### ISSUE TITLE
Manifests mark pasted content as protected

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#2114]
If a customer pastes content into a sample manifest, and doesn't override Excel's default options, then the content is marked as protected by default. This is due to the content being pasted in with the 'Normal' style, which on a protected sheet is flagged as protected by default. The solution is to update the normal style to ensure it isn't protected.

More information:
https://superuser.com/questions/392528/why-does-pasting-into-an-unprotected-cell-in-excel-protect-it

**Comment by radome** [comment]
Couldn't we remove password protected manifests all together? I think it would be preferable than having customers converting them to CSV for editing.

**Comment by JamesGlover** [comment]
Its not the customers converting them to CSV, its the SSRs. The password protection was added because customers were renaming columns and then complaining that their upload hadn't worked.
