### ISSUE TITLE
AssetRefactor

### ISSUE THREAD

**Issue by radome** [sanger/sequencescape#2177]
Brief summary of where the asset refactor is at:

1) Added migrations in db/migrate_asset_refactor
a. These will NOT run on rake db:migrate
b. Instead can be triggered by rake asset_refactor:migrate
2) These migrations create the labware and receptacles tables and migrate the data across, they rename the assets and container association tables to assets_bkp and container_associations_bkp
3) Sequencescape detects the presence of the labware table, and switched into refactor mode. This disables schema dumping, and also set a feature flag.
4) In places where behaviour needs to differ between pre- and post-refactor code you’ll see the following:

```ruby
# This block is enabled when we have the labware table present as part of the AssetRefactor
# Ie. This is what will happen in future
AssetRefactor.when_refactored do
  # Post refactor code
end

# This block is disabled when we have the labware table present as part of the AssetRefactor
# Ie. This is what will happens now
AssetRefactor.when_not_refactored do
  # Current code
end
```

Where possible I’m trying to ensure that we don’t need to use these feature flag switches too much, but a bit of use is inevitable.

A few other bits that you might come across:
- Some relationship information has been pulled out into the concerns folder as LabwareAssociations and ReceptacleAssociations these get included in the appropriate classes according to whether we’re in refactor mode or not.
- You might see the following in a few classes: 
```ruby
convert_labware_to_receptacle_for :association_name
```

This is just a wrapper to ensure compatibility with existing code, and will ensure that any labware with a single receptacle (such as a tube) will get converted to it corresponding receptacle if necessary. I’m currently logging a warning when this happens, but this will reduce the need to make extensive code changes until we’re ready.

**Comment by JamesGlover** [comment]
Initial prepatory code cleanup: https://github.com/sanger/sequencescape/pull/2157

**Comment by JamesGlover** [comment]
Adding the infrastructure described above:
https://github.com/sanger/sequencescape/pull/2182
Hold off merging this in until #2157 has had a chance to bed down a bit.

**Comment by JamesGlover** [comment]
At the validation stages, with most of the code merged in behind feature switches. Currently testing migrations against production-like data.

**Comment by JamesGlover** [comment]
So far confirmed no changes to batch.xml or warehouse messages. Integration suite passing, and some simple manual testing clear. Users notified of change, and DBAs emailed to discuss rollback options in the event of failure. (Migration rollbacks would be slow, and very dependent on me not having made any mistakes.)

**Comment by JamesGlover** [comment]
All ready to go live!

**Comment by JamesGlover** [comment]
Done!
