### ISSUE TITLE
GPL-220	"As lead for the loading team (Tris) I would like the unneeded task detailed feilds removed from the loading & read 1 & 2 screens in the Novaseq 6000 PE pipline in Sequancescape as the consumables and library tubes are RFID tagged and the instrument  reads tham"

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2495]
The only task detail fields remaining will be the 'workflow' & 'DPX-1' 'DPX-2' & 'DPX-3' fields.
Ideally default 'workflow' to 'standard' & only show 'DPX-1 to '-3' if workflow' is changed to 'XP'

**Comment by KatyTaylor** [comment]
After conversation with Tris 16/01/2020, new acceptance criteria are:

- Only field removed from 'Loading' screen will be 'Chip Barcode'
- Only fields removed from 'Read 1 & 2' screen will be:
    - Chip Barcode
    - Kit library tube
    - Buffer cartridge
    - Cluster cartridge
    - SBS cartridge
- Turn 'Workflow (Standard or XP)' into a dropdown

**Comment by KatyTaylor** [comment]
Ruby script attached for this story - @harrietc52 can you please review it on Monday? Thanks

[Script for GPL-220.txt](https://github.com/sanger/sequencescape/files/4076560/Script.for.GPL-220.txt)

**Comment by KatyTaylor** [comment]
Steps to get to the 'Loading' & 'Read 1 & 2' screens relevant to this story, in a dev environment:

1. Tab 'UAT'
    a) Generate Plate with purpose 'PF Lib Q-XP2' (can keep all other defaults)
    b) Note down the barcode
2. Home page -> 'Create Submission' 
    a) choose Template = 'Limber-Htp - Multiplexing - NovaSeq 6000 Paired end sequencing'
    b) Fill out Fragment size from and to ('1' for both is fine)
    c) Add Order
    d) Choose any study and project
    e) 'From Plate and Wells' - paste in your plate number
    f) Save Order, Build Submission
3. Make sure the submission processes ok:
    a) Note it says 'Your submission is currently pending.'
    b) make sure you have started the worker using bundle exec rake jobs:work
    c) refresh the page and make sure the message changes to 'Your submission has been processed.'
4. Tab 'Pipelines' -> 'NovaSeq 6000 PE' -> Notice there is an entry under 'Upcoming requests'
5. Cheat to get through the Limber Multiplexing step:
  a) Run attached script
6. Refresh pipeline page - entry should have moved to 'Available requests' section
7. Select it, make sure dropdown says 'Create Batch' and click 'Submit'
8. Under Actions, the 'Loading' and 'Read 1 & 2' links will take you to the relevant pages

[Limber multiplexing cheat script.txt](https://github.com/sanger/sequencescape/files/4076577/Limber.multiplexing.cheat.script.txt)

**Comment by KatyTaylor** [comment]
Once filled in, the data from the descriptors fields gets saved into the 'descriptors' field on the 'lab_events' table

**Comment by KatyTaylor** [comment]
Screenshots of 'Loading' and 'Read 1 & 2' screens after running the script (locally):

![Screenshot 2020-01-17 at 11 58 22](https://user-images.githubusercontent.com/10407809/72610985-c8462b80-3920-11ea-9168-304741ae2f3c.png)
![Screenshot 2020-01-17 at 11 58 32](https://user-images.githubusercontent.com/10407809/72610988-caa88580-3920-11ea-84de-015c160f617a.png)
