### ISSUE TITLE
GPL-273	As Chromium lead (Stef) I woudl like a new Library type 'Duplex-seq' because

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2499]
Q. Go live date?

TBD

Q. What is the library name?

‘’Duplex-seq’

Q. What are the request types?

TBD

Q. What LIMS changes are required?

Sequance scape?

TBD

Limber?

Q. Will this affect NPG analysis process?

(Please discuss this with NPG)

TBD

Q. Will this affect Faculty analysis process?

(please discuss this with the customer)

TBD

Q. Is there any remaining uncertainty?

A. Yes

**Comment by KatyTaylor** [comment]
Script for inserting the data required for this story:

[Script_Duplex-seq_library_type.txt](https://github.com/sanger/sequencescape/files/4164492/Script_Duplex-seq_library_type.txt)

**Comment by KatyTaylor** [comment]
Script for plate purposes fix: 
[plate_purposes_for_duplex_seq_script.txt](https://github.com/sanger/sequencescape/files/4214610/plate_purposes_for_duplex_seq_script.txt)
