### ISSUE TITLE
GPL-278	As a dev team we would like to investigate why/how we receive emails for each new project registered. This will become unsustainable if DToL creates +60K projects + project approved.

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2514]

**Comment by neilsycamore** [comment]
Message sent to all users with an authorized role type and for Projects the role type "administrator" (id 340) is set in user.rb, and as we are all administrators we get pinged

**Comment by neilsycamore** [comment]
History: Projects had to be approved post creation. Now approval is done pre generation.
Therefore function not required and discussed this with SSRs and they would SOOO happy if it went away

**Comment by JamesGlover** [comment]
Woo! That will be a nice simplification for us as well!

**Comment by KatyTaylor** [comment]
@neilsycamore what about the 'Project approved' emails - are they still needed?

**Comment by KatyTaylor** [comment]
Tested in UAT by looking at kibana logs as the emails are not actually sent in UAT, although couldn't find the relevant config to explain why.

From before deploying, when creating new Projects, got messages in kibana like:
![Screenshot 2021-01-14 at 15 38 58](https://user-images.githubusercontent.com/10407809/104612956-a344df80-567e-11eb-9bd6-ec9b335545e7.png)

After deploying, I didn't see any kibana messages like the above.
