### ISSUE TITLE
GPL-301 As a development team (esp Philip, Neil & Tom) we would like to send an aliquot plate creation event from SS to remove dependency on 5ul stamp event from asset audits as experience had demonstrated this is a fragile reporting  action for UK biobank reporting

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2532]
**User story**
GPL-301 As a development team (esp Philip, Neil & Tom) we would like to send an aliquot plate creation event from SS to remove dependency on 5ul stamp event from asset audits as experience had demonstrated this is a fragile reporting  action for UK biobank reporting

**Who the primary contacts are for this story**
Rich Livett <rl15@sanger.ac.uk>; 
Philip Jansen Van Vuuren <pj5@sanger.ac.uk>; 
Neil Sycamore <nts@sanger.ac.uk>; 
Eduardo Martin Rojo <emr@sanger.ac.uk>; Emma Gray <elg@sanger.ac.uk>

**Acceptance criteria**

- Raise event for all aliquot plate creation events
- One event / plate
- Event to include;
- source plate barcode (Thomas Whiteley <tw6@sanger.ac.uk> Wednesday, 12 February 2020 at 17:30)
- plate barcode,
- plate creation time
- supplier sample id
- study id (required to ensure join is not slow)
- No change to asset audits functionality and call to SS API*1

 
Dependency
 
·         Remove any report base table coupling between SS and UKB report*2
 
**Additional context**
Current event is fragile because
Operations can work if asset audits is unavailable, however cant process plates without plate barcode from SS. This makes using ‘aliquot plate creation’ more reliable.
Operation don’t always record this (Event is not lost is simply never created)
Operations don’t always know it’s a UK Biobank event and can record stamp as a ‘slf working dilution’ which is valid for lab but not for UK biobank report.
‘Missing’ 5ul stamp RTS cause a notable amount or rework

**Comment by TWJW** [comment]
Just to clarify the source plate barcode above IS the stock plate barcode.
