### ISSUE TITLE
GPL-343	As DNA pipelines team leaders (Rich R & Emma G) we would like for Submissions that have will have novaseq templates for teh SSR's to be able to speify if the flow cell type (SP, S4 or S2) and use of XP workflow (With XP, Without XP) to direct lab team (Tris)and billing (Rich R) [See GPL-341] 

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2563]
For submission templates containing * Novaseq*display options 

Label: Flowcell type
Drop down options for {SP, S4 or S2}

Label: XP workflo
Drop down options for {Yes. No}

**Comment by rl15** [comment]
![IMG_20200305_145450](https://user-images.githubusercontent.com/7222395/75993609-a7965d00-5ef1-11ea-915b-2d17bc72a518.jpg)

**Comment by JamesGlover** [comment]
I thought we agreed we wouldn't do this as the information is better obtained from NPG. We have the following issues:

1 - NPG capture what *actually* happened.
2 - In addition to hopefully rare mistakes, operations also need flexibility to better make use of availability or better allocate samples based on quality metric that aren't available upfront.
3 - As a result, customer requirements are only advisory
4 - Billing occurs based on what happened, not customer specification

So this would mean any information captured upfront would only ever be advisory, and thus shouldn't influence billing. In addition, it would probably be unwise to expose it in the WH, as it would cause confusion if it contradicted what *actually* happened.
