### ISSUE TITLE
GPL-345	As DNA pipelines team leaders (Rich R & Emma G) I would like to see in teh tableau billing report in Finace reports if XP workflow (or not) and the flowcell type (SP, S4 & S2) to save ~ 3 houres manual work / month [See GPL-341]

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2565]
**User story**
GPL-345	As DNA pipelines team leaders (Rich R & Emma G) I would like to see in teh tableau billing report in Finance reports if XP workflow (or not) and the flowcell type (SP, S4 & S2) to save ~ 3 hours manual work / month [See GPL-341]

**Who the primary contacts are for this story**
Richard Rance <rr1@sanger.ac.uk>

**Acceptance criteria**
Concatenate Flow cell  and if XP work flow has been used XP workflow to request type from down loaded report that can be accessed here https://globalreporting.internal.sanger.ac.uk/t/dna/views/UpfrontInvoicing_0/RevisedInvoicing?:iid=1&:isGuestRedirectFromVizportal=y&:embed=y#1

**Comment by rl15** [comment]
![IMG_20200305_163215](https://user-images.githubusercontent.com/7222395/76003216-a409d280-5eff-11ea-84b0-09f4059efe8c.jpg)

**Comment by JamesGlover** [comment]
We shoudl try and pull this information out of NPG tables, as it reflects reality. Will need to make sure that information is there.

**Comment by JamesGlover** [comment]
See https://github.com/sanger/unified_warehouse/issues/213
Flowcell type (More correctyl 'flowcell mode' is not currently exposed by NPG in ML Warehouse)

**Comment by KatyTaylor** [comment]
Removing from project as we might not have to do this work

**Comment by JamesGlover** [comment]
Closing in favour of: https://github.com/sanger/unified_warehouse/issues/386
