### ISSUE TITLE
GPL-356 As Development team (LIMS) we want to automatically create samples and their metadata in Sequencescape for heron samples to automate this high throughput process

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2574]
User story
As a development team when we receive a request from the csv parser to create a tube rack we want to create a tube rack, with the specified number of sample tubes and samples

Who the primary contacts are for this story
e.g. Eduardo

Acceptance criteria
To be considered successful the solution must allow:
1 - A tube rack will be created with the specified tube rack barcode that is sent in the request from csv parser
2 - The correct number of tubes will be created which will each have a sample, tube barcode and a position (rack location)
3 - Each sample created will have sample name, supplier sample name and the sample public name in sample metadata populated from the original tube barcode from the MLWH e.g. PHEC-nnnnnnnnnnnnn
4. - All of required sample metadata will be populated with default data as it is not available.

**Comment by emrojo** [comment]
Tasks:
* Create /api/v2/heron/tube_rack endpoint that will generate the tube rack by parsing the params (see comment) through a factory to build the rack (similar to how it was done in app/controllers/api/v2/aker/jobs_controller)

Create factories similar to how it was in app/aker/factories
* Create TubeRack factory to create the Rack labware with the rack barcode provided and delegates the tube creation to the tube factory
* Create Tube factory to create the SampleTube labware and put it inside the rack  with the barcode and location provided and delegates the Sample creation to the sample factory
* Create Sample factory that will create the Sample with metadata where the public name will contain the original tube barcode 
* Create test for the request to check that the request effectively creates the rack with the contents provided

**Comment by emrojo** [comment]
Proposal of message payload received by heron/tube_rack endpoint
```json
{
   "tube_rack": {
      "barcode": "ABC1234",
      "study_uuid": "000000000",
      "project_uuid": "000000000",
      "tubes": [
        {
         "location": "A01",
         "barcode": "FR12345",
         "sample": {
            "public_name": "PHEC-nnnnnnn1"
         }
        },
        {
         "location": "B01",
         "barcode": "FR12346",
         "sample": {
            "public_name": "PHEC-nnnnnnn2",
            "supplier_sample_name": "PHEC-nnnnnnn2"
         }
        }        
      ]
   }
}
```

**Comment by emrojo** [comment]
Required headers:
X-Sequencescape-Client-Id: <API_KEY>
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

**Comment by emrojo** [comment]
About acceptance criteria 3: the sample name has to be unique. That means that we cannot have 2 samples with same supplier_sample_id. My proposal is to use sanger_sample_id instead

**Comment by rl15** [comment]
Yes that’s correct.

I think we can also stop populating the public name:

On 21/03/2020, 09:30, "David K. Jackson" <david.jackson@sanger.ac.uk wrote:

we may want to revisit the use of public_sample_name if downstream [of NPG] have the capability to accept this ID separately (that would allow us to propagate say an NPG id with the sequence data, provide the phx_sample_id separating - makes for far like confusing data fixes).

On 21/03/2020, 10:14, "David K. Jackson" <david.jackson@sanger.ac.uk> wrote:

it's just I think downstream will have mechanism to import our supplier_sample_name rather than rely on us putting it in the CRAM header and renaming files to match.
