### ISSUE TITLE
GPL-357	(Heron) As Analysis lead (David Jackson) I would like a new sequancing type of 'Amplicon' to support analysis from the MLWH [RT686948]

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2578]
**User story**
GPL-357 As Analysis lead (David Jackson) I would like a new sequencing type of 'Amplicon' to support analysis from the MLWH

**Who the primary contacts are for this story**
David Jackson

**Acceptance criteria**
To be considered successful the solution must allow:
todo...

**Additional context**

**Comment by stevieing** [comment]
All you need to do is create a new StudyType via the command line. I have done this for UAT and Production.
