### ISSUE TITLE
GPL-358	(Heron) As Analysis lead (David Jackson) I would like a new primer_panel_id 'nCoV-2019' to support analysis from the MLWH [RT686948]

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2579]
**User story**
GPL-358	As Analyis lead (David Jackson) I would like a new primer_panel_id 'nCoV-2019' to support analysis from the MLWH [RT686948]

**Who the primary contacts are for this story**
David Jackson

**Acceptance criteria**
To be considered successful the solution must allow:

David anticipates that further primer_panel_id ill be required in time "nCoV-2019v2" (probably)

**Comment by stevieing** [comment]
Added two primer panels as per Katy's suggestion in UAT:
- nCov-2019-a
- n-Cov-2019-b

No point adding to production until we know this works.
