### ISSUE TITLE
BUG - When creating a bulk submission with a primer panel the primer panel still needs to be selected in the downloaded spreadsheet

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2582]
**Describe the bug**
When creating a bulk submission with a primer panel the primer panel still needs to be selected in the downloaded spreadsheet. It appears as a dropdown but you still need to add it for each well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page 'studies' and 'Start a bulk submission'
2. Fill in fields and select an appropriate primer panel
3. click button 'Generate Template'
4. When I open the downloaded spreadsheet the primer panel column is empty and you have to select it from a dropdown list.

**Expected behaviour**
The primer panel should be filled in when I open the spreadsheet.

**Additional context**
At scale there will be errors. People will forget to fill it in and it will slow them down. If they are creating 300 submissions a week this would save a lot of time.

**Comment by JamesGlover** [comment]
Issue appears to be that the form is generating a field named primer_panel_name, whereas the template is looking for primer_panel to populate it. I think it should just be a case of updating the column definition to use 'primer_panel_name' but I'm just making sure that it doesn't make more sense to update the form field name. (I think this would have wider repercussions, as it shares some behaviour with other submission behaviour)

**Comment by JamesGlover** [comment]
I'll also add a specific regression test for this bug, as essentially its an integration issue.

**Comment by JamesGlover** [comment]
Got things working for primer panels, just going to check the other columns for similar discrepencies

**Comment by JamesGlover** [comment]
Bait libraries show the same issue, fixing those in the same way
