### ISSUE TITLE
GPL-363 Migrate from axlsx to caxlsx [C=s,  V=3*]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#2584]
**User story**
As a developer I want to migrate to caxlsx from axlsx so that I can continue to receive updates.

**Acceptance criteria**
To be considered successful the solution must allow:
1 - Use the caxlsx gem in place of axlsx without any feature loss.

**Additional context**
caxlsx is a community fork of axlsx and is where most current development will be based. We're currently using our own custom fork of axlsx, but most of the changes in here were pulled from other user commits which hadn't been merged into axlsx yet, so hopefully these will be in the caxlsx fork.

**Comment by stevieing** [comment]
Already done.
