### ISSUE TITLE
GPL-374 Re-print barcodes from plates/new page

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#2602]
**User story**
As an SSR I would like to be able to come back to the plates/new page after creating plates using it, to print out the barcodes, in case they didn't print successfully the first time.

**Who the primary contacts are for this story**
Rich Clark & James Mack (& Danni Weldon)

**Acceptance criteria**
1. Way of printing barcodes in bulk on a group of plates created at one time using the plates/new page

**Additional context**
Don't think this is currently possible because there's nothing grouping those plates together - is there an alternative way of doing it?

**Comment by JamesGlover** [comment]
With https://github.com/sanger/sequencescape/pull/2604 we could at least allow printing of replacement barcodes from the feedback page, although this would only work until someone navigated away from the page.

**Comment by KatyTaylor** [comment]
Question - touched on by Rich C at some point I think -

What happens if the plates you've just created are the 'LHR RT' ones? If you print barcode from SS, presumably you get just the one barcode, but if you print them from Limber, you get 2 extra barcodes, for the PCR plates (this will go away when those PCR plates are tracked (GPL-375)).

Do we want this bulk print functionality from SS to print barcodes for just the RT plates, or somehow for those PCR plates as well?

**Comment by KatyTaylor** [comment]
Should we have some sort of more generic 'bulk print labels' page, where you paste in barcodes?

**Comment by KatyTaylor** [comment]
Got it working using Asset Groups:
<img width="1207" alt="Screenshot 2020-04-06 at 15 18 01" src="https://user-images.githubusercontent.com/10407809/78568618-43c9c180-781a-11ea-87f0-d787784530da.png">
<img width="1183" alt="Screenshot 2020-04-06 at 15 18 19" src="https://user-images.githubusercontent.com/10407809/78568623-46c4b200-781a-11ea-8fe5-78d430b05440.png">
<img width="1198" alt="Screenshot 2020-04-06 at 15 18 31" src="https://user-images.githubusercontent.com/10407809/78568627-49bfa280-781a-11ea-838e-acf7222a6a62.png">

**Comment by KatyTaylor** [comment]
Alternative to above could be something like this (notice the URL):

<img width="1199" alt="Screenshot 2020-04-06 at 16 43 14" src="https://user-images.githubusercontent.com/10407809/78577346-d91e8300-7825-11ea-990c-e864f03f05ce.png">

Where the plates/new page would generate the URL for you, but the plates are not grouped together in any way other than in the URL.

Pros:
* Not using up storage
* Not mis-using Asset Groups

Cons:
* Easy to forget to copy paste URL, and then it's lost.

**Comment by JamesGlover** [comment]
I'd vote for the asset group selection here, given the following caveats:

1. All wells on the created plates get added to the asset group
2. We de-duplicate the labware on the print page, preferably at the database level (ie. Asset group has many labware through receptacles (probably still called assets) with a distinct constraint

The asset group name should probably be something along the lines of the plate creator name and a timestamp.

**Comment by KatyTaylor** [comment]
@JamesGlover could you explain what you mean by 'the plate creator name' in above comment please? Thanks
