### ISSUE TITLE
GPL-411 Add functionality in Sequencescape to combine 1-4 source plates or tube racks to make the 384 RT plate

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#2618]
**User story**
As Sample Management we will need functionality in Sequencescape to create the 384-well RT plates from source tube racks or plates by quadrant.

**Who the primary contacts are for this story**
Lesley, Scott Thurston, Danni

**Acceptance criteria**
To be considered successful the solution must allow:
1. Creation of 384-well LHR-384 RT plates (or any 384-well plate purpose) from 1-4 source 96-well plates or 1-4 source 96-tube racks (it will mostly be tube racks and it will not be a mixture)
2. After creation the user should be taken to the standard plate view page, and ideally a plate label should be automatically printed off. 
3. The plate view should have some relatively easy way to see which parent plate is in which quadrant, perhaps using the plate name field.

**Additional context**
The user creating the RT plate in Sequencescape will likely be the same person performing the robot method, so they meed to clearly understand which parent plate has to be in which quadrant on the robot. Partly this is down to lab process, but they need a visual backup in the software.

**Comment by JamesGlover** [comment]
We used to have similar plate aggregation behaviour in one of the other pipelines (GBS?) conducted via cherrypicking, this worked but:

1) Was pretty much hated by the SSRs as it was incredibly time consuming
2) Wouldn't support tube racks

This ended up being the quad stamp in Limber. Currently Limber:
1) Is mainly used by library teams, not sample management
2) Doesn't support tube tracks
