### ISSUE TITLE
GPL-414 New plate type to cherrypick UK Biocenter  [RT 688547]

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2621]
**User story**
GPL-414 | As process development we need to add a new plate type for Sample Management to cherry pick from in order to support the processing of deep well plates from the UK Biocentre in Project Heron.

**Who the primary contacts are for this story**
Scott T (R&D)

**Acceptance criteria**
To be considered successful the solution must allow:
1. The name of the plate type to be added should be ‘KingFisher 96 2ml’.

**Additional context**

**Comment by JamesGlover** [comment]
PlateTypes have a maximum volume, assuming this is probably 2000 (as its in ul) but will check with Scott on the RT

**Comment by JamesGlover** [comment]
Note to anyone unfamiliar: Plate Type is a different thing from Plate Purpose and describes the physical shape of the labware. It gets passed to the Tecans to let them know information about tip positioning. From our perspective its just a name, and a maximum volume.

**Comment by JamesGlover** [comment]
> Hi James, 
> 
> That's right, the maximum volume would be 2000 ul for this plate, but it will always be a source plate rather than a destination plate. 
> 
> Thanks, 
> Scott.
