### ISSUE TITLE
GPL-415 ID positive samples for cherrypicking in QC report

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2623]
**User story**
GPL-415 | As a SSR (Rich C) I  need to be able to identify positive samples for the subset of plates processed by Sample Management for cherry picking (expecting QC report needs to be adapted to show this)

**Who the primary contacts are for this story**
Rich C (SSR)
Danni W (SM)

**Acceptance criteria**

Please read section 1.1: https://ssg-confluence.internal.sanger.ac.uk/x/OpoKBg 

To be considered successful it must:
The QC report as it stands now is fine, its just the addition of the disease state which needs adding to it.
1. Produce an excel file containing Plate ID, supplier IDs, Sanger Ids, well location and the information relating to disease state, as per manifest
2. It must contain all the plates which have been processed in Sample management and added to minilims for cherrypicking
3. It must identify all samples within the selection of plates to be processed for cherrypicking.
4. After identification of all the samples in the subset of plates, it must be able to filter for disease states (positive, negative or void)
5. It must be able to copy and paste sanger ID’s into the “create a submission” page.

**Additional context**

After discussion 5th May with Debbie and Rich C we have created a separate Heron product and added specific columns to that products criteria, including Phenotype (contains the disease state) and Sample Description (contains the Lighthouse Labs Root sample ID). Cuts out some other columns they don't need. All other product reports unaffected.

**On deploy**
Run
`bundle exec rake product_heron:add`

**Comment by rl15** [comment]
23rd April @13:05 Rich C wrote

The QC report as it stands now is fine, its just the addition of the disease state which needs adding to it.

1.       Produce an excel file containing Plate ID, supplier IDs, Sanger Ids, well location and the information relating to disease state, as per manifest
2.       It must contain all the plates which have been processed in Sample management and added to minilims for cherrypicking
3.       It must identify all samples within the selection of plates to be processed for cherrypicking.
4.       After identification of all the samples in the subset of plates, it must be able to filter for disease states (positive, negative or void)
5.       It must be able to copy and paste sanger ID’s into the “create a submission” page.

**Comment by andrewsparkes** [comment]
Change to requirements after discussion 5th May. See additional context above.

**Comment by KatyTaylor** [comment]
Deployment: 
run rake task `bundle exec rake product_heron:add`
