### ISSUE TITLE
GPL-420 new library type "PCR with TruSeq tails amplicon" for NPG

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2633]
**User story**
GPL-420 | As manager for NPG (David J) we need a new library type which describes a different way of creating PCR Amplicon Illumina sequencing ready libraries to the existing "PCR amplicon ligated adapters" which uses a ligation method [RT688782]

**Who the primary contacts are for this story**
David J
Nat S

**Acceptance criteria**
To be considered successful the solution must allow:
The new library type should be called "PCR with TruSeq tails amplicon" 
**Added:** An new library type should be called "PCR with TruSeq tails amplicon 384" 
**Added:** Both library types should be associated with Heron library creation request types

**Additional context**

**Comment by dkj** [comment]
Primary contact might be Naomi rather than Nat for this story (at the moment).

**Comment by JamesGlover** [comment]
Query sent via email:

> Hello,

> 
> Just a quick question regarding the PCR with TruSeq tails amplicon library type:
> 
> 1) I’m assuming this should be associated with the Heron request types (It will also be available for library manifests)
> 2) Do you need a 384 variation as well?
> 
> Thank you
> 
> James

**Comment by JamesGlover** [comment]
Received response

> Hi James
> 
> This type of library is likely required for both 96 and 384 plates types (more likely 384 if it comes out of R&D into ops) 
> 
> It will be associated with heron request types
> 
> Thanks
> 
> Naomi

**Comment by JamesGlover** [comment]
Updated pull request and initial story requirements.

Will need to run rake limber:setup on deploy
