### ISSUE TITLE
GPL-423 Lighthouse labs foreign barcodes in plate sample manifests for temporary process

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2634]
**User story**
As SSR's for Heron we would like to overwrite the plate sample manifest barcodes generated by SS with Lighthouse labs RNA plate barcodes to start & track the temporary process until the automated sample crawler can creates samples for us. 

**Who the primary contacts are for this story**
Rich C
James M
Deb P
James G
(Philip VV & Eduardo MR)

**Acceptance criteria**

Temporary process detailed section 1.1 here: https://ssg-confluence.internal.sanger.ac.uk/x/OpoKBg 

RNA plate Barcode standards 

There appears to be 4 variants of RNA plate barcode

1. nnnnnnnnnnNBC (Early UK Biocenter)
2. nnnnnnnnnANBC (Later UK Biocenter)
3. RNA_nnnn (Early Alderley park: Temporary barcodes on early plates)
4. AP-ccc-nnnnnnn (Later Alderley park: The new permanent barcodes are AP-rna-00110029 (note some RNA plates had the AP-kfr-00090016 barcode applied in error)

Key

n = number
c = character

**Additional context**

**Comment by JamesGlover** [comment]
Mapping four formats to three internally as 1 and 2 can easily be handled by a single regex without significant complexity.
Proposing:
- uk_biocentre
- alderly_park_early
- alderly_park

**Comment by JamesGlover** [comment]
Set up the following tests:
```
  describe Barcode::FormatHandlers::UkBiocentre do
    it_has_a_valid_barcode '1234567890NCB', prefix: nil, number: 1234567890, suffix: 'NCB'
    it_has_a_valid_barcode '123456789ANBC', prefix: nil, number: 123456789, suffix: 'ANCB'
    it_has_an_invalid_barcode 'INVALID'
    it_has_an_invalid_barcode '123456789NCB'
    it_has_an_invalid_barcode '123456789MBC'
    it_has_an_invalid_barcode '1234567890ANCB'
    it_has_an_invalid_barcode 'RNA_1234'
  end

  describe Barcode::FormatHandlers::AlderlyParkEarly do
    it_has_a_valid_barcode 'RNA_1234', prefix: 'RNA', number: 1234, suffix: nil
    it_has_an_invalid_barcode 'RNA_12345'
    it_has_an_invalid_barcode 'DNA_1234'
    it_has_a_invalid_barcode '1234567890NCB'
  end

  describe Barcode::FormatHandlers::AlderlyPark do
    it_has_a_valid_barcode 'AP-rna-1234567', prefix: 'AP-rna', number: 1234567
    it_has_a_valid_barcode 'AP-rna-00110029', prefix: 'AP-rna', number: 110029
    it_has_a_valid_barcode 'AP-kfr-00090016', prefix: 'AP-kfr', number: 90016
    it_has_an_invalid_barcode 'SD-rna-1234567'
    it_has_an_invalid_barcode 'AP-rna-12345678'
    it_has_an_invalid_barcode 'AP-cdna-1234567'
  end
```
The prefix, number and suffix behaviours are mostly to maintain compatibility with a handful of legacy systems, and should not affect operational behaviour. Instead it just ensures that you won't end up with a 'Something went wrong' page if you end up looking at the plate in one one of the older bits of Sequencescape.

**Comment by JamesGlover** [comment]
Ahh, the biocentre ones are slightly trickier than I first assumed, as the length of the number os coupled to the suffix. I'll see what I can do, but will split into two if the regex gets too complicated

**Comment by JamesGlover** [comment]
Question sent to Rich L via Slack:

> Hi Rich, the example Late Alderly park barcode (AP-ccc-nnnnnnn) suggests seven digits, but the two actual examples included have 8. I’m assuming that the latter is correct?

Reproducing here for reference

**Comment by JamesGlover** [comment]
Hadn't noticed the suffix in the UK Biocentre barcodes also transposes the B and C in the suffix. I'll handle these as two separate formats.

**Comment by JamesGlover** [comment]
Code pushed up, about to validate the given list of barcodes against this

**Comment by JamesGlover** [comment]
Identified a handful of barcodes which would not match:
 "01000001129NBC", "01000001071NBC", "RNADWP001", "RNADWP004", "RNADWP007", "RNADWP006", "RNADWP003", "RNADWP005", "RNADWP002", "010000985NBC", "0100000956NBC_", "0100000763ANBC", "0100000790ANBC", "010000661NBC"

**Comment by JamesGlover** [comment]
Validation code
```bad = []
File.open('barcode_list').each_line.map do |barcode_well|
  barcode_well.chomp.sub(/_[A-H]\d{2}\z/,'')
end.uniq.each do |barcode|
  format = Barcode.matching_barcode_format(barcode)
  if format
    puts "💚 #{barcode} = #{format}"
  else
    bad << barcode
    puts "💔 #{barcode}"
  end
end
```

Barcode list is just the extract RNA id columns

**Comment by JamesGlover** [comment]
Not sure what to do with the RNADWPnnn plates

**Comment by JamesGlover** [comment]
Also, seeing a few RNA_nnnn format ones in the MK list, not sure if that matters.

**Comment by JamesGlover** [comment]
Added the RNADWPnnn as uk_biocentre_unid
