### ISSUE TITLE
GPL-425 nCoV-2019/V3 primer panel in MX tube manifest 

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2635]
**User story**
GPL-425 | As representative for NPG (Nat S) we require NPG to be informed of the primer panel (e.g. "nCoV-2019/V3") which was used for the library prep of the PCR amplicon premade library

**Who the primary contacts are for this story**
Nat S
David J

**Acceptance criteria**
To be considered successful the solution must allow:

1. Primer_panel "nCoV-2019/V3" should be available in SSRs' MX tube manifest 
2. Primer_panel "nCoV-2019/V3" propagated to primer_panel field of iseq_flowcell table in ML warehouse

**Additional context**
Was RT https://rt.sanger.ac.uk/Ticket/Display.html?id=688443

**Comment by JamesGlover** [comment]
Via RT:

> Hello,
> 
> Changes to add primer panel to library manifests are now available for UAT at:
> http://uat.sequencescape.psd.sanger.ac.uk/
> 
> Changes:
> - The primer_panel column has been added to plate_library, tube_library, tube_library_with_tag_sequences, tube_multiplexed_library_with_tag_sequences manifests
> - Filling in the primer panel will set the primer panel on
> the aliquots in the created libraries
> - The field will display a dropdown of registered primer panels
> 
> This change should automatically propagate to the ML warehouse when the samples reach sequencing.
