### ISSUE TITLE
GPL-435 As Traction developers we would like an api v2 endpoint to allow us to retrieve plates, wells, samples and tags

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2640]
**User story**
As Traction developers we would like an api v2 endpoint to allow us to retrieve plates, wells, samples and tags because for heron they will be tagging samples with 96 PCR barcodes and we need to know thay they exist and what they are

**Who the primary contacts are for this story**
Stephen Inglis / Harriet Craven

**Acceptance criteria**
To be considered successful the solution must allow:
1. I should be able to make a request to an endpoint on the api/v2 using a list of plate barcodes
2. The response should include the plate along with the wells (position), samples (name, uuid) and tags (information to be decided).

**Additional context**

**Comment by JamesGlover** [comment]
This should already be available, with possibly just needing to extend the tag information. I'll pull out an example query shortly.

**Comment by JamesGlover** [comment]
```http://.../api/v2/plates?filter[barcode= DN550065I,DN550071G&include=wells.aliquots.sample```

Picked plates in training and production
