### ISSUE TITLE
BUG - default dilution factor not working correctly

### ISSUE THREAD

**Issue by pjvv** [sanger/sequencescape#2651]
**Describe the bug**
On the plate/new page, if a plate creator does not have a `valid_dilution_factors` entry in the `plate_creators` table, the JS on `app/views/plates/new.html.erb` does not work as expected as `(plate_creator_parameters[name] || defaultOption).valid_dilution_factors ` returns `undefined`.

**RT Ticket Number**
689589

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page /plates/new
2. Select a new plate and ensure that the `valid_options` field in the `plate_creators` table for that plate is empty
3. See no options for dilutions factor

**Additional context**
@emrojo resolved this by creating the missing `valid_options` by running something like this:
```
Plate::Creator.all.each do |c|
    if c.valid_options.nil?
      # Any other valid option will be set to 1
      c.update!(valid_options: {
                  valid_dilution_factors: [1.0]
                })
    end
  end
```

**Comment by JamesGlover** [comment]
Whoops, that'll be my fault. I was fixing an issue with older versions of chrome (The previous code was using some ES6 features)

**Comment by JamesGlover** [comment]
From Slack
> James(opens in new tab)  08:20
> Hmm, just trying to work out why the code doesn’t work as intended
> 08:20
> Especially as it did work in CI
> 
> Philip(opens in new tab):house_with_garden:  08:24
> My understanding: plate_creator_parameters[name] returns {} which is true in JS world then {}.valid_dilution_factors is undefined.
> 
> James(opens in new tab)  08:25
> Ahhh!
> 
> Philip(opens in new tab):house_with_garden:  08:25
> We could check if is plate_creator_parameters[name] is empty.
> 
> James(opens in new tab)  08:25
> Damnit, I was thinking it returned nil
> 08:25
> That’s what the previous code did, but it used ?. which is ES6 stuff not supported in older browsers
> 08:26
> And by nil I mean null of course
> 
> Philip(opens in new tab):house_with_garden:  08:26
> Were we having trouble with older browsers?
> 
> James(opens in new tab)  08:27
> On CI, but given the labs have XP machines I thought it worth fixing
> 08:28
> It wasn’t even massively old, Chrome 70
> 
> James(opens in new tab)  08:34
> Actually, thinking about it, we can probably just roll back to the old code, minus the safe navigation operator. I guess that’s what made me assume we were getting a null for plate creators without a specified dilution factor. As it is though, we’re only ever going to see a java-script object returned at that point.
> 08:35
> Long term we should consider yanking out all our inline js to be in files, that way we can run it all past babel and not have to worry about what might be supported or not
