### ISSUE TITLE
GPL-496 create 'Heron Lysed' purposes

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#2700]
**User story**
As a CGAP and Sample Management user, I would like new 'purposes' to track the plates and tube racks that hold lysates, which are going into the RNA extraction process, so that I can distinguish them from other plates or racks in the pipeline.

**Who the primary contacts are for this story**
Laura

**Acceptance criteria**
- [x] create a plate with purpose 'Heron Lysed Plate'
- [x] create a tube rack with purpose 'Heron Lysed Tube Rack'

**Additional context**
* Blocks sanger/wrangler#47 - wrangler story that creates these plates and racks
* See diagram https://app.lucidchart.com/documents/edit/068cc974-a783-4a9c-87c1-ec090ebecb56/0_0?shared=true for overview of the extraction process
* See https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=101361052 for technical discussion about tube racks and purposes

**Comment by pjvv** [comment]
Not sure what else there for this? 🤷‍♂️

**Comment by pjvv** [comment]
Sorry I haven't had a chance to get to this - wanted to do as much of GPL-472 as possible. Either someone can pick up the changes or include it in a larger refactor later on.

Suggestion from James:
> Pop them in separate task for now, and add it as a dependency of app:post-deploy eg.
task 'my_task' do
  do_stuff
end
task 'application:post_deploy' => 'my_task'

**Comment by KatyTaylor** [comment]
I'm merging it in as-is, to get the extraction stuff going, but we can do a larger refactor later on if we want, as you suggested.
