### ISSUE TITLE
GPL-528	Add priority to sample to support CGaP Heron automated release

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2746]
**User story**
GPL-528 | As a development team Laura, Rich C, Tom & Rich L we would like to add to an individual sample a priority to allow CGaP to release samples that we can then map this to a submissions priority (we inherit from highest on plate)

**Who are the primary contacts for this story**
Laura L
Tom W
Rich C
James M
James G

**Acceptance criteria**
See: https://ssg-confluence.internal.sanger.ac.uk/x/V6kKBg 

What levels of priority do we want per sample?

    0 will be used for non-Heron samples
    Backlog (integer value of 1)
    Surveillance (integer value of 2)
    Priority (integer value of 3)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
**Dependencies**
This story is requires [x517](https://docs.google.com/spreadsheets/d/1vMDtA7N2jgjY3kvvh88nO7b4NpX769mSA8MUsS0YXPk/edit#gid=0) in the CGaP Backlog to completed before to releasing to UAT
