### ISSUE TITLE
GPL-535 Update Tecan destination bed barcodes following upgrade

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2753]
**User story**
GPL-535 | As Sample management stakeholders (Danni, Ian & Scott T) we would like to change the Tecan destination bed barcode to ensure the correct bed is used for the destination plate when the work list is generated by SScape after June hardware upgrades

**Who are the primary contacts for this story**
Danni W
Ian S
Scott T
Iraad B

**Acceptance criteria**

Danni W wrote (Friday, 12 June 2020 at 16:15)

Tecan | Instrument sscape barcode | destination bed barcode
1 | 4880000008857 | 580020018655
2 | 4880000005825 | 580020018655
3 | 4880000004811 | 580020024861
5 | 4880000057855 | 580020024861
6 | 4880000058869 | 580020024861

**Dependencies**

**Additional context**
Checking this was not done as part of GPL-477
Andrew - No. UAT broke on Tecan bed verification due to layout differences. GPL-477 was dependant on this issue.

**Comment by andrewsparkes** [comment]
Made changes in UAT for testing.
Used Admin -> Robot Management screens in SS to make changes.
