### ISSUE TITLE
GPL-438 Record additional detail on asset_ausites

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#2758]
See: https://github.com/sanger/asset_audits/issues/141
**User story**
As Adam F, when I complete a bed verification in Asset Audits, I would like the audit record in Sequencescape to include which plates were scanned on which beds.

**Who the primary contacts are for this story**
Adam F

**Acceptance criteria**
To be considered successful the solution must allow:
1. 'Asset Audit' record in SS includes information about which plates were scanned on which beds
2. For all verifications or just new Heron ones?

**Comment by JamesGlover** [comment]
Covers the Sequencescape side of things for persisting data
- [ ] Migrate features to rspec
- [ ] Write migrations to add column
- [ ] Update model to serialize metadata
- [ ] Update tests for setting metadata
- [ ] Allow setting of metadata
- [ ] Update tests for viewing of metadata
- [ ] Add viewing of metadata
- [ ] Review need to add select scope which does not include TEXT column (performance)

**Comment by JamesGlover** [comment]
Hmm, might actually be able to use the MySQL JSON data type

**Comment by JamesGlover** [comment]
Yup. Works nice and smoothly

**Comment by KatyTaylor** [comment]
Before:
<img width="1187" alt="Screenshot 2020-06-17 at 10 12 49" src="https://user-images.githubusercontent.com/10407809/84879648-6599bd00-b083-11ea-8c92-c7ec1dbe66a7.png">

**Comment by JamesGlover** [comment]
After tweaks
![Screenshot 2020-06-18 at 13 22 41](https://user-images.githubusercontent.com/1283620/85019603-fc8b7580-b166-11ea-950e-4c31be72079c.png)
