### ISSUE TITLE
GPL-nnn As a developer or a user I would like to be able to add tags to a plate automatically

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2773]
**User story**
As a developer or a user I would like to be able to add tags to a plate automatically. Currently you need to add tags through libraries via a pipeline. R&D need to be able to tag samples so they can be run through an ONT pipeline in traction without running it through a high throughput pipeline.

**Who are the primary contacts for this story**
e.g. Steve.

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I want to be able to add tags to a plate of samples automatically
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
Would a library plate manifest with tag group and indexes work here, (Instead of the current one which is I believe by sequence) or do the samples need to exist in Sequencescape in an untagged form as well.

**Comment by stevieing** [comment]
> Would a library plate manifest with tag group and indexes work here, (Instead of the current one which is I believe by sequence) or do the samples need to exist in Sequencescape in an untagged form as well.

I think the point is here that users (R&D / Long Read) don't want to be adding the tags at all except by automation. For example they have been creating the plates in Sequencescape and these plates are then imported into traction. The samples need to have tags but the libraries are created in Traction. They know the strategy i.e. ONT PCR tags need to be added by column and it seems a waste of time for them to then add those tags manually by index or sequence in a manifest. Hope that makes sense?
