### ISSUE TITLE
GPL-552 Cherrypicking - Automated layouts need to place controls in all destination plates [m]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#2783]
**User story**
GPL-552 As an SSR I would like cherrypicks with controls which are generated by using the automated layout functionality to add controls to all the destination plates. Furthermore for the same batch those control wells in the destination plates should be shifted on each subsequent plate so that plate swaps can be identified in the resulting data.

**Who are the primary contacts for this story**
James Mack
Deborah Plowman

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] large batches with multiple destination plates should be laid out with the controls on all plates and in different locations

**Dependencies**
None

**Additional context**
Current automated layout places the specified control plate wells only on one destination (as no way to specify multiple picks). Manual csv generated layouts are fine as far as we can tell. Automated route likely to be used for lighthouse large batches.
NB. They have also stated that they do not mind about the automated layout generation splitting wells from a single source into multiple destinations, as SM see this regularly anyway and can cope with it fine.

**Comment by KatyTaylor** [comment]
A thought - maybe we should place the control on the first plate in a 'random' place, in case it's also useful to distinguish _between_ batches

**Comment by emrojo** [comment]
![image](https://user-images.githubusercontent.com/5426355/86275180-ca4c3000-bbca-11ea-9161-5f7563d5a72b.png)

Image for controls positioned in next well in subsequent plates created for the same batch

**Comment by emrojo** [comment]
Cherrypick from 6 plates x 96samples, partial plate with 2 wells at the beginning, template plate with 1 well at the end and applying controls:
Plates 1-3
![image](https://user-images.githubusercontent.com/5426355/86662796-f873aa80-bfe4-11ea-9b91-b1d8c1149e08.png)
Plates 4-6
![image](https://user-images.githubusercontent.com/5426355/86663044-3a9cec00-bfe5-11ea-831a-9c8e8f7d426a.png)
