### ISSUE TITLE
GPL-554 Support Glasgow barcode format

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#2803]
**User story**
As an SSR scanning Lighthouse plates into Asset Audits, I would like them to be imported correctly if they use the Glasgow barcode format. 

**Who are the primary contacts for this story**
Debbie

**Acceptance criteria**
To be considered successful the solution must allow:
- Barcodes like 'GLA001000R', 'GLA001001R' and 'GLA001002R' should be accepted by Sequencescape

**Additional context**
To see the list of Glasgow plates using our Lighthouse app, go to this url: view-source:http://uat.lighthouse.psd.sanger.ac.uk/samples?where=%22Lab%20ID%22==%22GLS%22

**Comment by rl15** [comment]
May be worth checking Cambridge also see https://github.com/sanger/crawler/issues/50

**Comment by KatyTaylor** [comment]
Response from Cambridge-AZ through PAM about barcode format - 
Q: Do you think the number of digits might increase? This is to ensure the system allows for longer barcodes if this is likely to happen.
A: Ours should all be 9 digit barcodes and should not change in the future


There are a few 10-digit barcodes (like '1087739340'), some of which are positive samples. They are all in the CB_sanger_report_200623_1109.csv file from sftp.
I guess we'll leave the validation at 9 or 10 digits, to allow these ones through.
