### ISSUE TITLE
GPL-557 BUG - auto-imported samples missing from stock_resource MLWH table

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#2811]
**Describe the bug**
One of the Heron reports uses the stock_resource table in the MLWH to link samples to studies (see https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/h.+Progression+reporting, '4.2.3 Give me all Heron COG-UK ids received from Lighthouse and the date (G.3)'). 

Many of the samples are missing from this table.

The samples imported by manifest are acting correctly - they have records in the stock_resource table.
The samples imported by the lighthouse app are incorrect.

We need to:
- change wrangler and lighthouse import (SS Heron endpoints) to send a message to MLWH to the stock_resource table
    - assume all plates / tubes imported this way are 'stock' (can change in future if start importing library tubes / plates this way
- back-fix the data in SS, and the MLWH (hopefully SS should propagate to MLWH automatically)

**Relevant code bits**
Well model `self.stock_message_template = 'WellStockResourceIO'`
Asset model `class_attribute :stock_message_template`
Asset model `def register_stock!`
sample_manifest > core_behaviour.rb `def generate_sample_and_aliquot ... register_stock!`

Code to modify will be in Heron endpoints, i.e. Heron/factories folder (for tube racks / tubes, and for plates / wells)

**Data investigation:**
Looking in the MLWH:

All relevant samples created before the end of April have a corresponding stock_resource record (stock.id_stock_resource_tmp is not null):
```
SELECT DISTINCT sample.name, sample.supplier_name, sample.created, stock.id_stock_resource_tmp
FROM sample
LEFT JOIN stock_resource stock ON stock.id_sample_tmp=sample.id_sample_tmp
WHERE SUBSTRING(sample.supplier_name,1,5) IN ('MILK-', 'ALDP-')
AND sample.created < '2020-05-01 00:00:00'
ORDER BY sample.created;
```

All relevant samples created after the end of April do not (change query section to `sample.created > '2020-05-01 00:00:00'`).

Looking in Sequencescape in the same timeframe:

All relevant samples created before the end of April were created by manifest upload (samples.sample_manifest_id is not null):
```
SELECT samples.name, studies.name, sm.supplier_name, samples.sample_manifest_id, samples.created_at
FROM samples
JOIN sample_metadata sm ON samples.id = sm.sample_id
JOIN study_samples ss ON ss.sample_id = samples.id
JOIN studies ON ss.study_id = studies.id
WHERE studies.name IN ('Heron Project', 'Heron Project R & D', 'Project Kestrel')
AND samples.created_at < '2020-05-01 00:00:00' 
AND SUBSTRING(sm.supplier_name,1,5) IN ('MILK-', 'ALDP-')
ORDER BY samples.created_at;
```

All relevant samples created after the end of April were created automatically by Asset Audits scanning in (samples.sample_manifest_id is null) (change query section to `samples.created_at > '2020-05-01 00:00:00'`).

**Comment by KatyTaylor** [comment]
P.S. It took a long time for me to find the relevant code for sending these stock_resource messages to the warehouse - so maybe worth refactoring, adding tests or at least a code comment as part of this story.

**Comment by neilsycamore** [comment]
RT Ticket: 693835

**Comment by KatyTaylor** [comment]
Testing the data fix (rake task):
Queries showing numbers in all environments:
```
SELECT DISTINCT sanger_sample_id, supplier_name, description, created
FROM sample
WHERE SUBSTRING(sample.supplier_name,1,5) IN ('MILK-', 'ALDP-', 'QEUH-')
AND sanger_sample_id LIKE 'Heron%';
-- 88,005 in training
-- 151,543 in prod
-- 5,141 in UAT

SELECT DISTINCT
sample.name
,sample.supplier_name
,sample.created
,submission_study.name AS 'submission_study'
FROM
sample
JOIN stock_resource stock ON stock.id_sample_tmp=sample.id_sample_tmp
JOIN study submission_study ON stock.id_study_tmp=submission_study.id_study_tmp
WHERE submission_study.name = 'Heron Project'
AND SUBSTRING(sample.supplier_name,1,4) IN ('MILK', 'ALDP', 'QEUH', 'CB')
ORDER BY stock.created;
-- 18,153 in training
-- 18,153 in prod
-- 0 in UAT
```

Output from testing rake task in training:
```
ubuntu@sss0-training:/var/www/sequencescape/current$ bundle exec rake auto_imported_samples:register_as_stock
RAILS_ENV=training environment is not defined in config/webpacker.yml, falling back to production environment
labware_samples count: 78579
labware count: 909
receptacles count: 78507
existing_stock_resource_messengers count: 0
receptacle_ids_with_messengers count: 0
registering as stock...
Done
```
The 'registering as stock...' section took about 5 minutes.
It will take significantly longer in prod, since ~43k new samples were added this week. It might be worth testing it again in training next week for this reason.

It inserted the Messenger records, but they did not propagate to the MLWH, because it looks like the training environment is not linked to a warehouse.

Tried same test in UAT:
```
ubuntu@sss0-uat:/var/www/sequencescape/current$ bundle exec rake auto_imported_samples:register_as_stock
RAILS_ENV=staging environment is not defined in config/webpacker.yml, falling back to production environment
labware_samples count: 94870
labware count: 1880
receptacles count: 11011
existing_stock_resource_messengers count: 122
receptacle_ids_with_messengers count: 122
registering as stock...
Done
```
Failed to register in the warehouse. Got these logs in kibana:
`No sample with uuid 'ac20f13a-c118-11ea-959e-fa163eac8e97'`
```
Delay: {"stock_resource":{"stock_resource_uuid":"ac083d70-c118-11ea-959e-fa163eac8e97","stock_resource_id":26858220,"created_at":"2020-07-08T13:43:49+01:00","updated_at":"2020-07-09T22:35:15+01:00","labware_type":"well","labware_coordinate":"G7","machine_barcode":"DN635104O","human_barcode":"DN635104O","concentration":null,"initial_volume":null,"current_volume":null,"snp_count":null,"pico_pass":"ungraded","gel_pass":null,"samples":[{"sample_uuid":"ac20f13a-c118-11ea-959e-fa163eac8e97","study_uuid":"468e0cd0-6a9d-11ea-a04f-fa163e68e77d"}]},"lims":"SQSCP_ST"}
```

**Comment by KatyTaylor** [comment]
To deploy this story:
1. Deploy Sequencescape as normal
2. Run rake task `auto_imported_samples:register_as_stock`

**Comment by JamesGlover** [comment]
Only saw this after I triggered the task, so haven't run the pre-queries on the WH
```
ubuntu@sss0-prod:/var/www/sequencescape/current$ bundle exec rake auto_imported_samples:register_as_stock
labware_samples count: 178239
labware count: 1972
receptacles count: 178239
existing_stock_resource_messengers count: 0
receptacle_ids_with_messengers count: 0
registering as stock...
Done
```

**Comment by JamesGlover** [comment]
```
SELECT DISTINCT sanger_sample_id, supplier_name, description, created
FROM sample
WHERE SUBSTRING(sample.supplier_name,1,5) IN ('MILK-', 'ALDP-', 'QEUH-')
AND sanger_sample_id LIKE 'Heron%'; // => 187002
```

**Comment by JamesGlover** [comment]
Second query significantly lower, but climbing rapidly, so I'll wait until it's sthbilized.

**Comment by JamesGlover** [comment]
Still rising...
