### ISSUE TITLE
GPL-564 UAT cherrypicking - Batch creation stack-depth problem

### ISSUE THREAD

**Issue by emrojo** [sanger/sequencescape#2821]
**Describe the bug**
On July 8 during uat, when trying to create a batch of 800 requests (1 for each of the 800 plates as source), it fill all memory and fails the action, so the batch couldnt be created.

What it triggers this batch creation is only to put all requests inside a batch, which it shouldn be an expensive operation, but we think the transaction in the process could be creating the problem.

Possible options for solution, but any more ideas would be much appreciated:
[ ] Add requests 1 by 1 to the batch with a request for each iteration instead of the whole group
[ ] Remove the transaction for the batch creation so it won't take so much memory
[ ] Add more memory to servers (more swap or ram)

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page pipelines / Cherrypicking
2. Select 800 requests to cherrypick
3. Click on 'Create batch'

**Expected behaviour**
It should create the batch

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by JamesGlover** [comment]
With these kinds of issue it's often a validator kicking off and loading a load of additional  records. Sometimes this even triggers N+1 queries, which instantiates lots of versions of the same record. Often adding a preload is sufficient. If not it might be possible to handle the validation manually in small batches, and then use a bulk insert to actually associate the requests with the batch.

**Comment by JamesGlover** [comment]
Actual exception we're seeing logged is:
```
A SystemStackError occurred in batches#create:

 stack level too deep
 app/controllers/batches_controller.rb:425:in `block in standard_create'
```

With a stacktrace:
```
-------------------------------
Backtrace:
-------------------------------

 app/controllers/batches_controller.rb:425:in `block in standard_create'
 app/controllers/batches_controller.rb:424:in `standard_create'
 app/controllers/batches_controller.rb:103:in `create'
```

This isn't a memory issue, but a stack-depth issue. Probably a recursive all somewhere.

**Comment by JamesGlover** [comment]
Bit more stack-trace via pry:
```
SystemStackError: stack level too deep
from /Users/jg16/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/to_sql.rb:820:in `each'
```

Which looks like we're falling over in our SQL generation. I think I've actually seen this before.

**Comment by JamesGlover** [comment]
This is building the requests query, not explicitly batch creation.

**Comment by JamesGlover** [comment]
It seems to be us chaining together a massive number of 'or' conditions.

**Comment by JamesGlover** [comment]
Options:
1) Build the query ourselves. This is what we used to do, back in the days before Rails added or support.
2) Chunk the query up into multiple statements. If we did this we'd probably need to extract the request ids, and then build up a new query, as otherwise we'll be passing back an array rather than a scope.

I'm going to do a little more poking, in case there are other options I'm overlooking.

**Comment by JamesGlover** [comment]
Looks like Arel gets quite complicated when building OR queries, and generates stuff like this:
```
SELECT requests.*, receptacles.labware_id AS labware_id FROM `requests` INNER JOIN `receptacles` ON `receptacles`.`id` = `requests`.`asset_id` INNER JOIN `request_types` ON `requests`.`request_type_id` = `request_types`.`id` INNER JOIN `pipelines_request_types` ON `request_types`.`id` = `pipelines_request_types`.`request_type_id` WHERE `pipelines_request_types`.`pipeline_id` = 12 AND `receptacles`.`labware_id` IS NOT NULL AND `requests`.`state` IN ('pending', 'hold') AND (((((((((((((((((((((((((`requests`.`submission_id` = 114111 AND ((((`receptacles`.`labware_id` = 26484072 OR `receptacles`.`labware_id` = 26484073) OR `receptacles`.`labware_id` = 26484074) OR `receptacles`.`labware_id` = 26484076) OR `receptacles`.`labware_id` = 26484077) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484842) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484843) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484849) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484850) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484851) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484852) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484853) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484854) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484855) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484856) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484857) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484858) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484859) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484860) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484886) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484887) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484888) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484889) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484890) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484891) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484892) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484893) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484894) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484895) OR `requests`.`submission_id` = 114109 AND `receptacles`.`labware_id` = 26484896) ORDER BY `requests`.`id` ASC"
```
You'll notices its grouping together shared submission ids and the like.

**Comment by JamesGlover** [comment]
So going to be building up the where condition manually, but hooking into the rails inbuilt sanitization to avoid nasty surprises. Bit of a mess at the moment, but should be able to refactor now most of the pipleine grouping options have been moved from attributes in the database onto the classes themselves.

**Comment by JamesGlover** [comment]
Fix working, but a mess at the moment. Now to refactor.
