### ISSUE TITLE
GPL-581 Cherrypicking happening in multiple runs should sort picks by destination well

### ISSUE THREAD

**Issue by emrojo** [sanger/sequencescape#2849]
**User story**
When cherrypicking to a plate that is created from merging several picks (several runs of a robot to create the plate), the plate is currently showing gaps between plate picks, but it would be better if they are picked consecutively in column order. See image at RT#694594

**Who are the primary contacts for this story**
Richard Clark

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] For every run, all well picks must follow column order, without leaving gaps, unless the well is a control
- [ ] If is a control, it has to be in the first run
- [ ] Controls can be in a random location

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
Follow up communication

> Hello,
>  
> When working on the plate pick story I ran across what might be a bug in GPL-581
> https://github.com/sanger/sequencescape/issues/2849
>  
> This was the story which specifies that plates should be sorted into picks based on well order, but with controls always appearing in the first pick.
>  
> Does control in this case refer to the samples coming from the control plate (ie. Plate DN626424D) or does it also include any samples from the customer which have been flagged as controls?
>  
>                 Just the control plate (i.e. Plate DN626424D. i.e. sample management controls)  We need to treat customer control effectively as samples as for all we know these have arrived contaminated.  The addition of SM controls would then highlight this as they would be processed and remain uncontaminated.
>  
> Currently its set to include customer controls. Which means:
>  
> 1) If a customer plate contains a customer control, then it will be sorted into the first pick, even if those samples are due to end up on the latter half of the plate. This would result in apparent gaps in the picking.
> 2) If you have a large number of customer controls, then all of them may be allocated to the first pick. Potentially this could force the actual control plate into the second pick.
>  
> The alternative:
>  
> 1) Samples from control plates, rather than control samples themselves, are sorted into the first pick.
>  
> This is a very simple change, and should actually improve performance as we don’t need to pull back the sample information.
>  
> Great, yes the focus here is solely on the SM controls.  The customer controls can be cherry-picked whenever :0)
>  
> James
