### ISSUE TITLE
GPL-588 help prevent SM missing a LH RNA plate through real time feedback against picklists 

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2860]
**User story**
GPL-588 | As process improvement specialist in SM (Eloise W) I would like a tool that provides real time feedback that all the RNA plate for LH cherypicking have been found for one or more pick list(s) to avoid leaving a positive sample behind.

**Who are the primary contacts for this story**
Eloise W (SM, & tool prototype implementer)
Danni W 
Rich C
James G (Dev on call when discussed on 14th July with above list)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] New page in SS showing 1 or more pick lists
- [ ] Provide real time visual feedback that after scanning a RNA plate, plate on pick list found (highlight green?)
- [ ] Feedback if plate scanned that's not on list.

**Assumptions**
No date need to be persisted after CP complete, tool simply provides feedback to user

**Additional context**
See attached file, working prototype in Excel
Sheet 1 Scanning in UI
Sheet 2 Picklist and found feedback
Sheet 3 User guide

This item deprecates GPL-572

**Comment by rl15** [comment]
Zipped to upload

[Assign_plate_to_picklist_final.xlsm.zip](https://github.com/sanger/sequencescape/files/4981646/Assign_plate_to_picklist_final.xlsm.zip)

**Comment by JamesGlover** [comment]
Other criteria extracted from spreadsheet:
[ ] Audio feedback when plate is in a pick
[ ] Plate list populated and indicates list of picks
[ ] Pick lists populated and indicates scanned plates
[ ] Distinguish between plates in multiple picks
