### ISSUE TITLE
GPL-597 Which of Ubuntu 10.04(physical) 12.04 VMs) can be decomissioned (& upgrade the rest)

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2867]
**Description**
GPL-597  Decommission a sub set of the following servers so only the ones that are required get upgraded to avoid wasting cognitive effort and power.

Physical

Server: psd2a
Description:    Ubuntu 10.04.4 LTS Product Name: ProLiant DL385 G7
Server: psd2b
Description:    Ubuntu 10.04.4 LTS Product Name: ProLiant DL385 G7
Server: psd2c
Description:    Ubuntu 10.04.4 LTS Product Name: ProLiant DL385 G7
Server: psd2d
Description:    Ubuntu 10.04.4 LTS Product Name: ProLiant DL385 G7
Server: psd2e
Description:    Ubuntu 10.04.4 LTS Product Name: ProLiant DL385 G7

VMS

Server: psd2h
Description:    Ubuntu 12.04.2 LTS Product Name: VMware Virtual Platform
Server: psd2i
Description:    Ubuntu 12.04.2 LTS Product Name: VMware Virtual Platform
Server: psd2j
Description:    Ubuntu 12.04.5 LTS Product Name: VMware Virtual Platform

**Who the primary contacts are for this work**
Pete J (Systems)

**Knowledge or Stake holders**
Individuals in team send request direct on 30 July 2020. Needs to be decision from team based on current state of the FCE for production
- [ ] Once agreed what can be turned off please update Incident Service Request 272892  (Pete Juhas {CMI: MCID1164370} )

**Additional context or information**
See GPL-592 [Research] Move pmb into psd-deployment and FCE #53 
We should aim to turn off the physical machines  in line with strategy for 2020 (accepting heron): https://ssg-confluence.internal.sanger.ac.uk/x/hoEKBg 3.4 section 'Services marked for deprecation' (note only a & b mentioned)

**Comment by stevieing** [comment]
Results of research can be found at [(https://ssg-confluence.internal.sanger.ac.uk/display/PSD/GPL-597+-+decomissioning+old+servers)]
