### ISSUE TITLE
BUG - updates by chromium manifests adds additional libraries

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#2868]
There’s a bug in SS chromium manifests where if a user changes the tag group and re-uploads it (with override) 
duplicates are added to the library tube meaning there are 4 libraries with one tag group and 4 with another tag group.  
The updates don't cascade to the pool/lane, the SSRs attempt to use tag substitution which then generically declares a tag clash BUT doesn't say where i.e. not the pool but the library tube.

https://rt.sanger.ac.uk/Ticket/Display.html?id=695176
Includes example of problem, can reproduce in training

**Comment by JamesGlover** [comment]
This was an agreed limitation of the original feature.
