### ISSUE TITLE
GPL-607 Cherrypicking - Order combination worksheet print by destination [size? s/m/l]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#2872]
**User story**
As Sample Management we would like the batch 'print worksheet' link at the right of the screen to order the worksheets sequentially by destination plate (and then pick) to make lab logistics more efficient.

**Who are the primary contacts for this story**
Rich C
Danni

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] print worksheet link on batch should order by destination plate

**Dependencies**
none

**Additional context**
See batch id 76968 and click 'Print worksheet' on right sidebar of screen. Worksheets are in random destination plate order.

**Comment by rl15** [comment]
Prioritized as a mid priority assuming was a mid sized feature. Rich C keen to do higher priority if is a small feature 1-2 days
