### ISSUE TITLE
BUG - As developers we need to stop the constant warning messages for crons

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2874]
**Describe the bug**
(WARN) /psg/webapp/crons/stop/production_monitoring_five_min.stop has remained untouched for 326.7 hours (stale lock file?)

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by JamesGlover** [comment]
1. Removing the stop file did not resolve issue
2. Cron involved was to send monitoring data to the old ganglia server

I've removed the cron that was generating the warning spam, but it will re-appear if we redeploy anything via the old deployment project.
