### ISSUE TITLE
GPL-612 - MX tube labels not showing NT barcode

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2878]
**Describe the bug**
Hi all,

On creating an MX library manifest and printing the MX tubes labels, the labels are only showing the study ID and the date printed. No NT barcodes. Please see attached.

Please could this be looked into as I know a bug was fixed recently for the printing of them but something has gone amiss since then.

Thank you,
Nat

**RT Ticket Number**
696859

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by stevieing** [comment]
Rogue tube barcodes:

- NT1638418B
- NT1638447G

**Comment by rl15** [comment]
Following on from stand up on 25th.  
Neil has closed RT as we have this backlog item.
Nat updated the RT on the 19th: https://rt.sanger.ac.uk/Ticket/Display.html?id=696859 - behaviour does look confusing.

**Comment by stevieing** [comment]
Nat and Rich Clarke to print out labels from various locations to check which ones are working and she will contact us tomorrow.

**Comment by JamesGlover** [comment]
> Morning all,

> 
> We have an update on this bug... Debbie generated a manifest and barcode absolutely fine (as circled in green in the attached image) from the study's manifest page.
> 
> I reprinted my problematic one from home, from the specific manifest page and James collected it and said it looked the same as my customer received it (middle set on the image). However, he tried printing the same tube label from the tube's specific SS page and it came out with the barcode but not the study ID (bottom set). BUT then he reprinted it again from the same tube page only for it to be missing the NT barcode that time.
> 
> So it's playing havoc! 
> 
> Thought you should know!
> 
> Thanks,
> Nat 

The various different locations for printing off labels do use different templates, so the differing behaviour isn't entirely surprising. I *thought* we had a story in the backlog to rationalise this a bit, but can't find it now, so its probably just something we discussed. This could easily explain the missing study id.

The missing barcodes on manifest printing is still funky though. Just probably dealing with one bug (plus some odd specs) rather than severall

**Comment by stevieing** [comment]
I had a look at the print labels code yesterday. Sounds like we need to do a proper research story and rationalise everything.
