### ISSUE TITLE
GPL-616 [Research] Warehouse 2 is not running, is it needed anymore?

### ISSUE THREAD

**Issue by emrojo** [sanger/sequencescape#2880]
**Description**

warehouse 2 has not been updated since the server was restarted, as the consumer didn't restart with it. Can we check if this is not needed anymore? If it is not needed we could decomission this machine, which is one of our current dependencies from old tin machines.

**Who the primary contacts are for this work**
Eduardo Martin

**Knowledge or Stake holders**
PSD helpdesk (Neil)
NPG (other warehouses access)

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by JamesGlover** [comment]
WH2 is currently our only source of historic information, making it very useful for debugging purposes. However we could consider just piping the messages straight into a mongo database or something like elastic-search. (Although that still leaves the question of existing  historic data.)

**Comment by stevieing** [comment]
No. It's gone.
