### ISSUE TITLE
GPL-617 Chromium manifests should perform tag substiution (C=S, V=3)

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#2882]
**User story**
See https://github.com/sanger/sequencescape/issues/2870 for some background

As an SSR I would like chromium manifests to perform tag-substitution on re-upload with tag changes like other library manifests. Currently that insert new aliquots with different tags.

Additional context points to the two points which will need to be updated to hook into the existing tag-substitution infrastructure.

**Who are the primary contacts for this story**
James G
Nat S
Lynda D (SSR Cellular)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Reupload of modified chromium manifests should update the tags in the library tubes and all downstream tubes

**Additional context**
Extracted from #2870 
Fixing re-upload:

- `SequencescapeExcel::SpecialisedField::ChromiumTagWell.update` should update the tags on the existing aliquots if there are already >1 aliquots in the well.
- `SampleManifestExcel::Upload::Processor::Base.update_samples_and_aliquots` should collect the substitution hash of all aliquots associated with the row, not just row.aliquot.

**Comment by neilsycamore** [comment]
In addition I tested re-uploading a manifest having amended the supplier name but without changing the tag data and I got a duplicate entry error (app/models/tag.rb:46:in `block in multitag!')

Could we then add to the acceptance criteria that 
'Re-upload of modified chromium manifests should update sample_metadata'?

**Comment by JamesGlover** [comment]
> In addition I tested re-uploading a manifest having amended the supplier name but without changing the tag data and I got a duplicate entry error (app/models/tag.rb:46:in `block in multitag!')
> 
> Could we then add to the acceptance criteria that 'Re-upload of modified chromium manifests should update sample_metadata'?

This *should* happen for free

**Comment by JamesGlover** [comment]
So while we should get the sample metadata updates for free, there's a bit of work to ensure that aliquot attributes correctly apply to all aliquots. This is mostly updating uses of 'aliquot' in specialised fields to match 'aliquots' instead
