### ISSUE TITLE
GPL-634 Sort Print plate labels on batch to match worksheets

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#2891]
**User story**
As sample management we would like the Batch 'Print plate labels' function to sort the plate barcode labels into the same order as the worksheets are sorted.

**Who are the primary contacts for this story**
Rich C

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Labels ordered same as for worksheets

**Dependencies**
None

**Additional context**
Worksheets are sorted by destination plate id. The barcodes are being fetched in the batches_controller print_plate_labels method, probably just needs to use the same batch.output_plates method as the worksheets.

**Comment by rl15** [comment]
Discussed with Rich C & James M on 20th October agreed to deprecate/archive low value given lens of Beckman robotics
