### ISSUE TITLE
GPL-651 I need to investigate why duplicate labwares are being created in Labwhere

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2907]
**Description**
Have a look at the labwhere reception and maybe the cron jobs to see if we can find out why duplicate labwares are being created

**Who the primary contacts are for this work**
Steve

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by JamesGlover** [comment]
In investigating the manifest performance, I noticed we don't have an index on barcode, let alone a uniqueness constraint. This opens up an easy race-condition. Adding the constraint would at least cause labwhere to error at the point this was occurring, rather than silently insert a duplicate.
