### ISSUE TITLE
GPL-663 Shorter short names for plate picks [small]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#2912]
**User story**
As a user of plate picks would be great if the default short names could be changed from “basket 1” to simply “1”. This would help us because we can scan faster than it takes the computer to say “basket”, which is repeated for each of the hundred-or-so plates we scan.

**Who are the primary contacts for this story**
Eloise W
James G

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The default short name should just be the number, not 'Basket n'

**Additional context**
app/javascript/plate-picks/store/actions.j:18
```
const new_pick = { ...pick, id, short: `Basket ${id}` }
```
to
```
const new_pick = { ...pick, id, short: `${id}` }
```

**Comment by rl15** [comment]
How big s/m/l
