### ISSUE TITLE
GPL-662 Sort pick lists before numbering [medium]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#2913]
**User story**
As a plate picks page (http://training.sequencescape.psd.sanger.ac.uk/plate_picks) user I would like the displayed picks to be sorted within each batch by destination barcode and pick order, and to be assigned 'basket' numbers in that same order.

**Who are the primary contacts for this story**
Eloise W
James G

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Within each batch, picks should be assigned 'basket' numbers based on destination plate order
- [ ] Pick ('basket') numbers should not change as new plates are scanned and new batches appear on the page (JG added this, mostly as I can see it causing massive issues)

**Additional context**
_Original message:_
> I’ve found a small bug: the picks aren’t always listed in numerical order. (E.g. See below DN671781 is followed by DN671784) Consequently, the basket names are assigned in the wrong order as well. This is workable, because we can change the names, but awkward because we normally work with around 40 baskets at any time, so that is quite a lot of names to find and change. Are you able to work it so the pick lists are ordered numerically?

(search barcode 'DN671557U' in http://training.sequencescape.psd.sanger.ac.uk/plate_picks to see the example she is talking about, and look at the order of the destination plates within the batch)

_James G implementation suggestions:_

Pick Ids get assigned by 'processPicks' which operates on each batch independently `app/javascript/plate-picks/store/actions.js:14`. This iterates over the picks attribute of batch, which is an array which ultimately comes from the PlatePicksController.

The `PlatePicks::BatchesJson` handles the rendering, but ultimately maintains the same pick order passed in in pick_information. Which is ultimately populated by `app/models/robot/verification/base.rb`.

This is very similar to issues we've fixed elsewhere in the past, where we used 'input_plates' instead, which has already been sorted. So I'd suggest updating this to do the same. One final gotcha however....

We're eager loading a lot of the information we require for generating the picks, and input_plates currently sorts using a scope. This will not only hit the database again, but throw away all our lovely eager loaded information.

The solution will look something like this:
app/models/robot/verification/base.rb (Use the sorted version)
```
  def all_picks(batch, max_beds)
    # @note No optimization yet.
    batch.output_plates.each_with_object({}) do |plate, store|
      store[plate.machine_barcode] = pick_number_to_expected_layout(batch, plate.machine_barcode, max_beds)
    end
  end
```

app/models/batch.rb (Only hit the database if you need to)
```
def output_plates
  if output_labware.loaded?
    output_labware.sort_by(&:id)
  else
    # We use re-order here as batch_requests applies a default sort order to
    # the relationship, which takes preference, even though we're has_many throughing
    output_labware.reorder(id: :asc)
  end  
end
```

Endpoint: http://training.sequencescape.psd.sanger.ac.uk/plate_picks

**Comment by rl15** [comment]
How big s/m/l
