### ISSUE TITLE
GPL-675 test print label from SS via  Sprint & Squix to reduce anxiety

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2927]
**Description**
GPL-675 | As the one risking an error of commission (Rich L) I would like to test print destination and control plate barcodes from SS using Sprint & Squix to reduce uncertainty  

**Who the primary contacts are for this work**
CGaP
Chris S
David R
Tom W

**Knowledge or Stake holders**
Lesley S
Scott T
Danni W

**Additional context or information**
Understand what labels we need to print to run an Beckman automated Cherry Pick: https://ssg-confluence.internal.sanger.ac.uk/x/royeBg (section 5)
Design a label for destination (and controls?): http://sprint.psd.sanger.ac.uk
Print from SS
Write up any notes what you learned.
Get a Squix moved to BOB
Raise a feature so can be used by SM to stress test

**Comment by rl15** [comment]
Steve I wrote in slack (11:34)

There is no label template designer for sprint but there is a graphql api.
We would either need to create a new service or add graphql support to Sequencescape. Luckily myself and Harry have some graphql experience from traction so we can apply it.

**Comment by rl15** [comment]
There's a GUI attached to the front of the SPrint application. The SPrint repo is https://github.com/sanger/sprint

**Comment by rl15** [comment]
This is what a CGAP template looks like


[slide.json.zip](https://github.com/sanger/sequencescape/files/5346327/slide.json.zip)

**Comment by rl15** [comment]
Tow W writes

o I guess if you want template like behavior between apps - it comes down to how GraphQL request templates are stored or shared…..
Or if no labels are shared between apps then perhaps it’s not so important

**Comment by stevieing** [comment]
Tasks I think we need to ensure we can test the printing. We don't need this in production for this story to be complete

- [ ] set up sprint locally
- [ ] create a label template for cherrypicking batch
- [ ] create small library in SS to print labels
- [ ] test connection between ss and sprint works locally
- [ ] ensure squix printer is correctly set up in lab ( port 21 and 80 need to be open)
- [ ] test labels can be printed in UAT

**Comment by rl15** [comment]
Chasing up on FTP from FCE via ACL avoiding IC direct to TC

**Comment by stevieing** [comment]
On hold. Nothing more we can do until the ACL is sorted.

**Comment by harrietc52** [comment]
Branch for Sequencescape side ready https://github.com/sanger/sequencescape/tree/GPL-675-sprint
