### ISSUE TITLE
GPL-677 BUG - Ongoing issues with failing batches

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2931]
**Describe the bug**
It looks like there is confusion when failing a batch about whether a batch is actually failed as the ui seems to give conflicting answers. We are also getting a 401 error which is indicating to the users that the action has failed.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to batches page
2. Select a batch
3. select plate layout
4. pick by ul
5. select number e.g. 35
6. click on next step
7. you should see plate map for selected plate layout
8. click next step
9. you should see finish cherrypick page
10. click release batch
11. you should see released batch
12. SSR realises they have made a mistake
13. go to batch page
14. find offending batch
15. select batch
16. fail batch or items
17. select fail all
18. select failure reason
19. add a comment
20. See error 'the page you are looking for doesn't exist'
21. go to batch page which says 'batch released'
22. click on fail batch or items
23. each request says it is failed
24. click on request which says it has passed

... confusion reigns!

3. See error

**Expected behaviour**
Batch should say it is failed??

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**
checking the data:
- state of batch is released
- state of each request is passed

**Comment by neilsycamore** [comment]
batch has a production state that is separate from state and gets set when the batch is failed BUT it should say it's failed.. it certainly used to

**Comment by JamesGlover** [comment]
Yeah, batch states are a little confusing, I think the two states are an attempt to separate qc state from progress state, which makes sense, but its not entirely clear. I know that failing all requests in a a batch is supposed to update the state automatically.

**Comment by JamesGlover** [comment]
And the 401 is weird, definitely didn't have that when I was testing things last time, although as that's an authentication error its possible that its either related to user permissions or redirects across domains resulting in invalid cookies.

**Comment by JamesGlover** [comment]
Hmm, so not seeing a 401 locally, but did get a 404 on training...

**Comment by JamesGlover** [comment]
Hmm, so training rendered the 404 for:
http://.../batches/77705/fail_items
Whereas locally I go redirected to:
http://.../batches/1/fail
As intended

**Comment by JamesGlover** [comment]
If we choose to fail nothing, then we don't get a 404, although the flash is empty. (But flagged as a success)

**Comment by JamesGlover** [comment]
I suspect we're raising an ActriveRecord::RecordNotFound somewhere, resulting in a 404.

**Comment by JamesGlover** [comment]
Okay, looks like something odd going on judging by the exceptions I'm seeing logged in kibana.

**Comment by JamesGlover** [comment]
Agh! So connecting to training from local, and attempting to reproduce and everything works okay. (Well, the state still displays wrong, but we don't show a 401/404)

**Comment by JamesGlover** [comment]
Buh?! Okay, so it looks like we're creating a failure reason for the requests, but not actually failing them. Which in turn means we don't fail the batch.

**Comment by JamesGlover** [comment]
So back on the 404, the logging is showing a proper redirect, but we seem to have another request being logged at the same time, which is generating a 50x:
```
Oct 13 10:04:25 sss1-training sequencescape[16106]: (thread-47435083772120) [13.17.0:training] FATAL -- : [17d9ddce-43de-4d21-ba69-8503eaa54603] ActionController::RoutingError (No route matches [GET] "/50x.html")
```

**Comment by JamesGlover** [comment]
This then ends up as a 404 as 50x.html isn't present

**Comment by JamesGlover** [comment]
Bingo. Turn on network logging in the browser and that 50x is a 502.

**Comment by JamesGlover** [comment]
And the 502 is coming from nginx:
```
ubuntu@sslb-training-theta:/etc/nginx$ tail /var/log/nginx/error.log
2020/10/13 10:04:25 [error] 1583#1583: *320 upstream sent too big header while reading response header from upstream, client: ***, server: ***k, request: "POST /batches/77705/fail_items HTTP/1.1", upstream: "http://***/batches/77705/fail_items", host: "***", referrer: "http://training.sequencescape.psd.sanger.ac.uk/batches/77705/fail"
```

So while the cookie size is fine if the request is direct, passing it through nginx appears to be causing problems with overall header size.

**Comment by JamesGlover** [comment]
So nginx buffers the headers, and the default buffer can be as small as 4kb, which is definitely too small for us here. (As that's out cookie alone) Can increase the buffer size or disable it completely

**Comment by JamesGlover** [comment]
Cool. Increasing the buffer size in training works. Just added the following to nginx.conf (naughtily updating the file on the server)
```
proxy_buffer_size 8k;
```

**Comment by JamesGlover** [comment]
Just working out the best way to add this in to the deployment process. As best I can tell we're using the default nginx.conf, and then include various files from conf.d. Ideally we'd keep the custom options in conf.d, but it didn't seem to like the http context here when I tried, so poking this further

**Comment by JamesGlover** [comment]
So the failure looks all to be a bit complicated, as its all wrapped up in some of the ancient Event code.

**Comment by stevieing** [comment]
> So the failure looks all to be a bit complicated, as its all wrapped up in some of the ancient Event code.

Can we strip it out and refactor? This is proper technical debt. Ops would really like this fixed.

**Comment by JamesGlover** [comment]
Yep, the event stuff is still quite heavily used, and we've even got lots of active requests hitting EventsController#create. So just a simple change to the actual state transition logic. Just want to run a few queries to scope out the changes in actual behaviour we can expect.

**Comment by JamesGlover** [comment]
Two things I'm checking:
1) Frequency of pass and fail events on the same request. Currently the second transition will be ignored. This is probably a bug, but it'll be nice to know if we need to warn anyone.
2) Frequency with which the events get called on requests that aren't in a started state. (This is somewhat trickier to work out)

**Comment by JamesGlover** [comment]
Scenario 1 is rare, last occurring in April 2019, where a request has a nts created fail event but is passed. Before that is 2015, where we have fail -> Pass, and that actually looks fine. We do have a large number of duplicate events, but that's fine.

**Comment by JamesGlover** [comment]
Starting looking into 2 by working out how many requests has a state that doesn't match the most recent event. This is complicated by having other routes to update state, but should be a starting point. (I'd rather not look at the request_events table)

**Comment by JamesGlover** [comment]
This is all looking sensible so far. A fair few of them, but all are either an incidence of this bug, or have comments explaining manual invervention.

**Comment by JamesGlover** [comment]
Request failure behaviour now working, and status is being passed onto the batch, but not showing due to the multiple different fields for tracking state. We have:

1) state
2) production_state
3) qc_state

Production state is the one being updated, but state is the one getting shown. Need to document exactly what each field does.

**Comment by JamesGlover** [comment]
All fixed up, just doing a final refactor pass
