### ISSUE TITLE
GPL-678 Verify PWGS pipeline model and backlog items and thier acceptance criteria 

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2932]
**Description**
GPL-678 | As a development team we need to understand the PWGS pipeline & check 3 backlog items and acceptance criteria

**Who the primary contacts are for this work**
Lesley S (NB anybody else as Lesley is also involved with Beckman?)

**Knowledge or Stake holders**

**Additional context or information**
Confluence doc: https://ssg-confluence.internal.sanger.ac.uk/x/W4meBg (includes process map)

**Comment by KatyTaylor** [comment]
Updated descriptions and added comments to following stories:
* https://github.com/sanger/limber/issues/518
* https://github.com/sanger/sequencescape/issues/2934
* https://github.com/sanger/sequencescape/issues/2935

**Comment by JamesGlover** [comment]
Closing as appears to be done.
