### ISSUE TITLE
GPL-694 BUG - SS Sample view page not saving data (PSDTHV)

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#2937]
Users unable to add sample data using the edit function as the new data is not saved.
This is specific to the N/A - Value boxes other fields are ok
![Screen Shot 2020-10-13 at 10 04 23](https://user-images.githubusercontent.com/299768/95840262-d738fd80-0d3b-11eb-85e6-42f145d91ca7.png)

raised in RT701951 (ncb)

**To Reproduce**
http://sequencescape.psd.sanger.ac.uk/samples/1049088
Edit RHS
go to phenotype OR donor id
click on down arrow select value
enter value
Save sample
new data is not displayed in view
(not a caching issue as data not in db)

**Expected behaviour**
That the data should be saved!
True for:
* Windows and Mac
* Browsers Chrome and Firefox

**Comment by JamesGlover** [comment]
Hmm, I think I fixed a similar bug on the studies page. The problem was fields which were flagged as 'required' but were then getting hidden. There was some code in place to handle the issue, but it wasn't firing correctly if you had several fields dependent on each other. Will track down then issue.

**Comment by JamesGlover** [comment]
Hmm, can't find the issue, or commits. It was quite a while ago.

**Comment by KatyTaylor** [comment]
@JamesGlover 
I fixed these a while ago - might be relevant?
* https://github.com/sanger/sequencescape/pull/2454
* https://github.com/sanger/sequencescape/pull/2456

**Comment by neilsycamore** [comment]
Also the following fields are set to defaults
GC content: Neutral
Sample visibility: Hold
DNA source: Genomic
Where previously they were 'Not specified' in SS, nil in the sample_metadata
