### ISSUE TITLE
GPL-693 BUG - MLWH study_user table not updating

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#2942]
When a contact/collaborator is removed from a study in Sequencescape the entry in the mlwh persists

**RT Ticket Number**
702503

**To Reproduce**
http://sequencescape.psd.sanger.ac.uk/studies/8/collaborators
add yourself as follower
go to mlwh.study_user 
find id_study_temp = 6
note users
in Sequencescape remove yourself
in mlwh.study_user user persists

**Expected behaviour**
in mlwh.study_user user is removed

**Additional context**
James G added
So based on past fixes:
1) Removal of the role_user entry wasn’t updating the study message in the WH. I had to uses **touch** to ensure that the timestamp on the study was updated, as otherwise the message wouldn’t have a more recent timestamp than the existing one. ( I think this took a couple of passes, as I don’t think I updated the timestamp first time round)

2)I think I might have needed to update the WH itself at some point to ensure existing relationships were purged. Its possible that this was just done on warehouse_two, and the unified WH may still be using the older code. Not sure though, it was a few years ago and is only a vague memory.

**Comment by JamesGlover** [comment]
Oddly, there are tests on the WH side of things:
https://github.com/sanger/unified_warehouse/blob/master/spec/support/it_behaves_like_associated_with_roles.rb

**Comment by JamesGlover** [comment]
And this is included in the study spec:
https://github.com/sanger/unified_warehouse/blob/master/spec/models/study_spec.rb

**Comment by JamesGlover** [comment]
Looks like the study isn't being touched as intended.

**Comment by JamesGlover** [comment]
Odd, I've written a unit tests to cover the particular behaviour that is used, but in isolation its working correctly. I guess an integration test is in order.

**Comment by JamesGlover** [comment]
Buh, Integration tests work as well....

**Comment by JamesGlover** [comment]
Bingo! The bug triggers if we have multiple users with the same role.
