### ISSUE TITLE
GPL-696 Automate UKB manifest upload

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2943]
**User story**
GPL-696 | As SSR for UKBiobank (Rich C) I would like to automate the UKB manifest upload to sequancescape because <TBD>

**Who are the primary contacts for this story**
Rich C

**Acceptance criteria**
TBD - token for a conversation

To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by rl15** [comment]
Rich C writes (Tuesday, 20 October 2020 at 09:21)

The process should resemble:
1.       SSR to download encrypted manifest
2.       SSR to open password protected manifest
3.       SSR to check plate barcode for typos and edit accordingly, thus matching the created plate barcodes in the UKB study.
4.        SSR to move the manifest to a specific location where the file will be automatically picked up and uploaded into sequence scape.
 
I can supply previous UKB manifests which are a defined format and will not change. This is needed to remove human error and expedite the process.

**Comment by rl15** [comment]
I don't want to create any further file share/file drops if we can avoid this.

**Comment by JamesGlover** [comment]
Do we have more information on the typos? How can these be detected/corrected automatically?

**Comment by rl15** [comment]
In stand up on 1st April Operation agreed can be deprecated as UKB contract ends in 2021
