### ISSUE TITLE
GPL-722 Chromium 10X research pooling the three 5 prime VDJ libraries

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#2947]
**Description**
As Stef I would like to be able to pool up to 3 library types at the end of the Chromium 10X 5 prime VDJ pipelines.

**Who the primary contacts are for this work**
Stef L

**Knowledge or Stake holders**
James G
Andrew S

**Additional context or information**
We think Sequencescape may be set up specifically to not allow pooling of different library types (presumably to prevent mistakes). In Chromium 10X we are splitting a sample into 3, and preparing 3 distinct libraries, but would like them to be analysed together as they give complementary information. Plus less sequencing resources.

**Comment by JamesGlover** [comment]
We added the ability to pool different library types to support one of the previous pipelines, but this got removed again due to issues it was causing failing wells (according to a comment in the submission documentation in confluence). I'll see if I can track down the exact details.

**Comment by JamesGlover** [comment]
I think this is the commit where we originally allowed mixing of library types:
https://github.com/sanger/sequencescape/commit/550e2714ce4a3548ad9bf9827c9de6e5bd98334a#diff-55a9e87628b4a7d890529b27b5208dca160b624d693bda396811602f89602448

I *think* this was related to the GBS pipeline, but there was some bespoke into limber work going on at the same time, so it may have been related to that.

**Comment by JamesGlover** [comment]
Can't currently find the restriction mentioned in the confluence page.

**Comment by andrewsparkes** [comment]
Stef can use the poolings/new screen in Sequencescape to pool the 3 library pool branches together at the end of the pipeline from the Lib Pool Norm tubes. As they've only got one 10X tag plate (supplied by manufacturer), they are limited to running only 32 samples and staggering the tagging in the 3 pipelines by 32 to avoid tag clashes.
