### ISSUE TITLE
GPL-723	BUG: Plate Location Reports in Sequancescape failing with 'Failed to create report: 

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2949]
**Describe the bug**
GPL-723 | BUG: Plate Location Reports in Sequancescape failing with 'Failed to create report: That selection returns no plates, no report generated.'

**RT Ticket Number**
N/a

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page 'http://sequencescape.psd.sanger.ac.uk/location_reports'
2. Fill in Create a report by selection sections

- Report name
- Study
- Copy & paste list of barcodes (tested separated by new lines, spaces or commas)

3. See error
Failed to create report: That selection returns no plates, no report generated.

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Mac
* Browser  Firefox,
* Browser version 70.0 (64-bit)

**Additional context**
See slack channel conversation in heron-ss on 28th October

**Comment by JamesGlover** [comment]
Exception email, with sensitive data anonymised:
An URI::InvalidURIError occurred in location_reports#create:



  bad URI(is not URI?): "http://labwhere_host/api/locations/AAA DDD EEE FFF"

  lib/lab_where_client.rb:26:in `get'





-------------------------------

Request:

-------------------------------



  * URL        : http://sequencescape_host_name/location_reports

  * HTTP Method: POST

  * IP address : xxx

  * Parameters : {"utf8"=>"✓", "location_report"=>{"name"=>"report_name", "location_barcode"=>"AAA DDD EEE FFF", "report_type"=>"type_labwhere"}, "commit"=>"Create report from labwhere", "controller"=>"location_reports", "action"=>"create"}

  * Timestamp  : 2020-10-28 10:33:37 +0000

  * Server : prod-host-server

    * Rails root : /var/www/sequencescape/releases/20201026231646

  * Process: 25961



-------------------------------

Session:

-------------------------------



  * session id: "2d372ca9d34beb86a8c724ba3a97e634"

  * data: {"session_id"=>"2d372ca9d34beb86a8c724ba3a97e634", "user"=>1009}



-------------------------------

Environment:

-------------------------------



  * CONTENT_LENGTH                                         : 219

    * CONTENT_TYPE                                           : application/x-www-form-urlencoded

    * GATEWAY_INTERFACE                                      : CGI/1.2

    * HTTP_ACCEPT                                            : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

    * HTTP_ACCEPT_ENCODING                                   : gzip, deflate

    * HTTP_ACCEPT_LANGUAGE                                   : en-US,en;q=0.5

    * HTTP_CONNECTION                                        : close

    * HTTP_COOKIE                                            : _ga=GA1.3.991229387.1579096283; ajs_user_id=%222786462f3efdc789870b7e1b35479233006137ab%22; ajs_anonymous_id=%22a7d04ed3-80ad-4e5e-8a89-97c9a2610601%22; _sequencescape_session=cWNJdG1Yb2tUWGZUUTRRMC8wUkxGUUw3bHE2eGFOcDZzNXBSOFN2UlIrc3B0VnF1VGZzR0FsclRoakljNTNSR2hoT0ZWSjh6blVIQnliU3ZkREdxR1E9PS0tWUFCNVBSSTZlc2ZuN1ZhR0pJdEJjZz09--456cd4839fbb758b875c7725a9da45687cd3ef1c

    * HTTP_HOST                                              : sequencescape_host_name

    * HTTP_ORIGIN                                            : http://sequencescape_host_name

    * HTTP_REFERER                                           : http://sequencescape_host_name/location_reports

    * HTTP_UPGRADE_INSECURE_REQUESTS                         : 1

    * HTTP_USER_AGENT                                        : Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0

    * HTTP_VERSION                                           : HTTP/1.0

    * HTTP_X_FORWARDED_FOR                                   : ,xxx

    * ORIGINAL_FULLPATH                                      : /location_reports

    * ORIGINAL_SCRIPT_NAME                                   :

    * PATH_INFO                                              : /location_reports

    * QUERY_STRING                                           :

    * REMOTE_ADDR                                            : xxx

    * REQUEST_METHOD                                         : POST

    * REQUEST_PATH                                           : /location_reports

    * REQUEST_URI                                            : /location_reports

    * ROUTES_46948902983420_SCRIPT_NAME                      :

    * SCRIPT_NAME                                            :

    * SERVER_NAME                                            : sequencescape_host_name

    * SERVER_PORT                                            : 80

    * SERVER_PROTOCOL                                        : HTTP/1.1

    * SERVER_SOFTWARE                                        : puma 4.3.5 Mysterious Traveller

    * action_controller.instance                             : #<LocationReportsController:0x00007f0b7a05d818>

    * action_dispatch.authenticated_encrypted_cookie_salt    : authenticated encrypted cookie

    * action_dispatch.backtrace_cleaner                      : #<Rails::BacktraceCleaner:0x0000556651efd208>

    * action_dispatch.content_security_policy                : #<ActionDispatch::ContentSecurityPolicy:0x000055664cc7bcf0>

    * action_dispatch.content_security_policy_nonce_generator: #<Proc:0x000055664cc7bbb0@/var/www/sequencescape/releases/20201026231646/config/initializers/content_security_policy.rb:33 (lambda)>

    * action_dispatch.content_security_policy_report_only    : true

    * action_dispatch.cookies                                : #<ActionDispatch::Cookies::CookieJar:0x00007f0b7a051d60>

    * action_dispatch.cookies_digest                         :

    * action_dispatch.cookies_rotations                      : #<ActiveSupport::Messages::RotationConfiguration:0x00005566498b5c90>

    * action_dispatch.cookies_serializer                     : hybrid

    * action_dispatch.encrypted_cookie_cipher                :

    * action_dispatch.encrypted_cookie_salt                  : encrypted cookie

    * action_dispatch.encrypted_signed_cookie_salt           : signed encrypted cookie

    * action_dispatch.http_auth_salt                         : http authentication

    * action_dispatch.key_generator                          : #<ActiveSupport::CachingKeyGenerator:0x000055664ff52098>

    * action_dispatch.logger                                 : #<Syslog::Logger:0x000055664c932c88>

    * action_dispatch.parameter_filter                       : [:password, :password, :credential_1, :uploaded_data, :password]

    * action_dispatch.redirect_filter                        : []

    * action_dispatch.remote_ip                              : xxx

    * action_dispatch.request.content_type                   : application/x-www-form-urlencoded

    * action_dispatch.request.formats                        : [#<Mime::Type:0x000055664a3e9bc0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=3650515312319772383>]

    * action_dispatch.request.parameters                     : {"utf8"=>"✓", "location_report"=>{"name"=>"report_name", "location_barcode"=>"AAA DDD EEE FFF", "report_type"=>"type_labwhere"}, "commit"=>"Create report from labwhere", "controller"=>"location_reports", "action"=>"create"}

    * action_dispatch.request.path_parameters                : {:controller=>"location_reports", :action=>"create"}

    * action_dispatch.request.query_parameters               : {}

    * action_dispatch.request.request_parameters             : {"utf8"=>"✓", "location_report"=>{"name"=>"report_name", "location_barcode"=>"AAA DDD EEE FFF", "report_type"=>"type_labwhere"}, "commit"=>"Create report from labwhere"}

    * action_dispatch.request.unsigned_session_cookie        : {"session_id"=>"2d372ca9d34beb86a8c724ba3a97e634", "user"=>1009}

    * action_dispatch.request_id                             : d07131e3-5567-46c9-a29f-cc1990980eac

    * action_dispatch.routes                                 : #<ActionDispatch::Routing::RouteSet:0x00005566495eadf8>

    * action_dispatch.secret_key_base                        : Really?! we should definately NOT email out that!

    * action_dispatch.secret_token                           :

    * action_dispatch.show_detailed_exceptions               : false

    * action_dispatch.show_exceptions                        : true

    * action_dispatch.signed_cookie_digest                   :

    * action_dispatch.signed_cookie_salt                     : signed cookie

    * action_dispatch.use_authenticated_cookie_encryption    : false

    * puma.config                                            : #<Puma::Configuration:0x0000556648c243c8>

    * puma.request_body_wait                                 : 0

    * puma.socket                                            : #<TCPSocket:0x00007f0b7a06be90>

    * rack.after_reply                                       : []

    * rack.cors                                              : #<Rack::Cors::Result:0x00007f0b7a06b030>

    * rack.errors                                            : #<IO:0x00005566485c4140>

    * rack.hijack                                            : #<Puma::Client:0x00007f0b7a06be68>

    * rack.hijack?                                           : true

    * rack.input                                             : #<StringIO:0x00007f0b7a06b968>

    * rack.multiprocess                                      : false

    * rack.multithread                                       : true

    * rack.request.cookie_hash                               : ...

    * rack.request.cookie_string                             : ...

    * rack.request.form_hash                                 : {"utf8"=>"✓", "location_report"=>{"name"=>"report_name", "location_barcode"=>"AAA DDD EEE FFF", "report_type"=>"type_labwhere"}, "commit"=>"Create report from labwhere"}

    * rack.request.form_input                                : #<StringIO:0x00007f0b7a06b968>

    * rack.request.form_vars                                 : [FILTERED]

    * rack.request.query_hash                                : {}

    * rack.request.query_string                              :

    * rack.run_once                                          : false

    * rack.session                                           : #<ActionDispatch::Request::Session:0x00007f0b7a05e998>

    * rack.session.options                                   : #<ActionDispatch::Request::Session::Options:0x00007f0b7a05e948>

    * rack.tempfiles                                         : []

    * rack.url_scheme                                        : http

    * rack.version                                           : [1, 3]



-------------------------------

Backtrace:

-------------------------------



  lib/lab_where_client.rb:26:in `get'

  lib/lab_where_client.rb:165:in `find_by_barcode'

  app/models/location_report/location_report_form.rb:121:in `find_labwhere_location'

  app/models/location_report/location_report_form.rb:71:in `check_labwhere_location_exists'

  app/models/location_report/location_report_form.rb:51:in `save'

  app/controllers/location_reports_controller.rb:37:in `block in create'

  app/controllers/location_reports_controller.rb:36:in `create'

**Comment by KatyTaylor** [comment]
Investigation so far:

* Haven't tested in Prod but have in local, UAT and training
* The following steps generate a report successfully:
    * Go to UAT tab, click 'Generate Plate'
    * Plate count = 2, Study = "UAT Study", leave the other defaults
    * Go to /location_reports
    * Report name = "whatever you like", Study = "UAT Study", List of Barcodes = <paste the barcode on separate lines>
    * Click "Create report from selection"
    * Get green success message
* I managed to get failure messages but this was only when the plate barcodes that I tried were not in the study that I picked - maybe this was the issue?
* I initially thought the issue was due to the error in the console "[Report Only] Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https: 'nonce-6qUG0LXDTqML9WdeEmdxwA=='"."
* The above is due to the library 'pdfmake', which seems to work with 'datatables', and has a dependency 'foliojs/restructure' that violates some CSP rules.
* However, if I disable this locally it makes no difference.

@rl15 I couldn't access the Slack conversation from 28th Oct you mention in the issue description, because it's too far in the past. Is it possible you selected the wrong Study for the plate barcodes? Can you reproduce the issue now?
Thanks!

**Comment by KatyTaylor** [comment]
Putting 'on hold' for now as couldn't reproduce - see previous comment.

**Comment by rl15** [comment]
Contacted James M & Danni on 2nd. James M wrote (Wednesday, 2 December 2020 at 09:20)

I tried using this again on 18/11 and I still had missing data so I reverted to the labwhere tableau report.

**Comment by KatyTaylor** [comment]
Figured out why this was not working for James M. This is how he was using it:

> I was looking to get the locations to inform the team of where the plates are for destruction. As it turns out they don’t need the locations of all the individual plates just the box locations so I don’t think I will need to use this again for this purpose but it is good to check anyway I guess.

For a list of 1000 barcodes he sent me the report only returned 215. This turned out to be because the plates were not in Sequencescape. As this is a Sequencescape page, it will only retrieve the LabWhere location for a plate if it is also in Sequencescape. Response from James confirms this makes sense:

> Ah that seems so simple yet never even crossed my mind. The majority of them would probably not be in sequencescape as I was trying to find samples for destruction from the reefers – many of which would not have been processed or uploaded via sentinel.
 
> This would also explain why this page seemed to work fine once before when I was making a list of purely “cherrypicks done” boxes, as all those plates would have been uploaded. It seems so obvious now you mention it but just going by the crawler day in day out my brain was making the assumption that all the data would be there.
