### ISSUE TITLE
GPL-nnn Control location should be completely random

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#2955]
As R&D (Louise/Naomi) we would like to see complete randomness when choosing controls location

At the moment the -ve controls are never picked into col 1-8 or 17-14 of 384 plates
The positive controls seem to be  little bit more random but always gathered together on a 384 plate.

Relates to https://rt.sanger.ac.uk/Ticket/Display.html?id=704743
Louise Aigrain
Naomi Park
Lesley Shirley

Naomi and I noticed that the location of the Heron negative controls is always between columns 9 and 16 of our 384 plates.
We know that originally some wells were avoided on purpose in order to not end up where the QC standard would be. However as far as I understand the process, it shouldn’t prevent the controls to be randomly picked towards the right or left third of a plate (it that correct?). Do you know why the negative controls are never picked into col 1-8 or 17-14?Beside the new tail process doesn’t require any cDNA quant QC so the constrains on avoiding standard well locations could be lifted to allow complete randomness when choosing controls location. 
Would it be possible put that in place? Is that a big job?
The positive controls seem to be  little bit more random but always gathered together on a 394 plate. Again they could be picked completely randomly like the negative controls now that there isn’t any cDNA QC.

**Comment by JamesGlover** [comment]
Duplicate issue: https://github.com/sanger/sequencescape/issues/2967
