### ISSUE TITLE
GPL-755	Beckman destination plate barcode is foreign

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2962]
**User story**
As a dev team we need to make Beckman destination plate barcode native.

**Who are the primary contacts for this story**
Steve I

**Acceptance criteria**
Place holder to capture requirement so is not lost.

To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Raised in rambling discussion on 25th Nov

**Comment by JamesGlover** [comment]
Barcodes generated in lighthouse UI via baracoda in format HT-n+ 
Might need to extend @emrojo plate creation to use this format as well.

**Comment by JamesGlover** [comment]
Nope, @emrojo uses the standard barcode detection methods, so just need to add the format to the foreign barcodes array.
