### ISSUE TITLE
GPL-762 Add link to label_printer in SS

### ISSUE THREAD

**Issue by emrojo** [sanger/sequencescape#2966]
**User story**
As a developer I would like to have label_printer linked inside SS so we can print labels for testing environments.

There is a JS app https://github.com/sanger/label_printer that provides some useful functionality for testing, like printing labels where you specify the contents it needs to have.  This app is using an old url and is not in current deployment project.

**Who are the primary contacts for this story**
James Glover, Eduardo Martin

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] label_printer is deployed inside the psd-deployment project
- [ ] there is a link in SS to the label_printer app

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by emrojo** [comment]
**Adittional Context**
From @JamesGlover comment: Current app makes the assumption we have pmb routed on the same host (and presumably port) at /pmb

**Comment by JamesGlover** [comment]
External application links can be configured via the:
configatron.external_applications array in `config/config.rb` this file is templated out in psd-deployment:
`roles/deploy_sequencescape/templates/production/config.rb.j2`

**Comment by JamesGlover** [comment]
The app doesn't support the newer SPrint printers
