### ISSUE TITLE
BUG - destination plate creation events don't include user identifier

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#2983]
**Describe the bug**
lh_beckman_cp_destination_created events, coming through from the Beckman cherrypicking method -> Lighthouse 'cherrypicked-plates/create' endpoint -> SS Heron plate API endpoint, do not include a user identifier when they reach the warehouse.

- Problem is in BroadcastEvent model in SS, in method `def user_identifier`, where it uses the user_id - it doesn't look in properties for a user_identifier at all
- Could change it here or maybe in the subclass BroadcastEvent::PlateCherrypicked

**To Reproduce**
- See event in mlwhd_mlwh_events_proddata with id 1979969 - user_identifier is 'UNKNOWN'
- See BroadcastEvent in sequencescape_staging with id 443161 - includes user_identifier in properties field, but user_id is blank
- If you generate the message that would have gone to the warehouse between these two, the user_identifier is UNKNOWN, therefore the problem is SS side
    - In UAT rails console, do `be = BroadcastEvent.find(443161)`, followed by `MultiJson.dump(be)` - notice user_identifier is UNKNOWN in the resulting json

**Comment by JamesGlover** [comment]
I'd suggest the subclass, we do something similar in BroadcastEvent::AssetAudit

**Comment by JamesGlover** [comment]
There we also see if we can lookup the user in SS when we first create the broadcast event:
```BroadcastEvent::AssetAudit.create!(seed: self, user: User.find_by(login: created_by), created_at: created_at)```

**Comment by KatyTaylor** [comment]
Testing in UAT:

Found destination plate used in previous test run - HT-111162
Find BroadcastEvent associated with this - id 443156
Rebroadcast with `BroadcastEvent.find(443156).queue_for_broadcast`
Check in UAT events warehouse for messages - 108 appeared, and they have 'user_identifier' field filled in ✅
