### ISSUE TITLE
GPL-821 Sequencescape displays a 500 error whilst finding descendants

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3018]
When going to some stock plate pages Sequencescape displays a 500 error whilst finding descendants

NB The plates that appear affected are DD MAIN plates circa 2013/14
https://rt.sanger.ac.uk/Ticket/Display.html?id=709700

http://sequencescape.psd.sanger.ac.uk/labware/7549288 => 'We're sorry, but something went wrong.'

Exception captured:
An ActionView::Template::Error occurred in labware#show:

  undefined method `label' for nil:NilClass
  app/views/labware/_relations.html.erb:42:in `block in _app_views_labware__relations_html_erb___4378959894098921918_406960'

<% asset.links_as_ancestor.indirect.includes(:descendant).find_each do |link| %>
          <tr>
            <td><%= link_to "#{link.descendant.label&.titleize}: #{link.descendant.display_name}", labware_path(link.descendant) %></td>
            <td>Descendant</td>
          </tr>
        <% end %>

**example link instance is**
#<AssetLink id: 13124697, ancestor_id: 7549288, descendant_id: 9169880, direct: false, count: 1, created_at: "2014-01-14 16:04:39", updated_at: "2014-01-14 16:04:39">

**Calling descendant on this returns nil YET the well (9169880) exists**
w = Well.find 9169880
=> #<Well id: 9169880, sti_type: "Well", qc_state: nil, resource: nil, map_id: 1, closed: false, external_release: nil, volume: nil, concentration: nil, labware_id: 9169879, created_at: "2014-01-14 16:04:35", updated_at: "2014-01-14 16:04:35", pcr_cycles: nil, submit_for_sequencing: nil, sub_pool: nil, coverage: nil, diluent_volume: nil>
w.plate
=> #<Plate id: 9169879, name: "Plate 319135", sti_type: "Plate", size: 96, public_name: nil, two_dimensional_barcode: nil, plate_purpose_id: 111, labware_type_id: nil, created_at: "2014-01-14 16:04:35", updated_at: "2014-01-14 16:04:35">
w.plate.purpose
=> #<Pulldown::InitialPlatePurpose id: 111, name: "ISC Covaris", created_at: "2011-08-05 17:22:51", updated_at: "2018-05-29 11:32:27", type: "Pulldown::InitialPlatePurpose", target_type: "Plate", stock_plate: false, default_state: "pending", barcode_printer_type_id: 2, cherrypickable_target: false, cherrypick_direction: "column", size: 96, asset_shape_id: 1, source_purpose_id: 110, lifespan: nil, barcode_prefix_id: 1>

**Comment by JamesGlover** [comment]
This is probably a data repair job. A quick naieve test on training for the example plate alone though reveals:
1) destroy throws an exception
2) delete is taking an age for some reason

**Comment by JamesGlover** [comment]
It *does* fix the problem though:
```AssetLink.includes(:descendant).where(labware: { id: nil}, ancestor_id:7549288).delete_all```

You *could* remove the ancestor_id bit and repair everything. Will probably need to do the inverse as well.

Asset links are warehoused though, so ideally we'd be ensuring callbacks fired.
