### ISSUE TITLE
GPL-822 Prevent relevant transfers from progressing when a submission is cancelled

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3019]
**User story**
As a Limber user, I would like to be prevented from progressing plates if the submission associated with them has been cancelled, so that I don't have to raise a ticket with PSD when I am blocked later down the line.

**Who are the primary contacts for this story**
Katy, James G

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When a Submission is cancelled in Sequencescape, all associated Transfer Requests are also cancelled.
- [ ] If there were any Transfer Requests, there is feedback to the user telling them so, and informing them that some work may have been disrupted because of it. (it's basically an indicator that some work had already been started on the submission that you are cancelling)

**Additional context**
This came out of this RT - https://rt.sanger.ac.uk/SelfService/Display.html?id=709924
The following sequence of events happened:
1. RT plate created
2. Submission 1 made
3. Submission 1 cancelled
4. Submission 2 made
5. PCR 1 plate made
6. PCR 2 plate made
7. Submission 2 cancelled 
8. Submission 3 made 
9. **Plates are further progressed & all link to second one**
10. Ticket raised - Charge and pass libraries button doesn’t appear due to submission being cancelled

This will prevent step 9 from being possible. The relevant page in Limber will look like this:
![Screenshot 2021-01-19 at 16 21 26](https://user-images.githubusercontent.com/10407809/105063627-d7037900-5a73-11eb-920d-01fdba2e4cc7.png)

There is a related story in Limber - https://github.com/sanger/limber/issues/606

**Comment by JamesGlover** [comment]
Background:
1) We usually block submissions from being cancelled once the requests within are started
2) However, requests don't get started until the first plate on the process is started (usually by running on a robot)
3) The transfer requests however get created prior to this, and associate the plate with the original submission.

This results in a small window in which a new submission is made, but it is not immediately apparent to the user than this is the case. Instead there appears to be an assumption that the older plate will be associated with the newer submission.

While it is tempting to update the plates to be tied to the new submission, I think this unwise, as there are to many potential things to go wrong.

**Comment by Skrich1999** [comment]
I don’t think it’s been implemented as far as I know, although I think some of the improvements we’ve made around Limber failures & cancellations probably mean the issue is less likely to arise.

Since it’s been sitting in the backlog for a year and hasn’t come up again, I think it’s safe to get rid of it, whether that’s by removing it from the project or archiving / deleting it.
