### ISSUE TITLE
GPL-847 Eagle changes

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#3034]
**User story**
From 10am ad hoc meeting

**Who are the primary contacts for this story**
James G
Katy T

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Generate COG-UK ids for UAT
- [x] Generate 18 x 93 Cog-UK ids for PROD (first runs today)
- [x] Add Eagle Barcode format UAT & PROD + Tests + array of acceptable formats (Roll in with Randox change)
- [x] LTRH plate creator UAT + PROD + Training (do from console)

**Tidy up**

- Automatic COG-UK ids creation
- Revisit Plate creator 
- Does it matter that these samples are also in the SFTP (need to check this statement is true first)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by rl15** [comment]
![Screenshot 2021-02-02 at 12 15 13](https://user-images.githubusercontent.com/7222395/106598991-64ed6280-6550-11eb-88ae-5d4e79f4953a.png)

**Comment by JamesGlover** [comment]
Added creators with: 
```ruby
Plate::Creator.create!(name: 'LTHR Cherrypick', plate_purposes: Purpose.where(name:'LTHR Cherrypick'), valid_options: { valid_dilution_factors: [1.0]})
```

**Comment by JamesGlover** [comment]
**Automatic COG-UK ids creation**
- New column type, maps to sample supplier name, but auto-populated with COG-UK ids on manifest generation (via baracoda)
- Replace existing supplier name column in heron manifest type with the new column

**Comment by JamesGlover** [comment]
**Revisit Plate creator**

- Plate purposes in the record loader can request a plate creator
- However limber plates are created via the API, as they 'belong' to limber
- We could allow the API to trigger the creation of a plate creator, but my gut it this is an implimentation detail, and shouldn't be exposed.
- Instead we're probably better migrating all the existing plate creators into an independent record loader
- If the record loaded can't find the plate purpose for a given creator it should warn, and skip that record. That way we don't get into a circular dependency with limber purposes.

**Comment by rl15** [comment]
James Make wrote: (Tuesday, 2 February 2021 at 13:08)
If the duplicates are given the go ahead we will need 18 * 93 COG UK IDs.

**Comment by KatyTaylor** [comment]
Sequencescape should now be able to accept eagle barcodes

**Comment by KatyTaylor** [comment]
Ticked off the COG UK barcodes as Eduardo just did them
