### ISSUE TITLE
GPL-884 Get COG UK ids in manifest creation for Eagle [Heron] [4]

### ISSUE THREAD

**Issue by emrojo** [sanger/sequencescape#3043]
**User story**

As a developer I want to automatically retrieve the COG UK ids of the samples created on manifest creation for samples for Heron projects so this action is similar to how it happens currently with Lighthouse.

**Who are the primary contacts for this story**
James Mack
Eduardo Martin

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Uploading a manifest will obtain a COG UK id for each sample created. 
- [ ] As possible, only existing samples will get a COG uk id (minimise the number of ids not in use)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Related with ticket RT 711416

**Comment by rl15** [comment]
Agreed with Alan Keith can be deprecated - see email Rich L Subject INFO: PAM Backlog refinement decisions make
