### ISSUE TITLE
GPL-932 Refine the way comments are displayed in the inboxes (C=M, V=3)

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3107]
**User story**
Comments in the inboxes suffer from a few UX issues:
1) They are confined to the table cell, so get a bit squashed together. It would be really cool if they could span the whole width of the table (but still not overlap rows beneath)
2) If the same comment is displayed multiple times, there is unnecessary duplication. We should be careful of just calling `.uniq`, as the comments displayed should match up with the comment counts. (Not to mention the comments on other pages). Id suggest adding a little badge `<%= badge("#{count} times") %> to duplicate entries. See https://github.com/sanger/sequencescape/issues/3166

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
Duplicated in: https://github.com/sanger/sequencescape/issues/3166

**Comment by JamesGlover** [comment]
See: https://datatables.net/extensions/responsive/ for a potential way to handle comment display. We'll still need to ensure we show a comment count though, and probably still makes sense to compact duplicate comments.

**Comment by stevieing** [comment]
The displayed comments are showing duplicates, at times this slows down the pipeline inbox users as they have to read all the displayed comments.
Example in RT ticket
https://rt.sanger.ac.uk/Ticket/Display.html?id=717970

Primary contacts
Lynda D
Tris

Looking at the NovaSeq inbox http://sequencescape.psd.sanger.ac.uk/pipelines/51
The comments displayed are mapped to request but also include labware comments.

Perhaps just apply uniq to the comment descriptions?

**Comment by stevieing** [comment]
The problem is that there are multiple identical comments. If we do a uniq on them, then we have to also do that when fetching the counts, which will impact on inbox speed. Also, its then unclear what we should show when a person clicks through, as:

    Comments link to the thing they are associated with, do we just display one of them, or have the comment counts differ when you click through?
    What happens if you try to delete one of these comments, how do we know which one to delete?

More details in existing issue:
