### ISSUE TITLE
GPL-919 BUG - verify tube layout missing

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3108]
The link to /batches/12345/verify has 'disappeared' from the batch view sidebar

https://rt.sanger.ac.uk/Ticket/Display.html?id=714533

![Screen Shot 2021-03-10 at 13 50 15](https://user-images.githubusercontent.com/299768/110639550-c041ee80-81a7-11eb-9823-e869105c516e.png)
![Screen Shot 2021-03-10 at 13 50 51](https://user-images.githubusercontent.com/299768/110639567-c46e0c00-81a7-11eb-87d9-886f8d7b0b4a.png)

Although the lab can work around this, Tris B says..
"be nice to get fixed fairly quickly though as today a member of staff missed this section and it now means the tubes weren't verified is S/S which is one of our systems for checking."

**Comment by JamesGlover** [comment]
Whoops, another permissions mistake. Fix incomming
