### ISSUE TITLE
GPL-916-1 Add Sequencescape sample_metadata fields to MLWH sample table

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3109]
See sibling issue here - https://github.com/sanger/unified_warehouse/issues/212

DTOL (Shane M) raised via https://rt.sanger.ac.uk/Ticket/Display.html?id=713449 that the "organism part" field in sample_metadata table 
was missing in the mlwh sample table

It is considered that rather than adding requested columns ad hoc that all missing columns should be added.
Attached is a comparison of the fields in each table with TO ADD marked against those that are absent.
[missing_mlwh_sample_fields.xlsx](https://github.com/sanger/crawler/files/6116727/missing_mlwh_sample_fields.xlsx)

Naming new fields:

Note some field names compare across tables (ss => mlwh)
eg cohort => cohort
whilst some differ
sample_public_name => public_name
some not so obvious
sample_strain_att => strain
and some just outright left field
sample_sra_hold => sample_visibility

The 'sample_' prefix naming convention in the sample_metadata table is a legacy that does not persist in the mlwh (apart it would seem for sample_visibility!). It would be good to not replicate sample_ 

NB
Look at the sample_reference_genome_old field.
I added reference_genome_id way back (when I still had all my teeth) to reference the new table (before Ref genome names were hard coded in) and sample_reference_genome_old was supposed to be removed (never happened)

**Comment by neilsycamore** [comment]
The request owner has just come back with "No need to get this added to mlwh. I'll find a work around."

**Comment by JamesGlover** [comment]
Going to suggest that `concentration` goes in as `customer_supplied_concentration` to avoid confusion with measured concentrations.

**Comment by JamesGlover** [comment]
We should also avoid any _id fields if the corresponding record is not in the WH. So user_id_of_consent_withdrawn for example should be consent_withdrawn_by and then the user login

**Comment by JamesGlover** [comment]
Note that donor_id is distinct from the above in that it doesn't reference a donors table.

**Comment by KatyTaylor** [comment]
What's the story of supplier_plate_id?
If I do the following on the training db, I get 0 rows:
```
SELECT supplier_plate_id
FROM sample_metadata
WHERE supplier_plate_id IS NOT NULL
  AND supplier_plate_id != ''
LIMIT 100
```

**Comment by KatyTaylor** [comment]
Went down a bit of a rabbit hole with the `rnai` field, to find a representative value for a test. Ended up with this where clause:
```
WHERE rnai IS NOT NULL
  AND rnai != 'N/A'
  AND rnai != 'NA'
  AND rnai != 'None'
  AND rnai != 'Not applicable'
  AND rnai != 'Null'
  AND rnai != 'Not specified'
```
and it returned 0 rows

**Comment by KatyTaylor** [comment]
`genome_size`, `saphyr` and `pacbio` are also all null, but I think that's because they are relatively new fields, created for Traction, and haven't been used yet

**Comment by KatyTaylor** [comment]
About sample_reference_genome_old:

There are 49 rows that have data in sample_reference_genome_old:
```
SELECT sample_reference_genome_old
     , reference_genome_id, rg.name AS 'reference_genome_new'
     , sm.created_at AS 'sample_created_at'
FROM sample_metadata sm
JOIN reference_genomes rg on rg.id = sm.reference_genome_id
WHERE sample_reference_genome_old IS NOT NULL
  AND sample_reference_genome_old != ''
ORDER by sm.created_at DESC
```

Of which, 5 don't quite match on the name of the reference genome:
```
SELECT sample_reference_genome_old
     , reference_genome_id, rg.name AS 'reference_genome_new'
     , sm.created_at AS 'sample_created_at'
FROM sample_metadata sm
JOIN reference_genomes rg on rg.id = sm.reference_genome_id
WHERE sample_reference_genome_old IS NOT NULL
  AND sample_reference_genome_old != ''
  AND sample_reference_genome_old != rg.name
ORDER by sm.created_at DESC
```

**Comment by JamesGlover** [comment]
> About sample_reference_genome_old ...

I think this is just left over from before the database migration to a separate reference genomes table. Should be safe to just ignore this entirely (And probably drop the column as well)

**Comment by JamesGlover** [comment]
> What's the story of supplier_plate_id?
> If I do the following on the training db, I get 0 rows:

Not sure, it was added before the migration to github 10 years ago, and isn't exposed in the current manifests. It is exposed on the sample edit/show pages, but given its never been used suggest we don't add it, and remove it from:
`app/views/shared/metadata/edit/_sample.html.erb` and `app/views/shared/metadata/show/_sample.html.erb`
To stop anyone from using it soon. Could drop the column and remove the attribute as well if you have time,

**Comment by JamesGlover** [comment]
> Went down a bit of a rabbit hole with the rnai field

This one is a little less clear cut. It seems to be associated with Array Express studies (I'm assuming it references RNAi interference), but I'm not sure if Array Express integration is even still a thing. (There was apparently a weird API added to the ENA that would pipe some data across for Sanger only. The API pre-dated me, so don't really know the details, but I recall someone telling me it had been removed)

I'm not quite sure what to suggest. We've still got hooks to update this field in the manifests, so its not quite as defunct as the supplier plate id column, even if no one is using it.

Maybe we hold off on adding this one for now, and add a story to strip it out from SS shortly, assuming no one starts to use it in the meantime?

**Comment by JamesGlover** [comment]
> `genome_size`, `saphyr` and `pacbio` are also all null, but I think that's because they are relatively new fields, created for Traction, and haven't been used yet

Yep, these were added for traction. Might be work checking with Steve if they are still needed, as there was quite a bit of back and forth of traction requirements specification. `saphyr` and `pacbio` were always a bit of a hack as the customer explicitly didn't want to create a submission, but still needed to specify the work they wanted done. However I think there was an alternative solution for this in the end, so those columns might not be needed.
