### ISSUE TITLE
GPL-915 Update 'Root Sample ID' in data stores

### ISSUE THREAD

**Issue by pjvv** [sanger/sequencescape#3123]
**User story**
Milton Keynes performed an investigation on their manual cherry picking and detected that 317 samples had the wrong root sample Id shared with us. They came up with a list of corrected samples IDs, which is attached.

RT: /Ticket/Display.html?id=713901

**Who are the primary contacts for this story**
Cristina A

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] work out why querying Sequencescape `sample_metadata` based on root sample id / description gives 326 rows (rather than 317 (@KatyTaylor)
- [ ] ~create an update script to update mongo~ - not needed as Sonia advised it was only manually (manifest) uploaded samples that were incorrect
- [ ] ~create an update script to update MLWH (@pjvv)~ - not needed as Sonia advised it was only manually (manifest) uploaded samples that were incorrect
- [x] create script in SS rails console to update root sample id for all 317-ish (will also propagate to MLWH sample table)
- [ ] ~create script to update Events WH for the incorrect events ?? (Beckman-fired events will include the root sample id in `subject_friendly_name`)~ - not needed as Sonia advised it was only manually (manifest) uploaded samples that were incorrect

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by KatyTaylor** [comment]
Script and log of when run here - https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Root+Sample+Id+fix+March+2021
