### ISSUE TITLE
GPL-949 Add Sequencescape study_metadata fields to MLWH study table (C=S, V=?)

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3129]
For consistency of reporting fields in sequencescape.study_metadata should also be present in mlwh.study table

**Comment by KatyTaylor** [comment]
@neilsycamore do you know if this one is still relevant? Thanks

**Comment by neilsycamore** [comment]
@KatyTaylor  this initially came from CASM who have since said that they would find a work around

**Comment by stevieing** [comment]
OK. I am going to remove this from the triage column but leave open for now.
