### ISSUE TITLE
GPL-982 BUG - Cherrypick layout page creates control requests on render, not perform

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3144]
**Describe the bug**
Control requests are created for the control wells. However these get created when the layout is previewed, which means if the user clicks back, and then tries again, you get multiple control requests. These can be remove manually, but ideally we'd only create the requests when the user clicks next.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate a cherrypickign submission (Eg. UAT actions, Test Submission)
2. Go to the cherrypicking pipeline and batch these up
3. Select a control plate (eg. DN626424)
4. Select pick by ul (to avoid needing concentration info)
5. Click Next step
6. Click back in the browser
7. Click next step again
8. Observe duplicate controls.

**Expected behaviour**
1. Controls should not be duplicated, and ideally request generation should be deferred until after the layout is confirmed. (As the user may have selected the control plate by accident for instance.)

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by KatyTaylor** [comment]
Moving this to UAT column to check if it's still an issue
