### ISSUE TITLE
DPL-027 [BUG] Sample edit page adding consent withdrawn metadata

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3203]
When editing a sample date_of_consent_withdrawn and user_id_of_consent_withdrawn is being saved in the sample_metadata.
Note: The consent_withdrawn flag is NOT being set.

This combined with 
https://github.com/sanger/sequencescape/issues/2937
https://github.com/sanger/sequencescape/issues/3104
makes sample editing a conduit for bad data

example id: 4495321, name: “CV001_KM8853544”

When fixed the affected data will require fixing
select count(*) from sample_metadata where date_of_consent_withdrawn is not null and consent_withdrawn = 0
800 records

**Comment by KatyTaylor** [comment]
For data update:
```
samples = Sample.joins(:sample_metadata).where('sample_metadata.consent_withdrawn = 0 AND sample_metadata.date_of_consent_withdrawn IS NOT NULL')

samples.each do |s|
  s.sample_metadata.update!(date_of_consent_withdrawn: nil, user_id_of_consent_withdrawn: nil)
end
```

**Comment by KatyTaylor** [comment]
Spun out data fix into https://github.com/sanger/sequencescape/issues/3213
