### ISSUE TITLE
DPL-038 Research: Understand Saturation Gene Editing (SGE) service

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#3221]
**Description**
Understand;

- [ ] Handover of material and ids from CGAP
- [ ] If new pipeline is required
- [ ] Reporting

**Who the primary contacts are for this work*
David PS (Gene Editing)
Mike Q (R&D)
Charlotte B (CGAP)

**Knowledge or Stake holders**

**Additional context or information**
https://ssg-confluence.internal.sanger.ac.uk/display/SCI/SGE+Hub+Architecture

In June 2021 is in pilot.
Expecting production pipeline end 2021

**Comment by TWJW-SANGER** [comment]
Closing as time has overtaken this.
