### ISSUE TITLE
DPL-038 Reserch Saturation Gene Editing (SGE) [ToR-036?]

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#3222]
**Description**
DPL-038 Understand

- [ ] Handover of physical material and required ids from CGaP to Genomics
- [ ] If require new pipeline in Genomics
- [ ] Reporting?

for new Saturation Gene Editing (SGE) service

**Knowledge or Stake holders**
David PS (Gene editing Informatics)
Charlotte B (CGAP)
Mike Q (R&D)
TBD (Expecting Business Analyst)
TBD (Expecting Project Manager)

**Additional context or information**
This backlog item is to capture brief notes from introduction meeting held on 14th June. 

https://ssg-confluence.internal.sanger.ac.uk/display/SCI/SGE+Hub+Architecture

In pilot June 2021 (Is using walk up service, but not expecting this route for production) 
Expecting production service end of year 2021

Work may be tracked under more than one study to manage data access (May present challenge to bring reporting together at end?)

This is work for Hum Gen and CASM

**Comment by rl15** [comment]
Process flow 

Gene Editing -> CGaP Operations -> Genomics operations -> NPG -> Gene Editing

**Comment by rl15** [comment]
Whats required are process maps to progress this next.

**Comment by TWJW-SANGER** [comment]
Closing as time has overtaken this.
