### ISSUE TITLE
DPL-043 Manifest upload causing duplications in EGA 

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3228]
When manifests are uploaded duplicate entries are being made in the EGA database (nearly always)

Example manifest (non sensitive data generated for testing)
[2405stdy_manifest_17293_170621.xlsx](https://github.com/sanger/sequencescape/files/6669512/2405stdy_manifest_17293_170621.xlsx)
Duplicate entries (scraped from the EGA Webin page (https://www.ebi.ac.uk/ena/submit/sra/#home)
[repeat_EGA_entries.xlsx](https://github.com/sanger/sequencescape/files/6669514/repeat_EGA_entries.xlsx)

When 2405STDY10409901 is viewed in sequencescape_warehouse.samples ('old' warehouse) there are two accession entries EGAN00003219314 and then EGAN00003219315, both with the same timestamps.

James G's comments (from Slack 17/06/21)
"Suspect we’re creating and then updating samples, and generating an accession job for each action. I’m not quite sure why both accessions are succeeding and returning different number though, I’m assuming the EBI have a similar race condition

**Comment by neilsycamore** [comment]
When we try to update them via Sequencescape EBI doesn’t know which one to update so returns “More than one object found with alias”

**Comment by JamesGlover** [comment]
So pretty sure the problem is multiple delayed jobs, but weirdly on upload i'm not actually seeing any generated in dev after supposedly enabling the feature. Reason being that studies isn't populated on sample, so they are flagged as invalid. Can't see why this would be different in production...

**Comment by JamesGlover** [comment]
Hmm, and looking at the code, I don't *think* the delayed jobs for accessionables is fetching the sample from the database, but is using the serialized copy in the job itself. This isn't ideal, as we're dependent on job order for ensuring the EGA version is the latest.

**Comment by JamesGlover** [comment]
Hmm, so seeing dupe delayed jobs happening on sample update in prod. Doesn't mean that there aren't ones on create, just looking at what I've found.

**Comment by JamesGlover** [comment]
Checking with Neil the plausibility. Neil's manifest example appears to have shown accession updating on creation, but was uploaded before the recent manifest changes, so perhaps the bug got introduced then.

**Comment by JamesGlover** [comment]
Checking out the version prior to recent changes to see if studies are loaded on the samples correctly. It should be an easy fix, but a bit confused why its not been noticed.

**Comment by JamesGlover** [comment]
Hmm, issue still exists before then...

**Comment by JamesGlover** [comment]
Ooohh, barking up wrong tree! We're reloading from database, so my studies were invalid for some other reason. Okay. Can work with this now.
