### ISSUE TITLE
DPL-084 [BUG] SS study users not updating to MLWH.study_users

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3245]
mlwh.study_users is used to determine who to inform that the sequenced data is available.

Adding owners etc to studies via the SS interfaces 
- Admin => users (eg bs16) => added as owner
- Study page => contacts => added as owner
records them in SS but the mlwh.study_users table only shows one record for each role.. so it doesn’t display 2 owners say.
In fact if you add a new owner the previous owner is removed from the mlwh
AND
If a study has 2 followers and another is added the 2 previous ones are not displayed.
Have tried adding roles manually but still get the same issue
Example study is 6498 (id_study_tmp 6326)

Relates to https://rt.sanger.ac.uk/Ticket/Display.html?id=725064

**Comment by JamesGlover** [comment]
Bug appears to be in message generation. Calling:
Api::StudyIO.to_hash(Study.find(6498))
Shows only one follower, whereas:

```
irb(main):003:0> Study.find(6498).followers.length
=> 2
Study.find(6498).roles.map(&:name)
=> ["manager", "owner", "owner", "owner", "follower", "follower"]
```

So it looks like we have multiple roles with the same name, then when we generate the message we do:

https://github.com/sanger/sequencescape/blob/765fd38b79385a85e82927e7e914b3329d5b67f6/app/models/api/study_io.rb#L48-L56

So blow away shared role names.

- We probably shouldn't generate duplicate roles if we can avoid it. This is a problem with:
https://github.com/sanger/sequencescape/blob/765fd38b79385a85e82927e7e914b3329d5b67f6/app/models/role/user_role_helper.rb#L18-L22
While it looks like we're doing a find_or_create this is scoped to roles already associated with the user.
- We should either:
  - Handle duplicate role names where they do occur
  - Squish down duplicates (Being careful not to remove roles) and add database constraints to prevent the bug from occuring again.

**Comment by JamesGlover** [comment]
We can handle the data clean up and constraints once this is live.
