### ISSUE TITLE
DPL-053 [BUG] tag substitutions made by manifest or via substitution page are not being updated in MLWH

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3248]
As title "tag substitutions made by manifest or via substitution page are not being updated in MLWH"

Requires manual intervention via rails console

**Comment by JamesGlover** [comment]
Hmm, thought I had another story in for this with the details...

**Comment by JamesGlover** [comment]
Hmm, can't find where I'd discussed the issues. May have been on slack?

**Comment by JamesGlover** [comment]
Tests work, but its not entirely surprising, as expected cause is related to transactions.

**Comment by JamesGlover** [comment]
Background:
- Prior to warren, batches used to trigger rebroadcast of the messenger on save
- However if the transaction later failed, this would result in an invalid message
- So the callback was moved to after-commit

However, this worked by adding the messenger to the transaction, something which was occurring after the transaction callbacks were fired, so the message never got sent.

Fix is actually simpler than I assumed, we're already in an after commit callback, so the transaction is nice and safe. We just need to send the message manually, rather then trying to deal with the transactions.

**Comment by JamesGlover** [comment]
Doh, tests were detecting the issue, I just forgot to expect the message from my factories
