### ISSUE TITLE
DPL-057 OKR: Provide function to allow DNA team users to edit and add batch loading events

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3250]
In the process of loading flowcells most details (events) are manually entered.
Some are for 'in team' tracking e.g. Operator, Pipette Carousel, PhiX lot
whilst others are required for downstream analysis e.g. phix barcode, loading concentration, workflow

Presently once the batch is released these events cannot be updated by the team and require the generation of an RT ticket to update the event(s). There is potential for downstream analysis to be delayed.

The number of RT tickets generated for this action is consistently the highest in any month than any other area we support.

**Comment by JamesGlover** [comment]
Merging with: https://github.com/sanger/sequencescape/issues/3225
