### ISSUE TITLE
DPL-091 associate PhiX with a study (Heron PhiX) to prevent data access

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3268]
Currently all the phiX data goes in study 198 (Pending https://github.com/sanger/sequencescape/issues/3255) which can be accessed by anybody in irods.
Due to index hopping we are concerned that some heron data could end up in the phiX reads and could thus be accessible to anybody.
Therefore to prevent this from happening we would like to send all the phiX data into Heron PhiX. We can then make sure that access in irods is restricted.

**Who are the primary contacts for this story**
Naomi P
Stef L
Carol S (NPG)

**Comment by JamesGlover** [comment]
Concerns:
- PhiX is currently linked to a study at the tube level. This would need to be selected when registering either Spiked PhiX Buffer, or the PhiX stock. http://sequencescape.psd.sanger.ac.uk/phi_x
- However there would be nothing to stop someone mixing up tubes of PhiX, and either using Heron registered Phix in Non heron studies, or vice-versa
- There's also scope for error when the tubes are registered, even if usage is tightly governed
- The study would also need to be know upfront when the PhiX was registered
- This only addresses the issue for Heron, whereas there are lots of other studies requiring restricted data access.
