### ISSUE TITLE
DPL-081-1 Add new control plate, update Cherrytrack

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3272]
As R&D we would like to change the location of Heron cherrypicking controls on the Biosero system to enable the transition to strip tubes and automated control preparation.

Acceptance Criteria:
  *   A new control plate should be registered in Sequencescape (same behaviour as DN626424D) with a positive control in D1 and a negative control in A1

Coupled with https://github.com/sanger/cherrytrack/issues/20

[RT ticket](https://rt.sanger.ac.uk/Ticket/Display.html?id=727296)

Contacts
Scott T

**Comment by JamesGlover** [comment]
When registering control plates in Sequencescape we should ensure that the same barcode is used in UAT as in production to reduce confusion. The counter is shared between the two environments, so no risk of clashes.

Might be worth assigning more sensible names to the control plates as well, current names include the barcodes, whereas we're already doing:

```ruby
ControlPlate.all.collect {|p| [ "#{p.human_barcode} - #{p.name}", p.id ] 
```

When generating the drop-down in sequencescape, so the current names 'Plate DN626424D' is redundant, and not very informative.

**Comment by JamesGlover** [comment]
Sent question on RT:

> Hello all,
> 
> The current control plate is named 'Plate DN626424D' and gets shown in the cherrypicking pipeline as:
> 'DN626424D - Plate DN626424D'
> 
> Which feels a little redundant.
> 
> I propose renaming this control plate to:
> Heron Control A1+ H12-
> 
> And naming the new plate:
> Heron Control D1+ A1-
> 
> These would then be displayed in the dropdown as:
> 'DN626424D - Heron Control A1+ H12-'
> 'DN??????X - Heron Control D1+ A1-'
>

**Comment by harrietc52** [comment]
From Biosero Technical meeting on 30th July - Update Cherrytrack config once SATs have finished. We will need to coordinate the change in config with Biosero (Rob/ Scott?)

**Comment by sdjmchattie** [comment]
These are the Rails Console commands I plan to use to rename the previous control plate and to create the new one.  The barcode would need to be valid in both UAT and production.  I've obscured the names of the samples in the script in case of not wanting to reveal those here:

# Rename the existing plate
old_plate = ControlPlate.find_by_barcode('DN626424D')
old_plate.update(name: 'Heron Control A1+ H12-')

# Create new plate
barcode = PlateBarcode.create!()
purpose = PlatePurpose.find_by_name('Stock Plate')
plate = ControlPlate.create_with_barcode!(sanger_barcode: { number: barcode.barcode, prefix: 'DN' }, plate_purpose: purpose, name: 'Heron Control D1+ A1-')

# Create wells for the new plate
maps = Map.for_plate(plate)
wells = maps.map do |map|
  Well.create!(plate: plate, map: map)
end

# Find the Heron study
study = Studies.find_by_name('Heron Project')

# Put a huge aliquot of the positive sample in well D1
pos_sample = Sample.find_by_name('Pos_sample_name')
pos_well = wells.find{ |well| well.map.description == 'D1' }
pos_aliquot = Aliquot.create!(study: study, receptacle: pos_well, sample: pos_sample, suboptimal: true)
pos_well.well_attribute.update(initial_volume: 100000000, measured_volume: 100000000, current_volume: 100000000)

# Put a huge aliquot of the negative sample in well A1
neg_sample = Sample.find_by_name('Neg_sample_name')
neg_well = wells.find{ |well| well.map.description == 'A1' }
neg_aliquot = Aliquot.create!(study: study, receptacle: neg_well, sample: neg_sample, suboptimal: true)
neg_well.well_attribute.update(initial_volume: 100000000, measured_volume: 100000000, current_volume: 100000000)

**Comment by JamesGlover** [comment]
Responses from Scott T:

> Hi James, 

> 
> This seems to be a logical and beneficial change. 
> 
> Would it be possible to change the Lighthouse UI to have a similar drop-down as you suggest here?
> Currently it is a free text box to allow for future functionality (GPL-736) but this is not needed until control batch tracking is implemented which may be some time away. 
> 
> Thanks, 
> Scott. 

The lighthouse changes would be another story, would probably be non-trivial as would need to add pulling of the control plates back from SS.

**Comment by JamesGlover** [comment]
And more info on the RT:

> Hi, 
> 
> Is it possible to use the config key 'bv_barcode_prefix' in the cherrytrack to specify 'DN??????X' instead of just 'DN'. 
> 
> If we have to operate the old control process on the Beckmans at the same time as the new process on the Bioseros, then this would help prevent mix-ups. 
> Beckman have not yet responded about the Apps time involved, so we are expecting to have to support two processes for a few weeks. 
> 
> Thanks, 
> Scott. 

@harrietc52 may be able to add more to this requirement.

**Comment by JamesGlover** [comment]
Code review:
`barcode = PlateBarcode.create!()` will have to be performed upfront to 'book' the barcode, rather than repeated on both environments, this will let the same barcode be used in each. (Mostly to reduce confusion) They share a counter, so it doesn't matter which gets used.

```
# Create wells for the new plate
maps = Map.for_plate(plate)
wells = maps.map do |map|
  Well.create!(plate: plate, map: map)
end
```
Can just become `plate.wells.construct!`

**Comment by sdjmchattie** [comment]
Thanks for the feedback @JamesGlover .  I will be sure to do the barcode as a separate step.  I've updated the well creation so now I have this:

```
# Rename the existing plate
old_plate = ControlPlate.find_by_barcode('DN626424D')
old_plate.update(name: 'Heron Control A1+ H12-')

# Create new plate
barcode = PlateBarcode.create!()
purpose = PlatePurpose.find_by_name('Stock Plate')
plate = ControlPlate.create_with_barcode!(sanger_barcode: { number: barcode.barcode, prefix: 'DN' }, plate_purpose: purpose, name: 'Heron Control D1+ A1-')
plate.wells.construct!()

# Find the Heron study
study = Studies.find_by_name('Heron Project')

# Put a huge aliquot of the positive sample in well D1
pos_sample = Sample.find_by_name('pos_sample_name')
pos_map = plate.maps.find_by_description('D1')
pos_well = Well.find_by(plate: plate, map: pos_map)
pos_aliquot = Aliquot.create!(study: study, receptacle: pos_well, sample: pos_sample, suboptimal: true)
pos_well.well_attribute.update(initial_volume: 100000000, measured_volume: 100000000, current_volume: 100000000)

# Put a huge aliquot of the negative sample in well A1
neg_sample = Sample.find_by_name('neg_sample_name')
neg_map = plate.maps.find_by_description('A1')
neg_well = Well.find_by(plate: plate, map: neg_map)
neg_aliquot = Aliquot.create!(study: study, receptacle: neg_well, sample: neg_sample, suboptimal: true)
neg_well.well_attribute.update(initial_volume: 100000000, measured_volume: 100000000, current_volume: 100000000)
```

**Comment by emrojo** [comment]
> The lighthouse changes would be another story, would probably be non-trivial as would need to add pulling of the control plates back from SS.

Currently this plate in particular is going to be used only with cherrypicking happening inside SS (with Tecan robots); with Beckman the plate cherrypicked has no direct link with the actual well in the control plate; every control sample in a plate is a new control sample created. I think we could keep the same behaviour with Biosero to keep it simple; in Heron we always use the same control plate. 
But yes, in future if they want to start using this for a normal cherrypicking process (not Heron) this would need to change.

**Comment by emrojo** [comment]
I'm thinking now that because of that maybe we could have it done with a manifest upload, and could be delegated to SSR. The previous control plate was created with a manifest by SSRs.

**Comment by sdjmchattie** [comment]
I've applied this to both UAT and production and it looks good.  One minor fault in the commands was that

```
study = Studies.find_by_name('Heron Project')
```

should be:

```
study = Study.find_by_name('Heron Project')
```

The barcode of the new control plate is DN845929S and both now have descriptive names.
