### ISSUE TITLE
DPL-113 LCM DNA & RNA-seq pipeline submission templates / request types [ToR 12]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3282]
**User story**
As an SSR I would like to be able to request work for the LCM DNA & RNA-seq pipelines.

**Difficulties**

The main difficulty here is that the same input can feed into two separate pipelines. Currently we have no way of having a submission template split into two independent paths. In cases where this currently happens, such as GnT, the SSR makes multiple independent submissions.

A further complication is the possible creation of the intermediate 'cherypick?' plate, as this can only be associated with a single request. In the Bespoke Aggregation this is a separate request type, and this plate automatically completes the aggregation when it is passed. A separate submission is then made. However this isn't really suitable in this case, as the cherrypick? plate only exists transitory on the robot, so even though the robot could pass it, it means:

1) There isn't a point at which the SSR could make a submission
2) Even if there was, the DNA Seq/RNA Seq Cherrypick plates are registered before this occurs
3) And even if we generated the requests upfront in a fancy branching request graph, 2 still causes a pain.

So we'd need to hook in the downstream requests as part of the 'cherrypick?' creator.

If we drop the `cherrypick?` plate it actually becomes easier, as the creator for the two DNA Seq/RNA Seq Cherrypick can pair each plate to the right request type. (We have similar logic already in the front-end for the GBS pipline and primer panel matching), although in this case we're mapping to two child plates... 

**Who are the primary contacts for this story**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Addition of library types to distinguish between RNA and DNA pipelines
- [ ] (Possible) Addition of one or two request types to replace limber_lcmb
- [ ] Ability to create LCMB RNA and RNA requests from submisison templates
- [ ] Generation of LCMB RNA and RNA requests that will be processed by the Limber pipelines

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
closed in favour of #3513
