### ISSUE TITLE
DPL-120 Print plate and tube labels to Squix from SS

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#3292]
**User story**
As representative for SSR (Rich C) we would like to be able to pint plate and tube labels on the new Squix printers from SS as the Toshiba TEC are increasing unreliable.

**Who are the primary contacts for this story**
Rich C (SSR)
Katy T
James G

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Test what happens today when try to pint from SS to one of teh Squi printers (In UAT)
- [ ] List all the templates that are required [Apps and printing templates](https://docs.google.com/spreadsheets/d/14DU8zbAMrk3EEUceUY5pt7m6hLp7343MHsWQuDyq-aU/edit?usp=sharing)
- [ ] Deprecate all the backlog items that mention Squix or barcodes

**Additional context**

**Comment by rl15** [comment]
List of backlog items that mention Squix or barcodes

https://github.com/search?p=2&q=org%3Asanger+squix&type=Issues

Of note 
GPL-906
GPL-831
GPL-832

**Comment by harrietc52** [comment]
LabWhere squix [diagram](https://lucid.app/lucidchart/004c0b67-4273-41dd-bbf6-a545edd53f20/edit?page=0_0#)

**Comment by harrietc52** [comment]
Priority: Tube, Plate 96 (384 not needed yet)

http://sqtest.internal.sanger.ac.uk  (Jamie’s printer) lives in the SSR Pod, Level 2, Ogilvie.
Currently set up for 96 plate labels (can swap out to tube)
But hopefully soon there will be both tube and plate printers available

**Comment by harrietc52** [comment]
Add printers to SS
`   <% printer_list = BarcodePrinter.alphabetical.includes(:barcode_printer_type).all.group_by {|printer| "#{printer.barcode_printer_type.name} (#{printer.active? ? 'Active' : 'Inactive'})" } %>
`

**Comment by harrietc52** [comment]
[Sequencescape printing rationalisation](https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Sequencescape+printing+rationalisation)

**Comment by stevieing** [comment]
Tasks:

- [ ] get sqtest re-added to the ACL
- [ ] test the sqtest printer
- [ ]

**Comment by harrietc52** [comment]
On Deployment

Script for running in SS
```
# Create new BarcodePrinterTypes, with the correct label template names or update existing? 
# sqsc_1dtube_label_template.yml.erb for tube
# sqsc_96plate_label_template_code39_v2.yml.erb for plate_96 

tube = BarcodePrinterType.find_by(name: "1D Tube")
plate_96 = BarcodePrinterType.find_by(name: "96 Well Plate")

# Create two new squix printers
BarcodePrinter.create!(name: 'sqtest', print_service: 'SPrint', barcode_printer_type: tube, active: true)
BarcodePrinter.create!(name: 'sqtest-tube', print_service: 'SPrint', barcode_printer_type: plate_96, active: true)

```

```
Script for running in PMB

# Create two new squix printers
Printer.create(name: "sqtest", protocol: "LPD", printer_type: "squix")
Printer.create(name: "sqtest-tube", protocol: "LPD", printer_type: "squix")

# Steves cloning script to create LabelTemplate/LabelType copies

```

Also redeploy Limber (and all other apps that import the sprint role to get the up to date label templates?)

**Comment by harrietc52** [comment]
Places in SS where there is a `extra_label`
- `SampleManifestPlateDouble`
