### ISSUE TITLE
DPL-122 Import Cardinal samples via manifest

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3312]
**User story**
As a member of the Cardinal team, I want to be able to upload samples / tubes into Sequencescape, so that I can record metadata about them, and continue along the pipeline using the LIMS.

**Who are the primary contacts for this story**
Stef L

**Acceptance criteria**
- Import uses sample manifests
- Samples are created in tubes, of purpose "LCA Blood Tube"
- Sample metadata needed:
  - Identifier of the sample is the tube barcode, which is stored in the sample metadata `sample_supplier_name`
  - Use manifest supplier to track location / Site ID:
    - Stockport: 11025
    - Reading: 11026
    - Newcastle: 11027
    - Bristol: 11028
    - East London Genes and Health: ?
  - Sample volume (volume of blood) (Use existing volume)

**Dependencies**
References
This story has a non-blocking relationship with:
- https://github.com/sanger/limber/issues/755 

**Additional context**

It is expected that the tubes / samples might be imported in a different way in future, for instance a more automated way to save time, or once the BMS system (Bioresource Management System) is up and running. 

This might already be doable using existing tube manifests - this story is to make sure.

JG: Yep, I think almost everything is in place. Will just need a new, super-tiny manifest format and new tube barcode.

There were these original requirements - not included in acceptance criteria due to reasons below:
- Upon receipt of the blood tubes at Sanger the blood tubes will be scanned into the LIMS. The LIMS should collate a list of the scanned-in tubes and send an e-mail to the various sites to confirm receipt of the particular tubes.  (This was agreed to be handled by the BMS - assume it will be manual until this is built / purchased).
- Following the entry of the samples into the LIMS, I need to be able to assign them into a storage location. (Assume this is already covered by LabWhere).

**Comment by JamesGlover** [comment]
# Use of supplier

- Supplier is selected when creating a new manifest
- Supplier belongs to sample manifests
- Supplier appears within the manifest spreadsheet iteslf
- Studies have many suppliers via their manifests, and these are actually linked to via a suppliers link on the study page
- Samples don't currently have_one supplier via sample_manifest
- V1 api exposes suppliers as their own endpoint, and via sample manifest (The suppliers themselves have no relationships)
- New suppliers can be registered via 'pipelines > sample managements > suppliers > create' 
- The last supplier was registered earlier this month, so I'll assume that knowledge exists about how all that works
- From thes pages it is also possible to link to all associated manifests or studies
- Suppliers can be registered by manager, slf_manger and administrator roles
- We expose supplier name as metadata on manifest creation/update events as `supplier name`
- IT would be relatively trivial to convert suppliers to subjects, as they already have uuids.
- Supplier is also exposed in the legacy qc reports (which are apparently still being used...)

However as far as I can tell we do not:
- Expose supplier information alongside sample in the UWH, although it is in the events warehouse
- Expose supplier information alongside the sample in the V1 or V2 apis (The confusingly named supplier_name is the name the supplier has given to the sample)
- Expose supplier information on any sample view page. (Although you can link to the manifest, and see the info there)

**Comment by KatyTaylor** [comment]
Thanks for 'Use of supplier' comment, v useful. Seems like we might need to do number 2 in your list of things we don't yet do, to support this story - https://github.com/sanger/limber/issues/759
And I would assume number 1 to support reporting - I will check this.

**Comment by KatyTaylor** [comment]
Info from Slack regarding 'volume' - 

Katy, Sep 1st:
> will the 'volume' that we need to store be supplied by the sites sending the tubes, or is it something that will be measured in-house by the bioresource team? Thanks

Stef:
> I believe this is internal (bioresource team)

Andrew:
> Measured in mls presumably?

Stef: 
> yes, typicall 2-4ml but it its very low they may enter 0.X (e.g 0.3)

James:
> Ahh, if its measured in house, we might have better methods than manifests. (Which typically record customer supplied volumes)
