### ISSUE TITLE
DPL-125 - As a long read user I would like to be able to select a library type when I create a manifest (C=S, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#3315]
**User story**
As a long read user I would like to be able to select a library type when I create a manifest

**Who are the primary contacts for this story**
Steve

**Acceptance criteria**
To be considered successful the solution must allow the following library types to be selected:
- [ ] Pacbio_HiFi: Standard Pacbio HiFi Library prep - without sample barcoding (without tags)
- [ ] Pacbio_HiFi_mplx: Standard Pacbio HiFi Library prep with Sample barcoding (with tags) - would include low input ToL samples
- [ ] Pacbio_Microbial_mplx: Pacbio pipeline for microbial samples with barcoding..
- [ ] Pacbio_IsoSeq: IsoSeq pipeline without samples being barcoded (without tags)
- [ ] PacBio_IsoSeq_mplx: Isoseq pipeline where samples have been barcoded (with tags) during library prep.
- [ ] Pacbio_CLR: Pacbio Large Fragment library

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
Chasing Liz WRT requirements. DPL-125 (https://github.com/sanger/sequencescape/issues/3314) added a library type column to the manifests themselves, with an appropriately filtered drop-down.

It sounds like this story may be extending that requirement to a dropdown on `sdb/sample_manifests/new` to pre-populate the manifest with a library type. However this is surprisingly tricky, as it couples the form content to the manifest type selected. It also means we need a way of handling the rendering of those forms and the available content. (Or we cheat, and have a few hard-coded divs)

**Comment by JamesGlover** [comment]
Spoke to Liz C, and this dropdown isn't needed outside the manifest itself, so all the requirements here will be covered by DPL-123 https://github.com/sanger/sequencescape/issues/3314
