### ISSUE TITLE
DPL-129 [BUG] updated batch edit page not sending changes to MLWH

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3323]
The updated batch editing page is not sending message to iseq_flowcell table on update

**RT Ticket Number**
e.g. https://rt.sanger.ac.uk/Ticket/Display.html?id=730495
batches 86227/86228

http://sequencescape.psd.sanger.ac.uk/batches/86228

**Comment by JamesGlover** [comment]
HUh, I explicitly wrote tests to check this.

**Comment by JamesGlover** [comment]
Testing in UAT and I'm not seeing the timestamps get updated. Message is broadcast though, just gets discarded because it appears to be the same age as the existing entry.
