### ISSUE TITLE
DPL-133 accept/validate a new format for Brant's Bridge: BB-nnnnnnnn [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#3329]
**User story**
As representative for Lighthouse labs I would like to accept/validate a new format for Brant's Bridge () to avoid the wholly numeric barcodes when pasted into MS Excel being marmalised

**Who are the primary contacts for this story**
Alan K (PAM/GSU)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] SS - Accept barcode format BB-nnnnnnnn (where n = number e.g. BB-12345678) for
- [ ] Crawler and plate maps accept Plate map file names will be the same format e.g. BB-nnnnnnnn.csv

**Additional context**
First raised in bi-weekly GSU-PSU 1pm meeting - and then by RT [Hinxton #731011] New barcode & file name for Brants Bridge (Heron)

**Comment by harrietc52** [comment]
Sequencescape deploy from [releases](https://github.com/sanger/sequencescape/releases) 
Crawler deploy from [packages](https://github.com/sanger/crawler/pkgs/container/crawler%2Fcrawler)
