### ISSUE TITLE
DPL-nnn [BUG] Sequencing pipelines should validate aliquots [C=M, V=3]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3330]
There are certain fields in aliquot that are required downstream for correct processing of sequencing information. These include:

1) library_id
2)  library_type
3) fragment_size_from
4) fragment_size_to

The latter two cause an exception in the batch.xml generation

Mostly this is a result of an incomplete library manifest, but can also happen following intervention in other pipelines or weird process flows.

Currently the sequencing pipelines perform no validation, and as a result samples get blocked in analysis. It would be nice if this missing information was surfaced earlier. While its tempting to block the pipeline, it may be better to display a prominent warning on the batch page instead, as there isn't a major reason to block progress. 

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by stevieing** [comment]
@JamesGlover It would be good to get an indication of the value of this story so we can get an idea of wher it sits in our list of priorities?

**Comment by JamesGlover** [comment]
This is mostly about:
1) Reducing the number of RT tickets by providing sufficient information to users to address the problem earlier.
2) Improving turn around times in the case of faulty data by reducing the feedback loop.

Given there are benefits to us, NPG, operations and customers I think, despite the issue being fairly rare, it offers a fairly decent value. (3 perhaps?) The other affected parties may have their own thoughts.

**Comment by SujitDey2022** [comment]
Closing based on the comment mentioned in https://docs.google.com/spreadsheets/d/14Rh3Q1l_d1tqcxZy6wploMXQV_kSiBfamkaJzwgjt8E/edit#gid=0
