### ISSUE TITLE
DPL-nnn Refine PhiX detail tracking for sequencing [C=S, V=?]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3331]
**User story**
As a sequencing Operator (Tris) I would like some refinements on the Sequencing pipelines to streamline the process, particularly Heron.

**Who are the primary contacts for this story**
Tris B
James G

**Acceptance criteria**

These criteria came out of a refinement of a story initially requested in RT#731220
https://rt.sanger.ac.uk/Ticket/Display.html?id=731220

To be considered successful the solution must allow:
- [ ] Add spiked in controls task should also record (automatically, based on the scanned tube):
        - Scanned PhiX stock [parent of scanned tube] name (eg NovaSeqPhiX_Heron_2)
        - We should probably also include the name of the scanned tube itself
- [ ] Move tracking of PhiX % from descriptors task to AddSpikedInControls. Only needed when PhiX is actually being added (so can be included in the same div that would usually be hidden

**Comment by stevieing** [comment]
Chase up with Tris to find out how much of an issue is.
How much time will it save?
