### ISSUE TITLE
[3rd Aug] DPL-258 - Switch from plate_barcode to baracoda for barcode generation so that we avoid 20 hours of Heron downtime due to the legacy Oracle database reaching end of life(C=M, V=3)

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3365]
**Describe the Housekeeping**
The plate barcode service uses a concurrency safe counter which is shared by other teams with the Sanger to generate unique barcodes. This results in a dependency on the Oracle database.

It would be nice to retire this in favour of using exclusively baracoda. This will require some work in Sequencescape to generate barcodes with non-clashing prefixes.

This will require updating the barcode generation in Sequencescape to use new prefixes that don't clash with the old DN numbers. The new prefixes should be registered in baracoda.

It might be nice to consider a few different prefixes, to make more useful barcodes.

WARNING: While external barcode support means that the switch should be reasonably smooth, I predict a LOT of busy work fixing assumptions made in the tests.

**Acceptance Criteria**
- [x] Barcodes generated by Baracoda should not clash with barcodes that continue to be generated using the Oracle DB
- [ ] Once deployed to production email David H and Aftab A so they can schedule the hardware upgrade of the Oracle database.
- [x] Barcode prefix for production sequencescape: SQPP
- [x] Barcode prefix for uat sequencescape: SQPU
- [x] Barcode prefix for training sequencescape: SQPT
- [x] Barcode for working dilutions sequencescape using same barcode of the parent but with a hyphen, like: SQPP-XXXX-1
- [x] Add a coment to the BarcodePrefix model that will be deprecated

**Related issues** 
https://github.com/sanger/plate_barcode/issues/11

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by JamesGlover** [comment]
Communication April 2021 with Tim C confirms direction to reduce Oracle usage:

> Thanks Rich, it is. I was fairly clear to the EBI yesterday that Sanger’s usage was only going to decrease, not increase.

**Comment by JamesGlover** [comment]
Comms back in 2018 confirms other teams using the SEQ_DNAPLATE counters:
>  
> From: Jon T<jwt>
> Subject: RE: Oracle SNP database SEQ_DNAPLATE counter
> Date: 29 October 2018 at 10:35:16 GMT
> To: Beth F , Adam B <apb>
> Cc: Andrew M <am3>
>  
> Hi Beth,
>  
> See emails below.
>  
> Best,
> Jon
>  
>  
> From: Andrew M <am3>
> Sent: 18 October 2018 16:29
> To: Adam B <apb>
> Subject: Re: Oracle SNP database SEQ_DNAPLATE counter
>
> Yes, we still use SNP for our DNP plate tracking.
>  
> Andy
> 
> On 18 Oct 2018, at 13:16, Beth F wrote:
>  
> Hello 
>  
> Do you know if you’re still using the Plate IDs from SNP for plate barcodes (if indeed you ever did)?
>  
> Beth
>

**Comment by TWJW-SANGER** [comment]
I have agreed to priortise this story over the other existing Heron user stories to avoid the 20 hours of downtime required to move the Oracle database this service depends on.

One query: _This will require updating the barcode generation in Sequencescape to use new prefixes that don't clash with the old DN numbers. The new prefixes should be registered in baracoda._
If we can guarantee continuity of the barcodes generated when switching over to Baracoda do we need new prefixes? For example if Plate Barcode's next seed is x (possibly for a given prefix), then make Barcoda's next seed x + N for that existing prefix where N is large.

**Comment by emrojo** [comment]
Checklist for UAT:
- [ ] Testing in Samples management
- [ ] Testing by SSR
- [ ] Testing in HTP 
- [ ] Testing in NPG
- [ ] General users tests

**Comment by emrojo** [comment]
Samples management and SSR testing found that a suffix would be a desirable requirement of the barcode format so we have added it. After the changes they have validated their part.
HTP wants to identify the risks about this change. To be able to test with HTP we would need:
  - Have a person from HTP assigned to test in HTP lab
  - Have a person assigned from SSRs to create the submissions and send the details to HTP test
  - Have a person assigned from NPG to validate the result of the tests
  - Identify the submissions required to create for the HTP tests.
  - SSRs to create the submissions and send the details to HTP
  - HTP to perform the test run
  - At the end NPG to check the data is right from their end
