### ISSUE TITLE
DPL-147 Currently we can’t trigger the right analysis pipeline for Targeted NanoSeq samples as we don’t have the corrected library type available at the point of creating the Re-ISC submission. I (Stef) need the Duplex-seq library type (which already exists) to be added as a library type on all templates (S)

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#3379]
**User story**
Currently we can’t trigger the right analysis pipeline for Targeted NanoSeq samples as we don’t have the corrected library type available at the point of creating the Re-ISC submission. I (Stef) need the Duplex-seq library type (which already exists) to be added as a library type on all templates.

**Who are the primary contacts for this story**
Stef

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The Duplex-seq library type can be selected on the Re-ISC submission templates.

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by sdjmchattie** [comment]
Tried to test this in UAT today.  It looks like it might be working correctly, but I wanted Stef to approve it.  Unfortunately she is unavailable at the moment so will catch up with her later when possible.
