### ISSUE TITLE
DPL-149 - As a quanthub user I need tube barcodes to be human readable (code 39) so that when I quant them I can easily recognise which tubes are in which wells

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#3386]
**User story**
As a quanthub user (Ben & Sara) I need tube barcodes to be human readable (code 39) so that when I quant them I can easily recognise which tubes are in which wells

**Who are the primary contacts for this story**
Ben / Sara

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When I print off a tube barcode and scan it it should be human readable e.g. NT123 rather than machine readable e.g. 123456789012
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by JamesGlover** [comment]
Working out the template layouts with a bit of difficulty, but also assessing impacts. I've updated a handful of tests, and have identified the following concerns:

`Plate#summary_hash` still seems to refer to the ean13 only, and the actual validation checked that the barcode length was 13. However the associated pipeline 'FlexibleCherrypicking' hasn't been used for four years, so this has gone unnoticed. I removed the length check, but couldn't find anywhere actually using the returned barcode information. Left that unchanged while I chase SSRs about value in keeping that pipeline. Either way, anything broken here will have been broken for a while.

`IlluminaHtp::InitialStockTubePurpose#sibling_tubes` returns ean13 barcode information for matching purposes in Limber. We can return and use machine barcode instead. However, as the code already has a note suggesting we should move the logic to limber, I'm evaluating each option.

`Transfer::BetweenPlateAndTubes#barcode_to_hash` uses ean13, but not machine barcode. Adding machine barcode to this, and evaluating impact.

**Comment by JamesGlover** [comment]
I can't find any direct usage of `Transfer::BetweenPlateAndTubes` being recorded in. the database, checking for subclasses

**Comment by JamesGlover** [comment]
This transfers has gets exposed via the API.

**Comment by JamesGlover** [comment]
This gets used via the 'Transfer wells to MX library tubes by submission' transfer template in limber in the FinalTubeFromPlate creator at the bottom of the ISC pipeline.

**Comment by JamesGlover** [comment]
Ironically this is one of the points where a tube-rack would make more sense!

**Comment by JamesGlover** [comment]
Hmm, looks like we're only using the uuid here in the information pulled back.

**Comment by harrietc52** [comment]
Services and their printing
https://docs.google.com/spreadsheets/d/14DU8zbAMrk3EEUceUY5pt7m6hLp7343MHsWQuDyq-aU/edit?usp=sharing

**Comment by JamesGlover** [comment]
Had a bit of a revisit of this now I'm back on site, and managed to get a template that could scan both 13 digit and human readable barcodes successfully (x=0300 seemed to work well but might be mistaken as I didn't have access to a pen - however a few values did work). Meanwhile testing with the squix printers reveals zero issues there.

I did note that the x offset values don't seem to be precise, as several values map to the same output. In addition, things are incredibly tight, so may not work for all alignments. Still, it *is* possible.
