### ISSUE TITLE
DPL-156 As a Genomic Surveillance Operations Officer (Alan K) I would like to the plate map ingestion process to recognise the new lighthouse plate barcode for the Lemington Spa Lighthouse so we can keep processing their plates

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3409]
Lemington Spa (LSPA) will be producing new plate barcodes in the coming months (estimated ~December).

These barcodes will follow the following standard: RFLCPnnnnnnnn (where n = number) for example RFLCP12345678

Expect file names to follow same format as currently used: LML_ RFLCP12345678.csv

Alan K: "Let me know if you need any more info – I’ll keep you posted as we draw closer to go live date."

Story created from [RT733798](https://rt.sanger.ac.uk/Ticket/Display.html?id=733798)

**Comment by KatyTaylor** [comment]
I moved this to the sequencescape repo as I think the main (only?) changes needed will be in the 'foreign barocodes' section (`barcode.rb` and `format_handlers.rb`).

**Comment by emrojo** [comment]
Just thinking it will require a small change in config in crawler to read the new filename too

**Comment by emrojo** [comment]
Tested that changes work in UAT
