### ISSUE TITLE
DPL-174 Tube controls manifest (C=S, V=5)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3417]
**User story**
As a member of the Cardinal team, I would like to be able to generate a batch of control samples in the LIMS, so that I have unique barcodes to stick on each tube prior to freezing, and so that I can later scan these tubes into the LIMS in the Cardinal pipeline, to track which control I added.

This is necessary from when Cardinal UKB start arriving, because they require the addition of controls.

**Who are the primary contacts for this story**
Stephen W, Eve C, Katy, Andrew

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] New unique barcodes can be generated for a batch of tubes of specified size, and printed out.
- [ ] Samples are generated for each of these tubes, with the 'control' flag set to true and the 'control_type' field set to 'positive' (integer '1' in the database).

Suggested way to implement:
- [ ] New tube manifest type that has the 'control type' column

**Additional context**
Meeting notes about useage of controls in Cardinal pipeline here - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cardinal+Controls

**Comment by stevieing** [comment]
Katy (26/01) - They need to put something like one control through per week, for UKB. So, without it, they can put non-UKB samples through, and they can put UKB samples through for a week before they're stuck.

**Comment by harrietc52** [comment]
To include https://github.com/sanger/General-Backlog-Items/issues/166
