### ISSUE TITLE
DPL-188 - Simplified Heron Request Graph (C=M, V=4)

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3451]
**User story**
As a developer I would like to simplify the heron request graph in order to reduce the number of edge-cases in the Heron pipeline. (Note: This story also has limber requirements)

- Heron submissions should build *just* the limber_heron request type (or possibly a V2 flavour?) [Edit: Yep, a V2 request type would make a seamless transition far easier]
- This request type should now be flagged as `for_multiplexing`
- This request should cover the *entire* library creation pipeline in limber
- No longer create the final tube up-front (Will require a new tube purpose)
- Remove the charge and pass step form the pool plate
- Instead should charge and pass at end of pipeline and build sequencing requests then.

This change:
- Avoids the need to explicitly know which RT plates will be processed together when building submissions
- Removed the pain points where you can't easily jump back to a previous step
- Avoids the need to 'charge and pass' before you get the QC data on the XP tube

Edit:

Note: Complexity high due to uncertainty. The actual core changes are fairly simple, and we may get lucky. But I'm anticipating a number of unknowns.

**Who are the primary contacts for this story**
James

**Acceptance criteria**
- [x] Update LucidChart doc
- [ ] Update Confluence "Limber mistakes" page
- [ ] Communicate changes to Heron leads

**Comment by KatyTaylor** [comment]
I've created pull requests in Limber, SS and Integration Suite for this. 

To remember: old submission templates will need updating to be marked as superseded by the new ones.

Have not yet updated the documentation or communicated anything to the Heron lab team.

**Comment by KatyTaylor** [comment]
Script for updating submission templates:

```
old_template = SubmissionTemplate.find_by(name: 'Limber - Heron LTHR - Automated')
new_template = SubmissionTemplate.find_by(name: 'Limber - Heron LTHR V2 - Automated')
raise "Can't find the relevant submission templates" unless old_template && new_template

old_template.update!(superceded_at: Time.zone.now, superceded_by: new_template)
```

**Comment by KatyTaylor** [comment]
Queries for after release - for checking whether there are still in-progress `limber_heron_lthr` requests, and therefore whether we can delete the old pipelines.

```
SELECT count(r.id), state
FROM requests r
JOIN request_types rt ON rt.id = r.request_type_id
WHERE rt.key = 'limber_heron_lthr'
GROUP BY state;

SELECT count(r.id)
FROM requests r
JOIN request_types rt ON rt.id = r.request_type_id
WHERE rt.key = 'limber_heron_lthr'
  AND r.state IN ('pending', 'started');
```
