### ISSUE TITLE
DPL-237 [BUG] Failing a 'pending' plate throws error [C=S,V=2]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3495]
**Describe the bug**
Trying to fail a plate that is in state 'pending' (from Limber) throws following error:

> There is an issue with the API connection to Sequencescape ({"general":["0 permitted transitions from 'pending' to 'failed'"]})

**To Reproduce**
Steps to reproduce the behaviour:
1. SS - UAT Actions - Generate plate - LTHR Cherrypick
2. Limber - Scan above plate
3. Click button to go down the 384 Heron pipeline
4. Add an empty LTHR-384 RT-Q plate
5. Paste same plate barcode into Plate 1 box, click off box, click Create
6. Scroll down, change plate state to 'failed', click red button 'Fail Labware'
7. See 500 error and message in email "0 permitted transitions from 'pending' to 'failed'"

**Expected behaviour**
The page should either not display the option to fail the plate, if it is not allowed, or allow transitions to failed from pending.

**Additional information**
See class app > models > request > statemachine.rb

**Comment by JamesGlover** [comment]
Given 'pending' typically indicates the plate is empty, and failed that the material in it either doesn't meet QC standards, or has somehow been contaminated, then a transition from pending to failed doesn't really make sense. So it would probably be better to hide the option. I must admit, I thought this was already the case. I thought the options were populated via querying the statemachine, albeit the Limber implementation, for permitted transitions
