### ISSUE TITLE
DPL-240 - The sequencing team would like a web page within the LIMS where they can either add annotations or upload associated documents to a sequencing batch (C=M, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#3499]
**Description**

**Current process:**

- you print batch sheets from Sequencescape
- You annotate them with various pieces of information e.g. volume, amount of elution buffer, loading concentrations, instrument number
- Once you have finished you need to keep a copy of annotations (which should not be seen by the customer) for future reference
- Each batch sheet is scanned and placed in an archive directory
- Once a week someone runs a python script which takes each archived batch sheet and renames it with the unique batch id to identify it later on
- The files are then checked manually to ensure all of the files have been renamed
- You currently produce 50-100 batch sheets a week

**Limitations of current solution:**

- The script is only 95% effective as if it can’t rename the file it drops it
- The script requires the use of a third party library Tesseract OCR to read from the pdf
- You have contacted IT and they have indicated that the script needs to be secure and maintained
- The script is run on the command line so note everyone has the skills to be able to set it up and use it
- The script is not maintainable as it was created by a former colleague and no-one has the ability to amend or improve it

**Ideal solution:**

- a web page within our current LIMS where you can either add annotations to a current batch or upload associated documents which would then be associated with that batch
- ability to upload several documents to a single batch

**Who the primary contacts are for this work**
Robert / Tristram

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Relates to [RT740861](https://rt.sanger.ac.uk/Ticket/Display.html?id=740861)
The current script:
[Python-batch-script.txt](https://github.com/sanger/sequencescape/files/7887615/Python-batch-script.txt)

**Comment by stevieing** [comment]
20/01 - Emma to discuss with Rich about whether there needs to be a bigger process change. A lot of this seems to be unnecessary. Also the SSRs spend at least half a day a week preparing batch sheets. The question is can we remove the need for them but still allow the sequencing team to add annotations to the batch.

**Comment by stevieing** [comment]
RT740861

**Comment by harrietc52** [comment]
James thinks uploads docs used to be possible in back end code, but was no longer being used (and out of date code).

**Comment by harrietc52** [comment]
Outputs:
- show them how to use current annotation feature, and if this is enough
- or figure out what extra fields are needed
- or if they just want to attach document
- or if they do need a new page,  why and what for
