### ISSUE TITLE
DPL-259 - As the long read team we would like to have specific plate and tube manifests for ToL to improve the process, save time and reduce errors (C=S, V=4)

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#3505]
**User story**
As the long read team we would like to have specific plate and tube manifests for ToL. Current process:

- pacbio send out a plate manifest to ToL
- when it comes back change plate purpose to pacbio
- barcodes have to be hand written on the tube by ToL
- James does a submission through Sequencescape

However ToL submit samples in tubes (but samples can be submitted in plates) so we would like a specialised plate and tube manifest for ToL with specified columns.

Having specialised sample manifests would improve the process, reduce the time taken to register samples and reduce errors.

**Who are the primary contacts for this story**
Liz C

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] we should be able to create a plate manifest specifically for Long Read with the following columns (TBC)
- [ ] we should be able to create a tube manifest specifically for Long Read with the following columns (TBC)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Part of this work has already been done so it might just be a case of modifying what is already there.

**Comment by JamesGlover** [comment]
This is also probably covered by DPL-123
