### ISSUE TITLE
DPL-299 [BUG] 404 when NPG update lane qc state if requests greater than 1

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#3525]
**Describe the bug**
As PSD we need to fix a bug, whereby when NPG send a message to update the qc state of a Lane, a 404 is returned if there is more than one sequencing request on the lane (e.g. example we saw was where one had been cancelled and a new one created). Check needs to be changed so is only looking for one active request.

**RT Ticket Number**
742604

**To Reproduce**
Steps to reproduce the behaviour:
1. Create more than one sequencing request for a lane, cancelling one and leaving a second active
2. Trigger the action_for_qc_state method in the AssetsController
3. The before action on AssetsController calls the find_request method which errors because requests.one? is false for the lane

**Expected behaviour**
The manual_qc state for the lane then does not get updated to Pass

**Additional context**
See this bit of code in Assets controller (controllers/npg_actions/assets_controller) starting line 66) in Sequencescape:

```
def find_request
  requests = @asset.requests_as_target
  raise ActiveRecord::RecordNotFound, "Unable to find a request for Asset: #{params[:id]}" unless requests.one?

  @request = requests.includes(batch: { requests: :asset }).first
end
```
requests does not filter to return only active requests. Also, error message is confusing, as we do find requests.
Maybe 'Unable to identify a suitable single request for Asset' or similar.

**Comment by emrojo** [comment]
```
irb(main):003:0> Lane.find(37415542).requests_as_target.count
=> 2
```
