### ISSUE TITLE
DPL-319 Add printers to LIMS

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3559]
Add new Squix printers to required LIMS (SS< Limber etc)

Printer 1

- Hostname: aa209bc1
- IP Address: 172.30.1.108
- MAC Address: 00:02:E7:08:64:97
- Label Type: Tube Labels

Printer 2

- Hostname: aa209bc2
- IP Address: 172.30.1.176
- MAC Address: 00:02:E7:08:64:AA
- Label Type: 96 Plate Labels

Relates to [RT745946](https://rt.sanger.ac.uk/Ticket/Display.html?id=745946)

Contact: Abby C (ac38)

**Comment by stevieing** [comment]
Link to confluence document to explain what is needed for setting up printers https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/SQUIX+printing
