### ISSUE TITLE
DPL-329 Find all plates run on a particular robot during a time period [C=?, V=4]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3569]
**User story**
As a Heron manager I would like to be able to find all labware that were run on a particular robot in a given time period. This will enable me to investigate and resolve contamination events associated with a particular robot.

**Who are the primary contacts for this story**
Barbora, Katy

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can find all labware run on a particular robot in a given time period

**Additional context**
Tom has previously produced a report for Sara showing this (June / July 2021?) - check out how this worked.

**Comment by TWJW-SANGER** [comment]
I think this might be referring to RT 724034. (The solution to this was very specific).
I wonder if with the plate tracking events being enhanced for other stories, if that might be an alternative more generic solution for this?
