### ISSUE TITLE
DPL-369 update data text, contact and information in 'Reason for delaying release' section of the manage study page

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3603]
**User story**
As Head of Research Governance (Carol Smee) I  would like the 'Reason for delaying release' section of the Study Create, Edit, and Manage pages changed.
The bullet points should be removed and the only text should be
**"To apply for a delay, please contact datasharing@sanger.ac.uk"**
example is  https://sequencescape.psd.sanger.ac.uk/admin/studies/6868

sequencescape/config/locales/metadata/en.yml
the help text for the data_release_delay_reason requires amending.
The data sharing contact also needs updating.

~~Also where HMDMC is mentioned, please change to 'HMDMC/HuMFre' in all instances.~~ (This requirement was managed as part of https://github.com/sanger/sequencescape/issues/3697)

For ref. RT is [749904](https://rt.sanger.ac.uk/Ticket/Display.html?id=749904)

Customer comment: "... the information is very out-of-date by several years!"

**Comment by neilsycamore** [comment]
DPL-481 closed, superseded by DPL-555
Acceptance criteria "Also where HMDMC is mentioned, please change to 'HMDMC/HuMFre' in all instances." superceeded by DPL-555.
Bullet point amendments still required

**Comment by SujitDey2022** [comment]
Need to update the story with the requirements completed.

**Comment by neilsycamore** [comment]
I have today contacted Carol to confirm the remaining work is required

**Comment by neilsycamore** [comment]
Can this go ahead as planned, please?

I confirm that the wording in the bullet points is very out-of-date and no longer applicable. Please replace with "To apply for a delay, please contact [datasharing@sanger.ac.uk](mailto:datasharing@sanger.ac.uk)'.

Thank you.

Kind regards,

Carol
Head of Research Governance

**Comment by SujitDey2022** [comment]
Hello @neilsycamore, I could not understand how to add my query to the RT Ticket and so raising it here. Could we confirm if we need to reflect this change across Study Create, Edit, and Manage pages as they are related? 

![image](https://user-images.githubusercontent.com/115623404/222761762-13a0d566-3d4c-4230-87bd-53e92d3aa8fc.png)

**Comment by yoldas** [comment]
We have also changed the data sharing contact name and email for sequencescape production ( dpl-369-data-sharing-config in deployment repo).

**Comment by yoldas** [comment]
Attached screenshot.

<img width="736" alt="Screenshot 2023-03-14 at 16 20 53" src="https://user-images.githubusercontent.com/91894/225070957-3fc79b04-a652-4ff7-9647-7eda3679d286.png">

**Comment by yoldas** [comment]
UAT Feedback:

For a PhD study, there would not need to be an application to [datasharing@sanger.ac.uk](mailto:datasharing@sanger.ac.uk) as the delay in these cases is covered by our standard Data Sharing Policy exemption. The proposed changes to SequenceScape currently read as though this would need to happen.
 
Maybe it would be better to phrase it as: ‘To apply for a delay which is not associated with a PhD study, please contact [datasharing@sanger.ac.uk](mailto:datasharing@sanger.ac.uk)’, and/or to remove this text for the PhD study delay option in the drop down and only have it appear if an another reason for delaying release is selected in the drop down?

**Comment by yoldas** [comment]
phd study option: No help text under "Reason for delaying release"

<img width="743" alt="phd_study" src="https://user-images.githubusercontent.com/91894/228398518-2d4e3b86-a78e-42e2-b096-322ac6e88b94.png">

other option: help text under "Reason for delaying release"

<img width="747" alt="other" src="https://user-images.githubusercontent.com/91894/228398533-989526d9-7e22-4c65-acba-0c710b6ddc21.png">

**Comment by yoldas** [comment]
Received email from sb46: "All studies, including PhD, should request a delay."

I suggested the following temporary fix below and it was also accepted:

- Change the help text as it will give a more up-to-date help and correct contact information:
To apply for a delay, please contact [datasharing@sanger.ac.uk](mailto:datasharing@sanger.ac.uk)

- Always show the help text for now; Do not hide the help text when phd study is selected for Reason for delaying release.
