### ISSUE TITLE
DPL-406 Research API v2 authentication, user authentication and authorisation

### ISSUE THREAD

**Issue by harrietc52** [sanger/sequencescape#3620]
**Description**

Generalised architectural plan for API authentication, user authentication and authorisation

Consider:
- users via browser
- user via intermediate applications (e.g. Limber UI talking to SS backend)
- internal calls
- platform independent (Ruby/Python/JS/Vue)

**Who the primary contacts are for this work**
@harrietc52 
@JamesGlover 

**Knowledge or Stake holders**

Might be worth having a day committed learning, where everyone can research different approaches, possibly a Wednesday? On Site activity. Could we get an expert in?

**Additional context or information**

Research task required for https://github.com/sanger/deployment/issues/128

**Comment by JamesGlover** [comment]
Worth considering if we can backport the solution to, say, API V1 without breaking existing authorization
