### ISSUE TITLE
DPL-411 Add ability to create WD plate from Stock RNA plate (C=? V=4)

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3625]
As Sample Management we would like to have the ability to make Working Dilution (WD) plates from Stock RNA plates in Sequencescape (atm we perform this in samples extraction) 

Relates to [RT753096](https://rt.sanger.ac.uk/Ticket/Display.html?id=753096)

Contact Danni

**Comment by SujitDey2022** [comment]
Need to review the user-story and check if it can be merged with other stories related to moving of capabilities from sample extraction to sequence scape.
