### ISSUE TITLE
DPL-417 Track requested flowcell type for Novaseq sequencing requests

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#3628]
**User story**
As a sequencing tech, I would like to track the requested flowcell type for NovaSeq, and have it displayed in the Sequencing inboxes.

See https://github.com/sanger/sequencescape/issues/3629 when writing the migration, a reverse_read_length (integer) column in request metadata would be good to add at the same time in preparation.

**Who are the primary contacts for this story**
Tris (Inboxes)
Siobhan (Submissions)
Rich R (Billing)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Permitted Flowcell types are SP, S4, S2 - Suggest adding a 'flowcell_types' table with an association with request types, rather than hard-coding.
- [ ] Note: NPG are ultimate arbiter on what flowcell type was *Actually* used, so we probably don't want to expose this information in the WH. Might be worth naming the parameter requested_flowcell_type to drive home that it reflects what was requested, not what was actually done.
- [ ] Flowcell type can be provided in bulk submission interface, and web interface - Note: Web interface generated automatically based on request_metadata. If you follow the existing patterns (such as those for library type) you *should* get this for free.
- [ ] Flowcell type should be displayed in sequencing inbox
- [ ] Sequencing inbox can be filtered based on flowcell types - See [datatables](https://datatables.net) for table configuration. Probably worth enabling filters for other columns [Example column filtering](https://datatables.net/examples/api/multi_filter_select.html)
- [ ] Remove unwanted columns Submission, Product Line, Previous Requests, Submitted at - Previous requests and submitted at in particular have a decent chunk of supporting code that might be able to be removed. 

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by Skrich1999** [comment]
Siobhan and Tris will be the Key UAT people for this story.  (Siobhan is on AL from 18th to 31st Aug).

**Comment by emrojo** [comment]
Tasks to do:
- [ ] Record loader implementation to add config data in database
- [ ] Create a test for validator and for sequencing request
- [ ] Fix Javascript problem and create test for views
- [ ] Add feature test

**Comment by emrojo** [comment]
**Config/tasks done**
Changes in the name of the columns flowcell_types_request_types
Changing the request_type_key
Created a new submission template in local
Added with record_loader the new information_types

**What is done from the requirements**
Requested flowcell displayed when using the right request type with a submission template
Requested flowcell can be updated when building with a submission template with web
Requested flowcell is displayed in the submission spreadsheet
Requested flowcell is displayed in the right pipeline inbox view

**To do:**
Submission spreadsheet is not displaying the right values in the requested_flowcell column
Javascript not sorting/failing
Some tests may be required yet
