### ISSUE TITLE
DPL-421 Advanced Search page

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3636]
**Describe the Housekeeping**
In implementing https://github.com/sanger/sequencescape/issues/3630 I created a new search tab and page within Sequencescape. I also described in [this comment](https://github.com/sanger/sequencescape/issues/3630#issuecomment-1163268779) how there are several, overlapping, search functions within Sequencescape, and it would be a better user experience to consolidate them into one advanced search page. I intended the new search page to be the beginnings of that page - it is named /advanced_search, and the tab is named generically as 'Search'.

- This 'Advanced Search' page should be extended to cover the functionality in the 'Lab View' and 'Lab Search' pages. 
- In addition, the top right search box could be modified to be a rapid, barcode-only search, and the more advanced functionality from that also absorbed into the 'Advanced Search' page.
- The 'Advanced Search' page should also retain the custom metadata related functionality that it was initially related for.

N.B. 'Lab View' also allows users to edit a couple of fields on tubes (search for a tube barcode to see this UI). I believe that this is not an intuitive place for this functionality, but I think it is used, so it needs to be retained somewhere. I think it is possible to do this in Limber? But may need some customer communication. I believe at least the bespoke team use this edit functionality.

**Comment by JamesGlover** [comment]
Ahh, I'm wondering if this is where out mysterious concentrations without QC results are comming from...

**Comment by SujitDey2022** [comment]
Can be revisited in future and scoped
