### ISSUE TITLE
DPL-467 [12th September] SGE library type creation for use with the creation of barcoded multiplexed library pool tube manifests

### ISSUE THREAD

**Issue by Skrich1999** [sanger/sequencescape#3663]
User story describing what is required:
As a user, Nick R and Mike Q need a new library type for processing samples which have be processed through the SGE pipeline in RnD (Nick will be processing 3 x 96 samples).  This new library type is to be called “SGE Library v0.2” and is to be added into manifest templates, specifically the Multiplex Library Tube manifest.

Primary contacts for this story:
Richard C, Michael Q, Nicholas R, David J

**Who is the nominated tester for UAT**
Richard C, and Nicholas R

**Acceptance criteria**
To be considered successful the solution must allow:

-  [ ]  Addition of “SGE Library v0.2” into library type for all library manifests
-  [ ]  “SGE Library v0.2” library manifest to be uploaded into lims
-  [ ] NPG to be notified of this new library type for SGE/Mave samples so that they can correctly interpret data for analysis.

**Additional context**
Story is expected to be small but is time dependent and ideally completed by w/c 12th September.

**Dependencies**
This story is blocked by the following dependencies:
- n/a

References
This story has a non-blocking relationship with:
- n/a

**Comment by TWJW-SANGER** [comment]
Is it sensible or possible to do this work in conjunction with[ DPL-466 ](https://github.com/sanger/traction-service/issues/807)?

**Comment by harrietc52** [comment]
- [ ] Add `SGE Library v0.2` to `library_types` in  `config/default_records/request_types/004_limber_high_throughput.yml`

**Comment by harrietc52** [comment]
To test:
```
Sequencescape >
Studies >
a study >
sample manifests >
create manifest for multiplexed libraries > 
Template >
Multiplexed Library Type >
Create manifest button >
Check library type is available in drop down column in downloaded spreadsheet
```

To run in UAT: 
`LibraryType.create(name: 'SGE Library v0.2')`

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
