### ISSUE TITLE
DPL-497 Record retention instructions against stock plates

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3673]
**User story**
As a Sample Management user, I would like the sample retention instructions to be recorded against stock plates when they are imported into Sequencescape, so that I know what to do with them later on.

**Who are the primary contacts for this story**
Danni W, Siobhan A-G, Katy

**Who is the nominated tester for UAT**
Danni W, Siobhan A-G

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] All plate manifests have a new mandatory field, 'Retention instructions', with the following options:
    - Destroy after 2 years
    - Return to customer after 2 years
    - Long term storage
- [x] Above field is mandatory - data must be provided
- [x] This information is saved on manifest upload, at the labware level (custom metadata?)

**Additional context**
This does not need to include a way to view this data once uploaded - that will be in another story (https://github.com/sanger/sequencescape/issues/3676)

N.B. If the 'Retention instructions' are stored in the custom metadata table, the functionality for https://github.com/sanger/sequencescape/issues/3676 could be achieved using Limber, as functionality has been recently developed to allow viewing and editing of custom metadata. You would need to add configuration to Limber to show the new field against the relevant plate purposes. Custom metadata can also already be viewed (but not edited) on the labware page in Sequencescape.

**Comment by Danniw373** [comment]
HI Katy, caught up with Emma. This requirement is for derivatives samples, not stock plates.

**Comment by KatyTaylor** [comment]
Clarification from Danni over Slack:

> The lifespan feature is for derivative samples (Assets audits) and the retention instructions should be manifest (Stock sample) but Emma mentioned it should be at a study level as well as a plate level.

**Comment by KatyTaylor** [comment]
Just adding some more info from Slack conversations ~ 11th Oct, as the above comments could be misleading.

The plan now is to focus on using the location report to report on retention instructions for all plates, whether stock plates or derivatives. The Asset Audits feature would still be used to log destruction, but not used by the Sample Management team to check whether labware can be destroyed or not. It may still be used by other teams though, e.g. the Heron team.

Retention instructions will be imported into Sequencescape at a plate level via sample manifests (or any equivalent system that imports samples, e.g. the message queue based systems that are coming in for ToL and other projects). These instructions should be able to be updated later on if needed.

Think the above requirements are still covered by the following previously written stories:

- https://github.com/sanger/sequencescape/issues/3673 (this one)
- https://github.com/sanger/sequencescape/issues/3674
- https://github.com/sanger/sequencescape/issues/3675 (lower priority)
- https://github.com/sanger/sequencescape/issues/3676 (lower priority)


For derivative plates, there is a request to include a date in the location report, which is the 'first scan into an Ogilvie freezer' - however, it will probably be easier to get the date from Asset Audits, when they receive labware using the "Reception fridge - 10010430" instrument. (N.B. Danni said "The only thing to be aware of is we could activity log a barcode as "received" multiple times, this happens if we return a plate to faculty who then send it back for further work. This is a low occurrence but in these instances i'd say we go with he latest date")
* No story exists for this at the moment, needs a bit of research as to how feasible it is to get this date and include it in the location report.

**Comment by Danniw373** [comment]
Asset audits feature - Life spans for plate types need to be updated for this to be used effectively https://github.com/sanger/asset_audits/issues/363

Having the date included in the report is key to ensuring stock samples are not destroyed too soon. Currently, we have the "data created" in the report which is fine for derivatives but stock plates can take months/years to be returned to site with samples. A story for this should be submitted to make sure it's not forgotten about.

**Comment by andrewsparkes** [comment]
Waiting to clarify from Danni which manifest types should have the new column. Current PR has it set on all plate types.

**Comment by KatyTaylor** [comment]
Closing issue as it's in Done column
