### ISSUE TITLE
DPL-498 Report on retention instructions

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3674]
**User story**
As a Sample Management user, I would like the plate location report to include any 'Retention instructions' recorded against the labware, so that I can find out what to do with old plates. The other information in the location report will also be useful in this context for cross-referencing.

**Who are the primary contacts for this story**
Danni W, Siobhan A-G, Katy

**Who is the nominated tester for UAT**
Danni W, Siobhan A-G

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Plate location report includes new column, that contains 'Retention instructions', if there are any against the labware

**Dependencies**
This story is blocked by the following dependencies:
https://github.com/sanger/sequencescape/issues/3673 - this is where the 'Retention instructions' will be added.

**Additional information**
Location report can be found at https://training.sequencescape.psd.sanger.ac.uk/location_reports

**Comment by Danniw373** [comment]
Emma agreed the retention instructions should be at a stud and plate level. This is because multiple studies can be linked so the retention information should be carried across.

**Comment by KatyTaylor** [comment]
Closing issue as it's in the Done column
