### ISSUE TITLE
DPL-576 Autologin to UAT SS from integration tests

### ISSUE THREAD

**Issue by emrojo** [sanger/sequencescape#3709]
**Description**
As a PSD developer I want to have a way to auto login into SS uat so I can run integration tests and that allows me to perform tests in SS side too.

**Acceptance criteria**
- [ ] I can run a test with SS from the integration suite tools that allows me to log in without providing credentials
- [ ] The solution does not compromise security

**Who the primary contacts are for this work**
Eduardo Martin

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by SujitDey2022** [comment]
Discussed with Eduardo and closing this as the story has low value and impact
