### ISSUE TITLE
DPL-632 - As developers we need to understand if there will be any impact on accessioning based on the EBI changes to the API [Time Sensitive - 1/2/23]

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#3733]
**Description**
Subject: [Ena-announce] Change to presented ENA Sample XML content 1st of February 2023 [EXT]
 
Dear Colleagues, a happy new year to you!
This is for the attention of anyone who retrieves Sample metadata in the XML format from the ENA Browser or the ENA Browser API.

In ENA, a sample is identified by its BioSample accession (starts with SAM. e.g. SAMEA8005050) or its SRA accession (starts with ERS/SRS/DRS. e.g. ERS5692297).

Currently, when fetching the Sample XML using either the BioSample accession or the SRA sample accession, the SRA sample accession is returned as the primary ID.
For example: [https://www.ebi.ac.uk/ena/browser/api/xml/SAMEA8005050 [ebi.ac.uk]]()

 ...

<SAMPLE accession="ERS5692297" alias="COVID-1" ...>
     <IDENTIFIERS>
          <PRIMARY_ID>ERS5692297</PRIMARY_ID>
          <EXTERNAL_ID namespace="BioSample">SAMEA8005050</EXTERNAL_ID>
...
 
On 1st of February 2023, we will change the returned XML content so that when retrieving by BioSample accession the primary ID will be the Biosample accession, and the SRA sample accession, if it exists, will be returned as the secondary ID:
...
<SAMPLE accession="SAMEA8005050" alias="COVID-1" ...>
     <IDENTIFIERS>
          <PRIMARY_ID>SAMEA8005050</PRIMARY_ID>
          <SECONDARY_ID>ERS5692297</SECONDARY_ID>
          <EXTERNAL_ID namespace="BioSample">SAMEA8005050</EXTERNAL_ID>
...

 
This change is required as we will switch to BioSamples ([https://www.ebi.ac.uk/biosamples [ebi.ac.uk]]() as the source authority for the sample metadata presentation in ENA. The change will allow us to present samples that do not have an SRA sample accession, e.g. SAMN05284377.
 
For backward compatibility, when retrieving by SRA sample accession the primary ID will remain the SRA sample accession and the secondary ID will remain the BioSample accession.
The new Sample XML content can already be retrieved from our development service for testing purpose.
New Sample XML with the BioSample accession only, requested using the BioSample accession:
[https://wwwdev.ebi.ac.uk/ena/browser/api/xml/SAMN05284377 [wwwdev.ebi.ac.uk]]()

New Sample XML with both the BioSample accession and the SRA sample accession, requested using the BioSample accession:
[https://wwwdev.ebi.ac.uk/ena/browser/api/xml/SAMEA8005050 [wwwdev.ebi.ac.uk]]()

New Sample XML with both the BioSample accession and the SRA sample accession, requested using the SRA sample accession:
[https://wwwdev.ebi.ac.uk/ena/browser/api/xml/ERS5692297 [wwwdev.ebi.ac.uk]]()
 
If you have any questions or concerns about this change please contact us via the ENA support form: [https://www.ebi.ac.uk/ena/browser/support [ebi.ac.uk]]()

Best regards,
Suran

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by Sangeetha-Bheeman** [comment]
No changes required as we are not using this SAMPLE_SET XML response in our applications.
