### ISSUE TITLE
DPL-638	Cardinal informatics: map which qc metrics belong to which pool

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3740]
In the Cardinal project we have repeated samples and need to figure out which qc metrics belong to which pool

What would be the mlwh query to get the mapping between mlwarehouse.qc_result.id_pool_lims (something like 'SQPP-2744-H:D5') and a mlwarehouse.sample.name experiment_id - something like 'CRD_CMB13195925'?

query is:

~~~~sql
SELECT * FROM (SELECT DISTINCT donors.id_sample_tmp,sample.name as experiment_id,original_study.name as cohort,donors.customer_measured_volume,donors.supplier_name as donor FROM mlwarehouse.iseq_flowcell
 JOIN mlwarehouse.sample ON iseq_flowcell.id_sample_tmp = sample.id_sample_tmp 
 JOIN mlwarehouse.study ON iseq_flowcell.id_study_tmp = study.id_study_tmp 
 JOIN mlwarehouse.iseq_product_metrics ON iseq_flowcell.id_iseq_flowcell_tmp = iseq_product_metrics.id_iseq_flowcell_tmp
 JOIN mlwarehouse.iseq_run on iseq_run.id_run = iseq_product_metrics.id_run
 JOIN mlwarehouse.iseq_run_lane_metrics on iseq_run_lane_metrics.id_run = iseq_run.id_run
 JOIN mlwarehouse.psd_sample_compounds_components pscc ON iseq_flowcell.id_sample_tmp = pscc.compound_id_sample_tmp
 JOIN mlwarehouse.sample as donors ON donors.id_sample_tmp = pscc.component_id_sample_tmp
 JOIN mlwarehouse.stock_resource ON donors.id_sample_tmp = stock_resource.id_sample_tmp
 JOIN mlwarehouse.study as original_study ON original_study.id_study_tmp = stock_resource.id_study_tmp
 WHERE sample.name IN ('CRD_CMB13195930','CRD_CMB13195926','CRD_CMB13195922','CRD_CMB13195927','CRD_CMB13195928','CRD_CMB13195921','CRD_CMB13195929','CRD_CMB13195924','CRD_CMB13195920','CRD_CMB13195925','CRD_CMB13195923','CRD_CMB13195918','CRD_CMB13195919')
 AND donors.supplier_name LIKE "%30007454087%") as A
 LEFT JOIN (SELECT id_sample_tmp,id_pool_lims,CONCAT(value,' ',units) as 'live_cell_count' from mlwarehouse.qc_result  WHERE qc_type = 'live_cell_count') as B on A.id_sample_tmp = B.id_sample_tmp;
~~~~

The samples are repeated at 24h and 48h they have the same id_sample_tmp. but they end up in a different pools with a different ids.
from the info on the pool level i can find the id_sample_tmp = ‘8380396’ but this id maps to two different mlwarehouse.qc_result.id_pool_lims
so I need to find which one bellowngs to which by finding the additional join element instead of id_sample_tmp which would be mlwarehouse.qc_result.id_pool_lims

What is the bet way to join instead of A.id_sample_tmp = B.id_sample_tmp to avoid the replication of qc fields such as live_cell_count

Relates to [RT770309](https://rt.sanger.ac.uk/Ticket/Display.html?id=770309) also discussion in Cardinal Slack [channel](https://psd-team.slack.com/archives/C02CFSJUA9J)

Contact: Matiss O (mo11)

**Comment by yoldas** [comment]
Adding some notes:

From Cardinal Knowledge Transfer document slide 4, Compound samples - data model:
- A compound sample has many component samples.
- A component (=normal) sample can be part of several compound samples. e.g. if it's been down the pipeline more than once on different plates
- A sample cannot be both a compound and a component sample.

In qc_results, id_sample_tmp is for components.

In iseq_flowcells, id_sample_tmp is for compounds.

psd_sample_compounds_components gives the mapping between components and compounds.

**Comment by yoldas** [comment]
We do not have the mapping in mlwarehouse. Limber File exports give metrics per well though, which correspond to id_pool_lims. For example, 

Plate SQPP-2744-H at https://limber.psd.sanger.ac.uk/limber_plates/78b39ca4-3410-11ed-94dc-fa163eea3084

See SQPP-2744-H:D5 (Export2.csv - September 14, 2022 12:24) at https://limber.psd.sanger.ac.uk/qc_files/c5439e34-341f-11ed-b805-fa163eac3af7

and 

Plate SQPP-2829-L at https://limber.psd.sanger.ac.uk/limber_plates/3475d9fa-34ea-11ed-8920-fa163eac3af7

See SQPP-2829-L:F7 (Export_p3.csv - September 15, 2022 13:28) at https://limber.psd.sanger.ac.uk/qc_files/de8ef956-34f1-11ed-9f51-fa163eea3084

**Comment by yoldas** [comment]
Notes: https://docs.google.com/document/d/1JvRFYc1ISB8nnXlrZaRfyqLSZSamOQme_8rY_bopc-s/edit?usp=sharing

**Comment by yoldas** [comment]
We have created a new story: DPL-682 Provide a mapping between qc_results and compound_samples in mlwarehouse for Cardinal Project #3755
