### ISSUE TITLE
DPL-643 Add new element TITLE to DAC xml for EBI accessioning service

### ISSUE THREAD

**Issue by emrojo** [sanger/sequencescape#3742]
**User story**
As PSD I want to make changes to the DAC xml generation process to provide a new element required: TITLE, and add a test that check that all xml we generate are valid with the latests versions of the xml schemas from EBI because we want to detect if there is any breaking changes in the schemas used by EBI to validate.

EBI schema for DAC is in:
https://github.com/enasequence/schema/blob/master/src/main/resources/uk/ac/ebi/ena/sra/schema/EGA.dac.xsd

**Who are the primary contacts for this story**
Eduardo Martin

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Be able to publish a new DAC xml in EBI (currently is broken)
- [ ] Validate the DAC xml generated is valid with the schemas provided by EBI
- [ ] Notification of any validation schema errors to PSD

**STEPS TO REPRODUCE THE PROBLEM**

- Go to a study in SS
- Click on Generate DAC accession number
- The error displayed is: 
```
Could not get accession number. Error in submitted data: ["\n - Failed to validate dac xml, error: Expected element 'TITLE' instead of 'CONTACTS' here in element DAC", "\n - Failed to validate dac xml, error: Expected element 'TITLE' before the end of the content in element DAC"]
```

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by stevieing** [comment]
Closed as deprecated. I believe there is a bigger project in play for accessioning.

**Comment by TWJW-SANGER** [comment]
Archiving this in favour of more recent EBI stories
