### ISSUE TITLE
DPL-664 - Bioscan - Create consumer to receive export feedback message from RabbitMQ and update XP tube

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#3749]
**User story**
As PSD we need to create a consumer to receive the feedback messages from the Traction consumer via RabbitMQ and pass information back to the XP tube in SS/Limber (to indicate whether the export was done ok or not, and if successful some sort of traction id, and if not successful an error message).

**Who are the primary contacts for this story**
PSD

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] create consumer to receive the feedback message from the RabbitMQ queue
- [ ] modify deployment project to connect up consumer and message queue
- [ ] message format to be defined via Avro schema
- [ ] update the XP tube metadata in SS to set values that can be displayed in SS/Limber to indicate whether tube has been exported successfully and any error message

**Dependencies**
This story is blocked by the following dependencies:
- Avro message format (issue?)
- Queue for feedback messages (issue?)

References
This story has a non-blocking relationship with:
- Avro message format (issue?)
- Queue for feedback messages (issue?)
- Limber tube view changes (issue?)
- Sequencescape tube view changes if needed (issue?)

**Additional context**
Minimal information to return in feedback message may be: source XP tube barcode, success or failure, error message(s).
Consider how best to store / display this information in Limber and Sequencescape. Simplest may be to write comments on the XP tube labware.

**Comment by harrietc52** [comment]
Deprioritised in [DPL-694](https://github.com/sanger/General-Backlog-Items/issues/280)
