### ISSUE TITLE
DPL-680 Research: Upgrade Sequencescape to latest version of Ruby(3.0)

### ISSUE THREAD

**Issue by Sangeetha-Bheeman** [sanger/sequencescape#3752]
**User story**
Upgrade Sequencescape to the latest stable version of Ruby(3.0)

Ruby 2.7 went end of life in March 2023

**Who are the primary contacts for this story**
e.g. PSD (don't include surnames in public repos)

**Who is the nominated tester for UAT**
e.g. PSD (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] All the existing functionalities should work seamlessly
- [ ] All the tests should pass

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by SujitDey2022** [comment]
@TWJW-SANGER moving this story back to Non-Func Backlog for your review based on our previous discussion.

**Comment by stevieing** [comment]
When you run the CI the cucumber tests are failing because they do not find the correct database which should be 'cucumber' not 'test'
