### ISSUE TITLE
DPL-682 Provide a mapping between qc_results and compound_samples in mlwarehouse for Cardinal Project

### ISSUE THREAD

**Issue by yoldas** [sanger/sequencescape#3755]
**User story**
A component sample can be used for multiple compound samples. The mlwarehouse.qc_results table repeats counts for the same component when that component is used for multiple compounds. mo11 needs to relate compound_sample_id_tmp with id_qc_result_tmp (or id_pool_lims) to find which QC metric belongs to which compound sample.

**Who are the primary contacts for this story**
mo11
nts
ay6

**Who is the nominated tester for UAT**
mo11
nts
ay6

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Map qc_result rows to compound samples using a join table in mlwarehouse (see suggested solutions)
- [ ] Map qc_results rows to compound samples (or message only) in sequencescape

**Solution 1**
New relation: psd_sample_compounds_qc_results(compound_id_sample_tmp, id_qc_result_tmp)

Given that the following query
~~~~sql
SELECT * FROM mlwarehouse.psd_sample_compounds_components WHERE component_id_sample_tmp = 8380396;
~~~~
returns the following result

id | compound_id_sample_tmp | component_id_sample_tmp | last_updated | recorded_at
 --- | --- | --- | --- | --- |
4207 | 8418270 | 8380396 | "2022-10-13 12:22:13" | "2022-10-13 12:22:13"
4225 | 8418272 | 8380396 | "2022-10-13 12:22:13" | "2022-10-13 12:22:13"

and given that the following query
~~~~sql
SELECT * FROM mlwarehouse.qc_result WHERE id_sample_tmp = 8380396 AND qc_type = 'live_cell_count';
~~~~

returns the following result

id_qc_result_tmp | id_sample_tmp | id_qc_result_lims | id_lims | id_pool_lims | id_library_lims | labware_purpose | assay | value | units | cv | qc_type | date_created | last_updated | recorded_at
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
18603948 | 8380396 | 18178064 | SQSCP | SQPP-2744-H:D5 | NULL | "LCA PBMC" | "Cardinal_PBMC_Count v1.0" | 712000 | cells/ml | NULL | live_cell_count | "2022-09-14 11:24:17" | "2022-09-14 11:24:17" | "2022-09-14 11:24:18"
18605783 | 8380396 | 18179936 | SQSCP | SQPP-2829-L:F7 | NULL | "LCA PBMC" | "Cardinal_PBMC_Count v1.0" | 944000 | cells/ml | NULL | live_cell_count | "2022-09-15 12:28:14" | "2022-09-15 12:28:14" | "2022-09-15 12:28:14"

the following query
~~~~sql
SELECT psd_sample_compounds_qc_results.compound_id_sample_tmp, qc_results.*
FROM qc_result JOIN psd_sample_compounds_qc_results ON psd_sample_compounds_qc_results.id_qc_result_tmp = qc_result.id_qc_result_tmp;
~~~~
should return the following result

compound_id_sample_tmp | id_qc_result_tmp | id_sample_tmp | id_qc_result_lims | id_lims | id_pool_lims | id_library_lims | labware_purpose | assay | value | units | cv | qc_type | date_created | last_updated | recorded_at
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
8418270  | 18603948 | 8380396 | 18178064 | SQSCP | SQPP-2744-H:D5 | NULL | "LCA PBMC" | "Cardinal_PBMC_Count v1.0" | 712000 | cells/ml | NULL | live_cell_count | "2022-09-14 11:24:17" | "2022-09-14 11:24:17" | "2022-09-14 11:24:18"
8418272  | 18605783 | 8380396 | 18179936 | SQSCP | SQPP-2829-L:F7 | NULL | "LCA PBMC" | "Cardinal_PBMC_Count v1.0" | 944000 | cells/ml | NULL | live_cell_count | "2022-09-15 12:28:14" | "2022-09-15 12:28:14" | "2022-09-15 12:28:14"

**Solution 2**
New relation: psd_sample_compounds_qc_results(compound_id_sample_tmp, id_pool_lims)

Given the same preconditions in Solution 1, the following query
~~~~sql
SELECT psd_sample_compounds_qc_results.compound_id_sample_tmp, qc_results.*
FROM qc_result JOIN psd_sample_compounds_qc_results ON psd_sample_compounds_qc_results.id_pool_lims = qc_result.id_pool_lims;
~~~~
should return the same result.

**Dependencies**
This story is blocked by the following dependencies:

References
This story has a non-blocking relationship with:
- #3740 

**Additional context**

**Comment by stevieing** [comment]
Cardinal project is done / completed.
