### ISSUE TITLE
DPL-739 As SSM (Richard R) I would like the new NovaSeqX sequencing machine to have its own 'Inbox' so that the team can track work submitted.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#3788]
**User story**
As SSM (Richard R) I would like the new NovaSeqX sequencing machine to have its own 'Inbox' so that the team can track work submitted.

**Who are the primary contacts for this story**
Rich R
Tris B
Liz C

**Who is the nominated tester for UAT**
Tris B
Liz C

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] There should be a page for the NovaSeqX equivalent to the one at /pipelines/51 for NovaSeq 6000's

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/General-Backlog-Items/issues/287

**Additional context**
It is likely that completing [DPL-711](https://github.com/sanger/General-Backlog-Items/issues/287) will give this feature for free - however this story exists to check that happens, make any modifications needed and test the 'Inbox' functionality works as expected.

**Comment by emrojo** [comment]
Done as part of https://github.com/sanger/General-Backlog-Items/issues/287
