### ISSUE TITLE
DPL-809 Import fresh blood samples into Sequencescape

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3849]
**User story**
As a member of the BioResource team, I would like to be able to enter samples into Sequencescape for transfer of fresh blood samples to SeqOps for the 007c project.

**Who are the primary contacts for this story**
Laura L, Katy

**Who is the nominated tester for UAT**
Laura L

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] New manifest ("scRNA Core") which is identical to the Cardinal manifest, except that it also includes a column for donor_id (donor_id is needed because you want to avoid pooling 2 different samples from the same donor together for sequencing)
- [x] Make a start on a documentation page similar to this one, which was made for Cardinal: https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cardinal+Pipeline+Documentation (the "Importing samples into Sequencescape" section is relevant to this story)
See confluence here [scRNA Core Pipeline](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/scRNA+Core+Pipeline+Documentation)

**Additional Context**
Documentation explaining how the manifest is used for Cardinal: https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Cardinal+Pipeline+Documentation#CardinalPipelineDocumentation-ImportingsamplesintoSequencescape

Existing Cardinal manifest screenshots, in case they're helpful:

![Screenshot 2023-07-03 at 11 06 28](https://github.com/sanger/limber/assets/10407809/f2a96b72-d4fc-45e7-a417-5204603649d6)
---
<img width="674" alt="Screenshot 2023-07-03 at 11 11 04" src="https://github.com/sanger/limber/assets/10407809/2f2d7af4-548e-4cdb-8810-3be4a7f70c53">

**Comment by LauraLetchford** [comment]
Might be worth specifying that this is for getting blood samples in to the pipeline for isolating PBMCs and banking (as opposed to getting PBMCs into the later part of the pipeline). 
We need to work out whether the 'Supplier' and 'Collected By' fields work for the other projects expected to run through this pipeline as those were designed around Cardinal which had two overarching 'suppliers' and multiple sites per 'supplier' which we entered into collected by.

**Comment by KatyTaylor** [comment]
Update from meeting yesterday:
- Confirmed donor_id is needed, because they want to avoid pooling 2 different samples from the same donor together for sequencing - there will probably be a requirement around this in a later stage.
- Decided to use "Collected by" to record the collection site, as in Cardinal, although this information will not be used in an automatic pooling decision, as there's not the same requirement as in Cardinal to have a spread of collection sites pooled together. However, the information will be available and it was thought best to record it at this stage. Would be useful when the data is handed back to the BioResource team.
- There will need to be a discussion around what to record as the "Supplier" - probably just the same value for all manifests in this project, but needs to be decided and added to the system (by a user). Doesn't affect the LIMS development.
- Supplier sample name - not sure it was decided what to record in here, whether the vacutainer tube barcode as in Cardinal or a different identifier. Doesn't affect the LIMS development but should be decided upfront for clarity for the users.
- All fields should be kept mandatory, as in Cardinal.

**Comment by Lesley84** [comment]
In the latest scenario, the samples will go directly to HumGen and the aliquots for sequencing produced by them and passed onto SeqOps. As Katy has mentioned over email do we need to enhance this story to capture this piece (container type, barcodes etc.) or will it be a separate story?

**Comment by KatyTaylor** [comment]
@Lesley84 Good question, not sure! If we're still in Limber for both of those points, I guess we can add the feature during the transfer in Limber, so that it's specific to the pipeline. I don't suppose we can make it a universal feature like the tag clash detection, because the rules might be different for different pipelines?

**Comment by andrewsparkes** [comment]
N.B. donor_id is an existing manifest column, and not currently set as mandatory. No validation on it either.
So you can create a new column cardinal_donor_id which is a copy of donor_id and add the mandatory setting.
```
conditional_formattings:
    empty_mandatory_cell:
```
N.B. learnt from Bioscan the hard way that the manifest definition defines only what columns get created in an empty manifest download, they are NOT used on upload. Only the column heading in the uploaded file is used, so column heading text MUST be unique for the upload to match against the intended column definition. You cannot have 2 column definitions with heading 'DONOR ID' (or you can but it will validate against one of them uncontrolled and with Bioscan we suddenly broke other pipeline manifest uploads by forcing extra validations by re-using 'SUPPLIER NAME' and 'CONTROL TYPE' headings). So maybe 'SINGLE CELL DONOR ID' or something.

**Comment by andrewsparkes** [comment]
For the donor_id clash detection at pooling maybe this validation can be added on the labware creator(s) or JS that does the pooling? Make 007-specific versions of those pooling labware creators / JS and add the donor_id validation step in there.
e.g. When pooling tubes together it's JS for tag clash detection: as you scan each tube in it just builds up a total list of tags and on each new scan looks for matches with that list, so might be relatively easy to add an extra list and validation on donor_id in a 007 specific copy of the JS.

**Comment by KatyTaylor** [comment]
@andrewsparkes replied in Slack but summary...
I suggest:
a) new column with heading DONOR ID (required) - so it can be re-used by other manifests in future
b) new Collected By column specific to this manifest - we will have to ask Lesley or Laura what the dropdown values should be

And yes, I think the donor id clash detection will be in Limber so sounds OK.

Thanks

**Comment by Lesley84** [comment]
@LauraLetchford are you able to provide suggestions on the dropdown values for the Collected By column in the manifest?
