### ISSUE TITLE
DPL-820	BIOSCAN: Printing multiple tag barcode labels

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3853]
As R&D (Scott T, Emma B), we would like the ability to print multiple barcodes from Sequencescape in order to support the printing of a full set of 24x384-well tag plate batches for BIOSCAN.   

Who are the primary contacts for this work

Scott T (R&D)
Emma B (R&D)

Acceptance Criteria

To be considered successful the service must:

Allow a choice of individual label printers
Have a selectable number of labels to print for each labware
Provide an input for the user to provide a list of barcodes
Have a ‘print’ button

Background
The BIOSCAN process requires the generation and printing of tag plate batches that are comprised of 24x384-well format plates with unique tag combinations.

Multiple tag plate batches may be created on a single day.

Currently the only option to print barcodes for these tag plate batches is for users to navigate to the Sequencescape page for each individual tag plate and print from there. This is a laborious process, which is prone to error, when the user is processing multiple plates.

We would like to implement a more robust solution with an improved user experience.

Supplemental information

This feature in Sequencescape may have applications more broadly and could benefit other pipelines.

**Comment by SujitDey2022** [comment]
Discussed this with @stevieing and closing this as 'not planned' as the platform requirement moved from Sequencescape to Limber LIMS
