### ISSUE TITLE
DPL-835 GSLP: Add new BB barcode format

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3859]
As GSLP we have started receiving unconsolidated positive/negative plates from the Brants Bridge Lighthouse lab.

Once we cherrypick out the positives via our standard Heron cherrypicking method, we want them to fit into our deep-well>shallow-well stamping pipeline.

They have a different barcode format than those currently accepted by our LIMS:

"nnnnnnnDWP"

That is, 7 digits proceeded by DWP.

All future plates of this type that will be sent by this lab should follow this one barcode format.

Would it be possible to programme this into LIMS, so that PlateGenie can import them into SequenceScape?

In addition, do you anticipate any issues importing the plates after first cherrypicking them via our standard method?

We have 6 plates so far we want to import:
0001054DWP
0001065DWP
0001058DWP
0001057DWP
0000045DWP
0000050DWP

Who are the primary contacts for this story
Michael  (mf17)

relates to [RT783628](https://rt.sanger.ac.uk/Ticket/Display.html?id=783628)

**Comment by sdjmchattie** [comment]
I've sent a message to Michael via the RT system asking that he check that this is now working as expected in UAT.
