### ISSUE TITLE
DPL-872 Ability to create a semi-auto 10X submission using the HT library types

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/sequencescape#3883]
**User story**
As an SSR (Clare C.) I would like to create new sample submissions for the 10x submissions using HT library types.

Notes:
HT libraries will need to be processed manually. This impacts the numbers that can be processed in each batch, and larger numbers will need considerable extra lab time and staff.

Libraries are due to start arriving in September 2023.

**Who are the primary contacts for this story**
Liz H.
Clare C.

**Who is the nominated tester for UAT**
Liz H.
Clare C.

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] New library types made available for 'Limber-Bespoke - Chromium - NovaSeq 6000 Paired end sequencing' template when creating bulk/single submissions
- [ ] New library types
- Chromium single cell 3 prime HT v3
- Chromium single cell 5 prime HT v2
- Chromium single cell BCR HT
- Chromium single cell TCR HT
 

**Dependencies**
This story is blocked by the following dependencies:
n/a

References
This story has a non-blocking relationship with:
n/a

**Additional context**
n/a

**Comment by emrojo** [comment]
Issue solved. Awaiting for new round of UAT.

**Comment by SujitDey2022** [comment]
Removing the 'Time Sensitive' flag until indicated about the new timelines from the SSRs
