### ISSUE TITLE
DPL-873 Ability to make a manual 10X submission with different numbers of GEX, TCR and BCR libraries

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/sequencescape#3884]
**User story**
As an SSR (Liz H.) I would like to be able to make manual 10X submissions with different numbers of GEX, TCR, and BCR libraries.

Note:

Need to investigate Limber, as currently, Limber does not allow for bulk/single submissions 'Limber-Bespoke - PCR - NovaSeq 6000 Paired end sequencing' with a mix of different library types

**Who are the primary contacts for this story**
Liz H.
Clare C.

**Who is the nominated tester for UAT**
Liz H.
Clare C.

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] submission with different library types are processed in Limber
- [x] create new labware creator to allow for partial submissions of wells and to compress child wells to top left
- [x] add tests to the integration suite

**Dependencies**
This story is blocked by the following dependencies:
n/a

References
This story has a non-blocking relationship with:
n/a

**Additional context**
Relates to [RT786014](https://rt.sanger.ac.uk/Ticket/Display.html?id=786014)

**Comment by SujitDey2022** [comment]
@Sangeetha-Bheeman  added the new user story for your review and further refinement.

@TWJW-SANGER fyi...

**Comment by Sangeetha-Bheeman** [comment]
After today's meeting with Andrew, John and Matt, we need to be able to create LBB Enriched BCR and TCR plates from LBC Cherrypick plates which is failing currently. 

As mentioned by John,
"we just want the compression, as we do not dilute going into the enrichment, we just take 2uL as standard and place that into 98 uL of Amplification mix - we then dilute going from the enrichment into the library prep aiming for a concentration of 50 ng in 20 uL"


<img width="607" alt="image" src="https://github.com/sanger/sequencescape/assets/93536758/9f38a9dc-5545-4df5-9b63-cb1b5a7dec2b">

**Comment by Sangeetha-Bheeman** [comment]
Added the integration suite tests here - https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/commit/83fc518b657a62ff146c993814745716f8d6b125

**Comment by SujitDey2022** [comment]
Discussed this with Liz C. with respect to identifying if the requirements mentioned here replicate the work expected to be done for the 007c scRNA project. Awaiting further response from the SSR Team.

**Comment by SujitDey2022** [comment]
![image](https://github.com/sanger/sequencescape/assets/115623404/b3d24dcd-8d81-4edb-9154-9cb043411ede)

**Comment by andrewsparkes** [comment]
@SujitDey2022 
Not clear why this story is back in To Do when it says above there's a PR and integration test.
Did they not work? Did the requirements change?

**Comment by yoldas** [comment]
Added steps for creation of LBB Enriched BCR and LBB Enriched TCR plates to the integration suite. The merge request is at https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/108 .
