### ISSUE TITLE
DPL-896 For Targeted Nanoseq Pipeline - Merge Data from the following data sets: Input amount file, Hamilton driver file, PCR XP concentration file

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/sequencescape#3896]
**User story**

As a Short Read Team User, I want to be able to download a merged file following the Library Prep process containing sample details received from the Sample Input Amount File from the faculty group (CASM), PCR XP Concentration File (Limber LIMS), and PCR XP Plate Data from Sequencescape LIMS SO THAT we can use the merged data in the sample 'rearray' template required for the ISC process.

This is a completely manual process that requires Short Read Targeted Nanonseq Team to collavborate with the SSRs to be able to merge data from various source files and Sequencescape LIMS so as to allow for the merged data to be fed into the 'rearray' template that includes the pooling plan. Each single merged file corresponds to a single 96-well sample plate and the manual efforts can vary from 2-to-40 sample plates requiring 1-2 FTEs every week.

Current Manual Process:

1. Receive the Sample Input Amount File from the faculty (CASM) SSR (Siobhan)
- SSR sends a pre-populated file template received from the Targeted Nanonseq Team to the faculty for providing the requested details.
Example: [SQPP-30689-M_TNano_AL Lib_qPCRconc_310823.csv](https://github.com/sanger/sequencescape/files/12585517/SQPP-30689-M_TNano_AL.Lib_qPCRconc_310823.csv)

2. Download the concentration .csv file for custom pooling from Limber
- Example: Limber SQPP-22955-O : https://limber.psd.sanger.ac.uk/limber_plates/186d9fd4-0b6a-11ee-9148-fa163eac3af7
3. Ctrl+A the Plate data from Sequencescape
- Example: Sequencescape SQPP-22955-O : https://sequencescape.psd.sanger.ac.uk/labware/27502701
4. Merge all the data mentioned in points 1-to-3 above
- Attached is a sample of the merged file created manually - 
[Copy of SQPP-20828-A_Merged file_150623.xlsx](https://github.com/sanger/sequencescape/files/12574993/Copy.of.SQPP-20828-A_Merged.file_150623.xlsx)

In addition to this, below is an overview of the approx. monthly demand forecast,

LIBRARIES | Duplex/Targeted Nanoseq Samples | Approx. No. of 96 Well Plates
-- | -- | --
Aug-23 | 241 | 2
Sep-23 | 193 | 2
Oct-23 | 145 | 1
Nov-23 | 905 | 9
Dec-23 | 804 | 8
Jan-24 | 804 | 8
Feb-24 | 2201 | 22
Mar-24 | 1397 | 14
Apr-24 | 1397 | 14
May-24 | 1397 | 14
Jun-24 | 0 | 0
Jul-24 | 0 | 0

**Who are the primary contacts for this story**
Sara W.
Maria M.

**Who is the nominated tester for UAT**
Sara W.
Maria M.

**Acceptance criteria**
To be considered successful:
- [x] Need to identify if the data from the source files can be fetched to generate the merged file
- [x] Identify if the manual input data received as part of the Sample Input Amount file provided by SSR can be automated or entered/saved in LIMS
- [x] Create new user stories for the implementation work required to provide a solution for this process.

**References**
Sample of an existing merged file for the incoming sample requests,

[Copy of SQPP-20828-A_Merged file_150623.xlsx](https://github.com/sanger/sequencescape/files/12574993/Copy.of.SQPP-20828-A_Merged.file_150623.xlsx)

**Additional context**

**Comment by andrewsparkes** [comment]
Thoughts on the data required:
- Where does the 'concentration' value come from in step 1? Is that a QC concentration from the PCR XP plate, i.e. is it the same concentration being downloaded from Limber in step 2? 
- Where does the 'input amount available' value come from? Is it calculated? If so how?
- What exactly is being copied from the plate page in Sequencescape in step 3? Is it the Sample Name and Sanger Sample Id for each well? But they are already in the file in step 1.
- How is the 'Input amount desired' calculated? 
- And the sample and diluent volumes?
- Where does the Hyb Panel come from? Is it always the same i.e. hardcoded, or is it a variable choice? Do we track Hyb panels in LIMS or is this a string value?

Columns in merge file:
Well e.g. A1 - well of plate - from Sequencescape
Concentration (nM) e.g. 20 - concentration of well - from QC data in Sequencescape?
Sanger Sample ID e.g. 1234STDY12345678 - from Sequencescape
Supplier Sample Name e.g. PD12345b_tds0001 - from Sequencescape
Input amount available (fmol) - ?
Input amount desired - ?
Sample volume - ?
Diluent volume - calculated from sample volume
Hyb Panel (string) - ?
