### ISSUE TITLE
DPL-904 BIOSCAN manifest interim supplier sample name approach

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3898]
As R&D (Scott T) I would like to identify a method to automate the supplier sample name prefix addition to the existing BIOSCAN manifests as it takes a considerable amount of time for faculty staff to generate and validate these prefixes in the current system.

Who are the primary contacts for this story
Scott T (R&D)
Emma B (R&D)
Jemma S (BIOSCAN faculty)

Knowledge or Stake holders
Jemma S (BIOSCAN faculty)
Mara L (BIOSCAN faculty)
Alex M (BIOSCAN faculty)

Acceptance Criteria
In order to be successful, this story should:

Identify an interim approach to ‘automating’ supplier sample name prefix addition
This could be entirely LIMS driven
This could leverage Excel formulas to perform the prefix addition and LIMS to validate
Other approach
Identify a method that applies the same naming convention currently applied manually
Designated lysate negative control type  = lysate negative  : supplier sample name set to CONTROL_NEG_LYSATE_<Sanger plate ID>_<Well>
PCR negative control type  = pcr negative : supplier sample name set to CONTROL_NEG_<Sanger plate ID>_<Well>
PCR positive control type  = pcr positive : supplier sample name set to CONTROL_POS_<Sanger plate ID>_<Well>
Empty well control type   = null AND (TAXON_ID = 2582415 OR common name = blank sample) : supplier sample name set toCONTROL_NEG_LYSATE_<Sanger plate ID>_<Well>
Sample control type   = null AND (TAXON_ID = 32644 OR common name = unidentified): supplier sample name set to <Sanger plate ID>_<Well>
Require the user to input the minimal amount of sample information.
Ideally this would be limited to:
              - Sanger Plate ID
              - Taxon ID
              - Control Type
              - Sanger Sample ID

Identify a method to validate the resulting manifest
Estimate the time taken to develop the identified approach in order that it can be effort and value can be weighed against a longer term solution (User Story: BIOSCAN automated manifest generation and submission)

Additional context or information

This feature has been requested as the current method  of sample manifest submission requires a considerable amount of manual editing to apply the necessary prefixes to supplier sample names for the control information in mBRAVE to be informative.

For completeness I have attached an email chain which contains the original request from BIOSCAN faculty. They have asked for this functionality since in other forums.

**Comment by neilsycamore** [comment]
On 31 Aug 2023, at 11:27, Emma Betteridge <[eb13@sanger.ac.uk](mailto:eb13@sanger.ac.uk)> wrote:
Hi all,
We had a BIOSCAN working group on Tuesday and discussed that it would be useful to have a short guide on BIOSCAN controls with particular emphasis on how to annotate these on sample manifests.
I’ve had a go at putting this together here - https://docs.google.com/document/d/1xfuXNLpUL4WIPuZtnq8UCt3WD71IQL4HR9BNmr-sp64/edit

I have based this on what we agreed during for the batch_7 manifest. Please add comments if you feel something is not correct or missing.
Jemma and Mara, please let me know if this covers everything you would like to have documented or if there is other information you would like included.
Thanks,
Emma

**Comment by neilsycamore** [comment]
Hi Scott, 
With Emma on leave, perhaps you can enlighten us. We are wondering about the process to add CONTROL_NEG_RANDOM to the prefix of the Well ID for any randomised negative control added by the Beckman. Alex is working on implementing addition of the required prefixes to CONTROL_POS to H12 and CONTROL_NEG_LYS to G12 wells and just wondered why this couldn’t be done alongside the addition of the randomised naming.

We can do it of course but wondering if it is more efficient and future proof to do it at the stage of specimen extractions?
Thoughts?
Best
Mara

**Comment by neilsycamore** [comment]
Hi Scott, 

Thank you for the clarifications! Based on this I understand that we only need to add CONTROL_NEG_LYSATE_ prefix to ‘supplier sample name’ for empty wells on our side. If this is correct, I can see a potential issue with well G12 - in some older plates this well can contain real sample, while in newer plates it should be empty. How should we label the sample in each of those cases?

Also, just to see if we can simplify the process a bit: on our side, we are using different taxonomy for real samples and blanks when filling in the SequenceScape manifest:

- real samples are submitted as 'unidentified', TAXON_ID 32644
- blank samples are submitted as 'blank sample', TAXON_ID 2582415

Would it be possible to use this information from SequenceScape manifest to apply all of the prefixes on your side? I.e:

- CONTROL_NEG_LYSATE - anything with COMMON_NAME as 'blank sample' / TAXON_ID 2582415, with the exceptions below:
- CONTROL_POS - well G12 (only if it was blank? or in any case?)
- CONTROL_NEG - randomised control introduced by the robot (only if the original sample was not blank)
Let me know what you think.
Alex

**Comment by TWJW-SANGER** [comment]
From Scott T:
Faculty are happy to drop this request as it was an interim solution to aid in manifest submission. They have subsequently made their own scripts to help automate the task, making this story redundant.

Closing and archiving.

**Comment by SujitDey2022** [comment]
@TWJW-SANGER @andrewsparkes @KatyTaylor moving this to Done column based on above comments.
