### ISSUE TITLE
DPL-913 Submit banked PBMC tubes for cDNA prep

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3900]
**User story**
As an SSR, I would like to be able to submit a collection of tubes containing banked PBMCs for cDNA prep, as part of the "scRNA Core" pipeline. 

**Who are the primary contacts for this story**
Katy, Lesley, Abby, Liz H

**Who is the nominated tester for UAT**
Abby, Liz H

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] I can submit "LRC Bank Seq" and "LRC Bank Spare" tubes for donor pooling and cDNA prep (the two stages of the pipeline in one go).
- [x] Request types are 'limber_scrna_core_donor_pooling' and 'limber_scrna_core_cDNA_prep' (in that order).
- [x] Library type is specified as 'Chromium single cell 5 prime HT v2'
- [x] Update / create new Integration Suite test to include this submission
- [x] Update [documentation](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/scRNA+Core+Pipeline+Documentation), to say relevant submission templates, library types etc.

**Additional Information**
We will use the HT library types added for 'bespoke' activities in https://github.com/sanger/sequencescape/issues/3883:

- Chromium single cell 3 prime HT v3
- Chromium single cell 5 prime HT v2 (just this one to begin with)
- Chromium single cell BCR HT
- Chromium single cell TCR HT

**Comment by Lesley84** [comment]
1) How will the communication happen here? e.g. When they determine there are enough banked cells in storage to go down the pipeline, BioResource team create an RT ticket for the SSR, listing out the tubes? **To be determined for the SSRs and BioResource**

2) Who knows / how do they know which cost code (Sequencescape "Project") is relevant for each tube? (Study should be known as it was specified on the manifest, when the samples were first uploaded prior to cell extraction). **To be determined for the SSRs and BioResource**

3) OK if this is a normal "manual" submission, managed by SSRs? **To be determined for the SSRs and BioResource**

4) Should the submission be just for the thawing step (before the 2nd entry point to the pipeline), or for the whole of the cDNA preparation step? Needs stakeholder and dev agreement. Considerations: what chunks billing will happen in; whether pool plates from SeqOps-banked cells will ever be combined with pool plates from faculty. **If there is just one submission and the cell count is poor post-thawing and as a consequence, it doesn't move forward for cDNA prep will the customer still be billed for cDNA prep (assuming contingency also fails)? Also, how would this look if we had to use contingency samples? Can we discuss combining with SeqOps and faculty plates when we meet on Monday it will be useful to have the process map alongside and there are multiple considerations. The risk of cross-study swaps is high.** 

5) Should it have a "library type"? Assume no, as we are not creating "libraries". Library type will come in in the next submission - when enters the existing 5' Chromium pipeline. **There are alternative protocols for cDNA prep which will need to be defined here. e.g. 5' or 3' for example**

How should we refer to the "middle" section of the pipeline - is "cDNA prep" OK? (as opposed to the first section, "cell extraction", and the final section, "library prep" or currently "Bespoke Chromium 5 prime") **'cDNA prep' is fine**

**Comment by KatyTaylor** [comment]
More thoughts on q4 above:
- As I understand it, whether the submission covers both thawing and cDNA prep, or whether there is a submission for each of those steps, shouldn't impact the billing report. The report is based on what gets recorded as sequenced (iseq_flowcell table in the MLWH) - so if wells are failed, they shouldn't be recorded as sequenced, so won't be in the billing report.
- Whether we are going to represent a pool as a compound sample (DPL-916) may impact both the billing report, and this decision about number of submissions.

**Comment by KatyTaylor** [comment]
Notes from meeting yesterday:

Library types:
- Library type - agreed makes sense to create some scRNA-specific versions of the 10X library types, so that the scRNA data can be distinguished from the existing 10X data. Can use the same library type for the cDNA prep stage as for the library prep stage. Discussed adding 'HT' to the library type name, and that 'HT' versions are already being created for the existing pipeline in this story: https://github.com/sanger/sequencescape/issues/3883. 
- Need to clarify exactly what library types we'll need. Suggest to start off with we could just have "scRNA Chromium single cell 5 prime HT" or similar. (above linked story includes 'v2' in the name - ask why)

Submissions / selecting samples to go onto the 10X chip together:
- Also see related comment here - https://github.com/sanger/limber/issues/1388#issuecomment-1764736960
- Still lots of uncertainty around this.
- BioResource team are managing the banked PBMC tubes. Once there are enough tubes available, a group of 100-160 banked PBMC tubes, destined for the same 10X chip, will be taken out of the freezer together.
- Faculty will be sending plates of ready-pooled PBMCs to SeqOps, ready to go on the 10X chip.
- It's possible faculty and SeqOps pool plates could be combined onto one chip - could lower costs, but it complicates things (from LIMS point of view, and also from lab point of view, managing tags).
- If the above happens, how are the faculty plates coming in coordinated with the tubes being taken out of the freezer?
- Discussed possibility of enforcing separate processing of samples from different entry points, at least for MVP.
- Discussed whether this submission could specify which samples would end up being pooled together for sequencing. Only if a) they consider the donor id, to prevent 2 samples from the same donor being pooled together, and b) if they are not combined with plates coming in at either the 2nd or 3rd entry points.
- Another point at which sequencing pools could be specified is the submission for library prep (aligning with 3rd entry point).
- Trade off between more admin and more flexibility. Could be max number of submission points:
    1. Fresh blood for cell extraction (automated submission)
    2. Frozen PBMCs for thawing and pooling (manual submission)
    3. Pool plates for cDNA prep (manual submission)
    4. cDNA for library prep (manual submission)
    5. Tubes for sequencing (manual submission)

**Comment by KatyTaylor** [comment]
In meeting 25/10/23 with R&D we discussed library types. Decision confirmed by Lesley today:

> These library types are the best placed to align with the 007C project. As discussed previously, in the early days of the project there will be cross-over with what were bespoke activities and 007C until the point at which they are aligned. However, in the interim we can filter by date and/or study.
>
> Chromium single cell 5 prime HT v2 will the library type we immediately require for 007C.
>
> - Chromium single cell 3 prime HT v3
> - Chromium single cell 5 prime HT v2
> - Chromium single cell BCR HT
> - Chromium single cell TCR HT

**Comment by yoldas** [comment]
Added Integration Suite [DPL-913 MR](https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/116) on GitLab .

**Comment by yoldas** [comment]
Updated the documentation with the [Submitting banked PBMC tubes for Donor Pooling and cDNA Prep](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/scRNA+Core+Pipeline+Documentation#scRNACorePipelineDocumentation-SubmittingbankedPBMCtubesforDonorPoolingandcDNAPrep) section.

**Comment by yoldas** [comment]
Gist: [Running integration suite locally for the 'scRNA Core entry point 1 - blood' scenario](https://gist.githubusercontent.com/yoldas/a705887279fccd472320d8bb7fee2964/raw/d8aeab031e021e5c804d5c7a15a304e387eb0db4/running_integration_suite_locally_for_scrna_cdna_prep_blood.txt)

**Comment by yoldas** [comment]
Gist: [Database Inspection for Donor Pooling and cDNA Prep submission](https://gist.github.com/yoldas/d4e8b2202810afc4ddb0b3d13269b22c)

**Comment by yoldas** [comment]
Deployment note: To enable WIP when we deploy Sequencescape to UAT, we need the following executed on the host:

`WIP=011_scrna_core_cdna_prep_submission_templates,014_limber_scrna_core_cdna_prep_request_types,011_scrna_core_cdna_prep_plate_purposes,008_scrna_core_cdna_prep_tube_purposes,011_scrna_core_catalogue bundle exec rake record_loader:all`
