### ISSUE TITLE
DPL-917 Submit plate of PBMC pools for cDNA prep

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3901]
**User story**
As an SSR, I would like to be able to submit a plate of pooled PBMCs for cDNA prep, as part of the scRNA Core pipeline. 

**Who are the primary contacts for this story**
Katy, Lesley, Abby

**Who is the nominated tester for UAT**
Lesley, Abby, SSR

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] PBMC pool plates imported from faculty (output of DPL-823) can be submitted to the cDNA prep part of the scRNA Core pipeline (request type limber_scrna_core_cDNA_prep)
- [x] Update / create new Integration Suite test to include this submission.
- [x] Update [documentation](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/scRNA+Core+Pipeline+Documentation), to say relevant submission templates, library types etc.

**References**
This story has a non-blocking relationship with:
- https://github.com/sanger/sequencescape/issues/3857
- https://github.com/sanger/sequencescape/issues/3900

**Additional context**
This is the second entrypoint into the pipeline - these plates are coming straight from faculty, rather than having being taken through the scRNA Core Cell Extraction pipeline in SeqOps.

**Comment by andrewsparkes** [comment]
Gitlab branch for 917 also made
