### ISSUE TITLE
DPL-944 JS banner not being displayed

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3915]
As an SSR (Liz C) I am using the “request additional sequencing” button, however every time I put in the information and click “create”, the page just reloads and doesn’t make the request. 
(nts) This is because the study the did not have the correct accessioning profile and should be displaying a JS banner informing the user that the study OR sample required accessioning

**RT Ticket Number**
[RT789966](https://rt.sanger.ac.uk/Ticket/Display.html?id=789966)

**Comment by yoldas** [comment]
It should not allow requesting additional sequencing when the study data release strategy is open and data release timing is standard, without an accession number. It is not triggering validations and going on with creating the requests. The problem is not only showing the banner it seems. However, it showed the validation banner and not allowed the request in both unit test and a manual test with copied production data.

![Screenshot 2023-11-15 at 16 19 48](https://github.com/sanger/sequencescape/assets/91894/3ecd28b4-a6ac-4b7c-9e6e-c38c67755245)

**Comment by yoldas** [comment]
The deployment projects sets `disable_accession_check: true` for training environment. This flag is set to true for all environments except production. I have set this configuration to false for training and deployed the fix again.

When the study has the data release strategy open and the data release timing is standard, requesting additional sequencing fails with validation errors and the request is rejected as expected.

<img width="1098" alt="Screenshot 2023-11-15 at 21 37 29" src="https://github.com/sanger/sequencescape/assets/91894/bc0bfc1e-10a8-4d1b-ae4f-55cbf8e1f923">

**Comment by yoldas** [comment]
There are three possible errors added in `check_data_release_and_accession_for_submission` method of `AccessionBehaviour`. 

The first one is for empty data release strategy and timing. If any of them is empty, `"#{study.name}: Please fill in the study data release information"` is shown. Although they are validated, it is not possible to produce this error by user as they are set using combo and radio boxes in the form for editing the study details.

The second is for missing accession number for a study. `"#{study.name} and all samples must have accession numbers"` is shown. This case is covered in the previous comment.

The third is for missing accession number for any of the samples that require accession. `"The following samples are missing accession numbers: #{unaccessioned_samples}"` is shown. I have set an ENA number for the study and tried requesting a new sequencing. A validation error is shown for the samples as expected.

<img width="1322" alt="Screenshot 2023-11-15 at 22 07 45" src="https://github.com/sanger/sequencescape/assets/91894/1ab135c2-3435-4a5a-8259-38b77f7c80cb">

**Comment by yoldas** [comment]
The tests above clearly show that the page banner now displays error messages to inform the user of issues when requesting additional sequencing after the bug-fix.
