### ISSUE TITLE
DPL-969 Support for "Chromium chip" labware

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3936]
**User story**
As a user of the scRNA Core cDNA Prep pipeline, I would like there to be a plate-like entity called a "Chromium Chip 16-well", which acts like a plate but with a different number / layout of wells.

**Who are the primary contacts for this story**
Katy, Andrew

**Who is the nominated tester for UAT**
Katy, Andrew (can get Lesley and Abby from R&D involved if seems useful, or wait until https://github.com/sanger/limber/issues/1392 is done)

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] A "Chromium Chip 16-well" has 16 wells: columns 1-8, and rows A & B.
- [x] A "Chromium Chip 16-well" created via the Rails console can be viewed in Sequencescape like I can view a plate, including the samples it contains, relationships with other labware, etc.
- [x] A "Chromium Chip 16-well" can be created and retrieved via the v2 Sequencescape API.
- [x] A "Chromium Chip 16-well" can be created and retrieved by Limber.
- [x] A "Chromium Chip 16-well" created via the Rails console can be viewed in Limber like I can view a plate, including the samples it contains, child labware, etc.
- [x] A "Chromium Chip 16-well" acts like a plate (catch-all, for features I haven't listed...)

**Additional context**
See helpful research branch from Andrew and Harry, which might be most of the work that is needed - https://github.com/sanger/sequencescape/compare/DPL-687-research

**Comment by yoldas** [comment]
I have set the LCA 10x cDNA purpose shape and size to ChromiumChip and 16, disabled a failing WellHelper method that computes well ranges.

### Parent

<img width="973" alt="limber-parent" src="https://github.com/sanger/sequencescape/assets/91894/b6908aa2-e504-4470-879a-83d3bd134c39">

### Limber pending

<img width="977" alt="limber-pending" src="https://github.com/sanger/sequencescape/assets/91894/b6cc3f39-e189-4bad-959e-92f002e63c8e">

### Limber passed

<img width="972" alt="limber-passed" src="https://github.com/sanger/sequencescape/assets/91894/49fd9071-0119-4d71-978f-35fb5ee185fd">

###SS plate

<img width="987" alt="ss-plate" src="https://github.com/sanger/sequencescape/assets/91894/af007876-726c-4288-b1e0-06e003dd6fa4">

### SS well

<img width="985" alt="ss-well" src="https://github.com/sanger/sequencescape/assets/91894/8d2b1e8e-fb19-4c5a-ac52-cdb1acd3fe85">

**Comment by yoldas** [comment]
I have also used [HTTP Toolkit](https://httptoolkit.com) to view the HTTP traffic between Limber and Sequencescape while running the integration suite. My attempts of using alternatives such as WireShark, Fiddler Everywhere, etc. were not successful for various reasons.

**Comment by yoldas** [comment]
We can have another iteration on this when we work on DPL-919 . 

At the moment asset_shape is not exposed as a relationship from plate_purpose. However, Limber might need this to avoid hardcoding values such as in WellHelper module. I suggest 
- changing the option name in Limber purpose config from 'asset_shape' to just 'shape' to avoid name clash 
- Purpose registration to use the shape to query the AssetShape resource
- Exposing asset_shape resource 
- Setting association in plate purpose resource to set up relationship.
