### ISSUE TITLE
DPL-1001 Research and refine BGE requirement tasks and efforts

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/sequencescape#3969]
**User story**
Possible scope of work discussed during team backlog refinement.

1. Create new BGE pipeline (setting up the new purposes & pipeline config in Limber, adding straight stamps instead of any new labware creators)
2. Integration Suite test for the above
3. Bed verifications for the above (copied from existing pipelines)
4. Allow blending of pool tubes from PCR Free and ISC arms & validate the pairing is correct
5. Ability to fail wells on both arms at once (Not MVP)

**Who are the primary contacts for this story**
Matthew M., Sara W.

**Who is the nominated tester for UAT**
e.g. John S (don't include surnames in public repos)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References

https://docs.google.com/presentation/d/1UvMcZhYmTwj2yqSXtp6Tv_d-s8hFX152OGH7_JF4Y7A/edit#slide=id.g292a0708915_0_150

**Additional context**

**Comment by BenTopping** [comment]
Closing as research is done. Will update with any comments from future meetings.
