### ISSUE TITLE
DPL-1002 Sample Prep - Ability to create working dilution from RNA stock plate

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/sequencescape#3970]
**User story**
As a User (Lynda) of the Sample Prep team, I WANT the ability to create working dilution from RNA Stock plates in Sequencescape LIMS AS currently there is no option to create one without executing workarounds in Sequencescape LIMS

Refer slides 3 and10-to-12 for details from the refinement sessions,
https://docs.google.com/presentation/d/1UvMcZhYmTwj2yqSXtp6Tv_d-s8hFX152OGH7_JF4Y7A/edit#slide=id.g29dcfe1fe66_0_35

Current workaround in Sequencescape LIMS:

1. Change plate purpose to stock
2. Create working dilution
3. Change plate purpose back to RNA stock

**Who are the primary contacts for this story**
Lynda D.

**Who is the nominated tester for UAT**
Lynda D.

**Acceptance criteria**
- [ ] Confirm if the user can create a working dilution directly from Stock RNA Plate without the need of changing plate purposes.

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

Execute the rake task in the project directory once after deployment:

`bundle exec rake support:add_stock_rna_plate_to_working_dilution_parents`

**Comment by yoldas** [comment]
I have updated the Additional context with the instruction for documenting deployment.

Execute the rake task in the project directory once after deployment:

`bundle exec rake support:add_stock_rna_plate_to_working_dilution_parents`
