### ISSUE TITLE
Y24-008 As PSD we would like to identify what services are using the v1 SequenceScape API so that we can start migrating clients away from it.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4042]
**Description**
As PSD we would like to identify what services are using the v1 SequenceScape API so that we can start migrating clients away from it.

**Who the primary contacts are for this work**
PSD

**Knowledge or Stake holders**
PSD

**Additional context or information**
We would like to fill in the table on the PSD Confluence Site under _Usage+of+SequenceScape+v1+API+-+2024_

By:
- [x] Look at Limber repo to identify any v1 endpoints and functionality being used.
- [x] Look at Traction repo to identify any v1 endpoints and functionality being used.
- [x] Look at Quant Hub repo to identify any v1 endpoints and functionality being used.
- [x] Look at GateKeeper repo to identify any v1 endpoints and functionality being used. 
- [x] Look at Wrangler repo to identify any v1 endpoints and functionality being used.
- [x] Look at CherryTrack repo to identify any v1 endpoints and functionality being used.
- [x] Look at PlateGenie / Lighthouse repo to identify any v1 endpoints and functionality being used.
- [x] Check Kibana / SS application logs to see if calls to the v1 API are logged clearly. If yes, see if you can identify any external IP's calling in, if no create a story to make the logging clear enough to be able to.

**Comment by stevieing** [comment]
@sdjmchattie Traction and Quanthub do not use any v1 endpoints.

**Comment by sdjmchattie** [comment]
Report is in https://ssg-confluence.internal.sanger.ac.uk/display/PSD/Usage+of+SequenceScape+v1+API+-+2024
