### ISSUE TITLE
Y24-012 Security related RT 798566

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4043]
**Describe the Housekeeping**
See security related RT 798566

**Comment by dasunpubudumal** [comment]
Dual Passwords for MySQL Documentation: MySQL:: [MySQL 8.3 Reference](https://dev.mysql.com/doc/refman/8.3/en/password-management.html#:~:text=passwords%20to%20it.-,Dual%20Password%20Support,MySQL%20servers%2C%20possibly%20involving%20replication.)

**Comment by dasunpubudumal** [comment]
The following procedure could be carried out for testing dual password feature (source referenced in https://github.com/sanger/sequencescape/issues/4043#issuecomment-2051656462) in a local MySQL 8.5 database.

**Note:** Creating the user and updating grants are not a part of this story. These steps are purely for completion purposes of the procedure.

1. Check the version of the database. 

```bash
mysql> SELECT VERSION();
+-----------+
| VERSION() |
+-----------+
| 8.3.0     |
+-----------+
1 row in set (0.01 sec)
```

2. Create new user `sample_user` with password `PASSWORD`.

```bash
mysql> CREATE USER 'sample_user'@'localhost' IDENTIFIED BY 'PASSWORD';
```

3. Check all users and privileges.

```bash
SELECT * FROM mysql.user;
```

This displays all users and privileges. The user `sample_user` has no privileges (i.e., privileges were not granted).

4. Grant privileges for `sample_user`.

```bash
mysql> GRANT ALL ON *.* TO 'sample_user'@'localhost' WITH GRANT OPTION;
Query OK, 0 rows affected (0.00 sec)
```

5. Attach a secondary password `PASSWORD_2` for user `sample_user`.

```bash
ALTER USER 'sample_user'@'localhost' 
IDENTIFIED BY 'PASSWORD_2' 
RETAIN CURRENT PASSWORD;
```

This attaches another password `PASSWORD_2` as the secondary password for the user account `sample_user`.

--- 

6. Log in using `PASSWORD_2` as the user's credential (i.e., the secondary password).

```bash
mysql -u sample_user -pPASSWORD_2;
```

7. Log in using `PASSWORD` as the user's credential (i.e., the primary password).

```bash
mysql -u sample_user -pPASSWORD;
```

8. Update the configurations of all consumer applications of the database.
9. Deploy the configurations to UAT environment, and check application's functionality.
10. Discard the old password.

```bash
ALTER USER 'sample_user'@'localhost'
  DISCARD OLD PASSWORD;
```

**Comment by dasunpubudumal** [comment]
Identified that the following applications use the host `psdp-db`:


Application | Database Name
-- | --
janitor | labwhere_production
samples_extraction | samples_extraction_production
asset_audits | process_tracking_production
labwhere | labwhere_production
print_my_barcode | print_my_barcode_production
sequencescape | sequencescape_production
sm_workflow | sm_workflow_lims_production
traction-service | traction_service_production

**Comment by dasunpubudumal** [comment]
`credentials` project was updated with the latest KeePassXC database.
