### ISSUE TITLE
Y24-058 [BUG] Study data release information - data clean up [Due 13/11/24]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#4084]
**Describe the bug**
During development of https://github.com/sanger/sequencescape/issues/4076, I found that many of the existing Studies in the Sequencescape database do not conform to the new validation rules.
Because of this, I deployed the new server-side validation for that story 'feature flagged off'. This story is to track the resolution of this. Ideally, we can 'fix' all the existing studies, so that they pass the new validation, and then remove the feature flag.

There is an ongoing conversation via email between Katy, Liz C and Governance as to whether the validation rules are correct, and whether we can 'fix' those studies.

**Additional context**
See query to find records that fail the validation here:
https://github.com/sanger/sequencescape/issues/4076#issuecomment-2045269998

Table that shows the expected relationships between fields, which the new validation would enforce:

| Data release strategy | Data release timing |
| :--- | :--- |
| Managed or Open | Standard, Immediate or Delayed |
| Not applicable | Never |

To remove the feature flag, merge the following pull request: https://github.com/sanger/sequencescape/pull/4086
This will be the first time the server-side validation is enabled, so consider doing some extra testing of it.

**Solution:** prepare a spreadsheet broken down by faculty. The strategy for each study needs to match the data release timing 

We still need to do it for inactive studies? Could we change validation so that it doesn't validate if it is inactive? Maybe they haven't started yet? What if they have samples that have an accession number?

**Comment by stevieing** [comment]
43 studies to change. Script generated so missing information.

@KatyTaylor Neil has some good knowledge of this so can do some useful work to prepare the information for faculty to review.

**Comment by neilsycamore** [comment]
[Y24-058_studies_imported_from_SNP.csv](https://github.com/user-attachments/files/17437334/Y24-058_studies_imported_from_SNP.csv)
There are 945 studies that were imported from a previous tracking LIMS (ETS) in Oct 2010.
All have 'Automatically imported from SNP, please check & update all information' in the study description. Many of these have new lines or carriage returns in the description. The attached csv has had these removed and makes a useable xlsx worksheet.
Next step is to forward this to the Tech admin/SSR team.

**Comment by neilsycamore** [comment]
[Y24-058_studies_imported_from_snp_managed_ok_count_31.csv](https://github.com/user-attachments/files/17802662/Y24-058_studies_imported_from_snp_managed_ok_count_31.csv)
[Y24-058_studies_imported_from_snp_managed_never_count_221.csv](https://github.com/user-attachments/files/17802664/Y24-058_studies_imported_from_snp_managed_never_count_221.csv)
[Y24-058_studies_imported_from_snp_no_samples_managed_ok_count_12.csv](https://github.com/user-attachments/files/17802665/Y24-058_studies_imported_from_snp_no_samples_managed_ok_count_12.csv)
[Y24-058_studies_imported_from_snp_no_samples_managed_never_count_681.csv](https://github.com/user-attachments/files/17802666/Y24-058_studies_imported_from_snp_no_samples_managed_never_count_681.csv)
[Y24-058_studies_not_applicable_not_set_to_never_14_count.csv](https://github.com/user-attachments/files/17802669/Y24-058_studies_not_applicable_not_set_to_never_14_count.csv)
[Y24-058_studies_managed_or_open_set_to_never_53_count.csv](https://github.com/user-attachments/files/17802670/Y24-058_studies_managed_or_open_set_to_never_53_count.csv)
