### ISSUE TITLE
Y24-063 Create a new attribute retention_instruction in labware table and update the way how retention instructions are stored and retrieved

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/sequencescape#4093]
**User story**

As a developer, I need to update where retention instructions for labware are retrieved from and stored to.

- [x] Create a new attribute `retention_instruction` in `labware` table to store retention instructions for plates and tubes. This attribute can only take the following values: `"Destroy after 2 years"`, `"Return to customer after 2 years"` and `"Long term storage"`.
- [x] Update the current codebase to store retention instructions in `labware` table. Currently, they are stored in `custom_metadata` with  `custom_metadata.key` equal to `retention_instructions`.
- [x] Update the current codebase to retrieve retention instructions from `labware` table and display retention instruction ~in **Metadata** section of the Labware user interface, along with metadata coming from `custom_metadata`. We will introduce a separate page in https://github.com/sanger/sequencescape/issues/3676 to let admin users edit retention instructions.~ in the fields at the top of the Labware page (see the figure below). We will introduce a separate page in https://github.com/sanger/sequencescape/issues/3676 to let admin users edit retention instructions

<img width="746" alt="image" src="https://github.com/sanger/sequencescape/assets/25484917/f226dbe4-ce6c-49e9-88d7-207b7b11ea49">

**Who are the primary contacts for this story**
Dasun, Katy

**Who is the nominated tester for UAT**

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] All retrievals and storage of retention instructions of **new submissions** must occur from/to `labware` table, and not from/to `custom_metadata` table.

**Dependencies**
This story is blocked by the following dependencies:

References
This story has a non-blocking relationship with:
- https://github.com/sanger/sequencescape/issues/4003

**Additional context**

**Comment by KatyTaylor** [comment]
> Update the current codebase to retrieve retention instructions from labware table and display retention instructions in Metadata section of the Labware user interface, along with metadata coming from custom_metadata

I wouldn't do this. It should be easy (if not happen automatically) to add it to the fields at the top of the page, if it's a field on Labware. I think it would be confusing to crowbar it into the Metadata section, since that just pulls from the custom metadata object.

**Comment by dasunpubudumal** [comment]
@KatyTaylor I have updated the description :)

**Comment by dasunpubudumal** [comment]
![image](https://github.com/sanger/sequencescape/assets/25484917/cb25b6b4-a213-493f-a81a-b01ae12ad43e)
