### ISSUE TITLE
Y24-064 Develop an audit mechanism for retention instructions that can later be displayed in the UI

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/sequencescape#4094]
**User story**
As a developer, I need to create an audit trail for retention instructions stored in `labware` table. Please refer to https://github.com/sanger/sequencescape/issues/4093 to see how retention instructions are stored in the table.

- [ ] Establish an eventful `has_one` relationship between `labware` and `events` table. See how a similar implementation in [`lib/eventful_record.rb:29`](https://github.com/sanger/sequencescape/blob/e238a0b7770ab94a94f48438c1b9eae474fbc856/lib/eventful_record.rb#L29C1-L37C6).
- [ ] When persisting a retention instruction (i.e., when uploading a manifest), store an event in the `events` table in the database. This can be done by updating the [`lib/eventful_record.rb`](https://github.com/sanger/sequencescape/blob/develop/lib/eventful_record.rb) module.
- [ ] Update the codebase to persist another record to the `events` table when an update (or a deletion) is made to the retention instructions of a particular labware.

**Who are the primary contacts for this story**
Dasun, Katy

**Who is the nominated tester for UAT**

**Acceptance criteria**
To be considered successful the solution must allow the following:
- [ ] To persist and audit record in the `events` table when a create, update or a deletion is made for a retention instruction of particular labware.
- [x] **Update:** Populating the `events` table with correct `eventful_id` should bring in the data related to the labware history in [Events History](https://training.sequencescape.psd.sanger.ac.uk/labware/27554453/history) page. 

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/sequencescape/issues/4093

**References**
This story has a non-blocking relationship with:
- https://github.com/sanger/sequencescape/issues/4003

**Additional context**

**Comment by KatyTaylor** [comment]
@dasunpubudumal I presume that the event history UI will display these events without any code changes needed? But could be worth adding an acceptance criteria that the audit must be viewable in SS, just so it's tested?

**Comment by dasunpubudumal** [comment]
We can accomplish the audit trail using a simpler approach using [`lib/event_factory.rb`](https://github.com/sanger/sequencescape/blob/0b81263981ce55bff8bc89eeb6036695eac07fb9/lib/event_factory.rb). Since we are only going to create the trail for **update** events, we just need to include a class-level method in `event_factory.rb` and call it in `update` method at `labware_controller.rb`.
