### ISSUE TITLE
Y24-065 Create a script to backfill the labware table's new retention_instruction column

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/sequencescape#4095]
**User story**
As a developer I need to backfill the new attribute `retention_instruction` that was created in the `labware` table in the story https://github.com/sanger/sequencescape/issues/4093. 

Retention instructions for existing labware can be extracted using the following query:

```sql
SELECT cm.key, cm.value, cmc.asset_id
FROM <sequencescape-db>.custom_metadata cm INNER JOIN <sequencescape-db>.custom_metadatum_collections cmc ON cm.custom_metadatum_collection_id = cmc.id
WHERE cm.key = 'retention_instruction';
```

The script could be extendable to remove existing `retention_instruction` values from `custom_metadata` table for assets. See https://github.com/sanger/sequencescape/issues/4093 for more details.

This can be tested in training, where dumps from production are being restored.

**Update**: Inform the DBA team of the script as this needs to be run on production after approval. Along with the script, we can remove conditional logic in [`app/views/labware/_asset_summary.html.erb`](app/views/labware/_asset_summary.html.erb) (and in similar code that conditionally checks for `custom_metadata` in search of retention instructions such as [`app/sequencescape_excel/sequencescape_excel/specialised_field/retention_instruction.rb`](https://github.com/sanger/sequencescape/pull/4096/files/4cc00bb3b979abcedd258f561586426df65319b4#diff-98d2c64e6875b5a9dd25d598f7672f377506a43ede905c6fe2db00a1a3d0a33d)) that aren't applicable anymore after the script.

**Who are the primary contacts for this story**
Dasun, Katy

**Who is the nominated tester for UAT**

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Successfully backfill the labware table's `retention_instruction` column for existing retention instructions in `custom_metadata`.

**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/sequencescape/issues/4093

References
This story has a non-blocking relationship with:
- https://github.com/sanger/sequencescape/issues/4003

**Additional context**
This story needs to be completed soon after https://github.com/sanger/sequencescape/issues/3676 is done.

**Comment by dasunpubudumal** [comment]
Draft script for backfilling: https://gist.github.com/dasunpubudumal/ce70b7d4d99c64cb8bad91e190457a8e

**Comment by yoldas** [comment]
I think, the script should fill the new column with a default retention instruction value if it does not have a value in custom metadata.

**Comment by dasunpubudumal** [comment]
@yoldas Does _every_ labware piece require to have a retention instruction? We can add a default value but I'm not entirely sure whether if there are labware pieces that does not correspond to a retention instruction. Maybe @KatyTaylor or @andrewsparkes can help here.

**Comment by dasunpubudumal** [comment]
**Notes on testing locally**

- Step 1:

Initial setup was done to return the following results for the query:

```sql
SELECT lw.name, cm.key, cm.value, cmc.asset_id
FROM sequencescape_development.custom_metadata cm 
INNER JOIN sequencescape_development.custom_metadatum_collections cmc ON cm.custom_metadatum_collection_id = cmc.id
INNER JOIN labware lw ON cmc.asset_id = lw.id
WHERE cm.key = 'retention_instruction';
```

Results: 
<div align="center">
<img width="602" alt="image" src="https://github.com/sanger/sequencescape/assets/25484917/23e2b605-00f7-491f-b492-c7d7307fed65">
</div>

- Step 2:

Executed the script by using the following command:

```bash
$ bundle exec rake retention_instructions:backfill
```

- Step 3:

Investigated the `labware` table's `retention_instruction` attribute. The following propositions must be true:

1. `labware.retention_instruction` is populated correctly.
2. The corresponding records in `custom_metadata` and `custom_metadatum_collections` are removed.

**Comment by yoldas** [comment]
I suggest including a manual export of the existing custom metadata records for retention instruction, e.g. as CSV before running the rake task. It can be useful for recovery.

**Comment by dasunpubudumal** [comment]
Production deployment commands on 23rd of May, 2024:

1. Deploy `sequencescape` and run migrations:
```bash
ansible-playbook -vD deploy_sequencescape.yml -i environments/production -e "github_branch=v14.34.0" -e "full_deploy=true skip_migrations=false"
```
2. Run the script to backfill the `retention_instruction` column of the `labware` table:
```bash
ssh sss0-prod.psd.sanger.ac.uk
cd /var/www/sequencescape/current
bundle exec rake "retention_instructions:backfill[1000]"
```
3. Connect to PSDP database and verify the contents of `labware` and `custom_metadata` tables:
```sql
-- Check Labware Table --
SELECT * FROM sequencescape_production.labware WHERE retention_instruction IS NOT NULL;

-- Check custom_metadata table --
SELECT cm.key, cm.value, cmc.asset_id
FROM sequencescape_production.custom_metadata cm INNER JOIN sequencescape_production.custom_metadatum_collections cmc ON cm.custom_metadatum_collection_id = cmc.id
WHERE cm.key = 'retention_instruction';
```

It's better to use MySQL Workbench because it implicitly limits the resultset. 

4. Query the barcode `SQPP-18334-K` in [Sequencescape](https://sequencescape.psd.sanger.ac.uk/login) and check whether the **Retention Instruction** value appears in the asset summary in the labware view.
