### ISSUE TITLE
Y24-081 Add Program name field to MLWH

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#4109]
As team lead Sequencing Operations (James M) we would like to add the “name” field from the “Programs” table in the Sequencescape database to the MLWH. This will enable us to identify studies by Sanger programme type and enable efficient reporting.

Contact
jm36

Raised in [RT802591](https://rt.sanger.ac.uk/Ticket/Display.html?id=802591)

**Comment by SujitDey2022** [comment]
@TWJW-SANGER @stevieing this was marked as low priority in the[ requirement sheet ](https://docs.google.com/spreadsheets/d/1GPhbrkizYqz4N9_jTu_qkdlQWqJ73wbTdQ3WshWtzS4/edit?usp=sharing)Seq80 but can be pulled ahead if a quick win.

**Comment by neilsycamore** [comment]
@sabrine33 the column name should be 'programme' see here https://www.sanger.ac.uk/science/programmes/
The 'program' in Sequencescape is incorrect but no one can see it, if we expose it incorrectly in MLWH I'm sure it will not be long before someone points out the error.

**Comment by sabrine33** [comment]
> @sabrine33 the column name should be 'programme' see here https://www.sanger.ac.uk/science/programmes/ The 'program' in Sequencescape is incorrect but no one can see it, if we expose it incorrectly in MLWH I'm sure it will not be long before someone points out the error.

Thank you @neilsycamore for highlighting this, I will update it accordingly.
