### ISSUE TITLE
Y24-107 Sequencescape search function fails to handle exception

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#4122]
When searching 'All' using four digits i.e 1234 Sequencescape returns an exception

![Screenshot 2024-05-22 at 10 22 31](https://github.com/sanger/sequencescape/assets/299768/45978c8c-ce2d-4855-b9cf-2d77fc5cd44e)

An ActionView::Template::Error occurred in searches#index:

  Tried to load unspecified class: HashWithIndifferentAccess
  lib/acts_as_descriptable.rb:49:in `descriptor_hash'

-------------------------------
Request:
-------------------------------

  * URL        : https://sequencescape.psd.sanger.ac.uk/searches?utf8=%E2%9C%93&type=&q=1234
  * HTTP Method: GET
  * IP address : 172.20.242.66
  * Parameters : {"utf8"=>"✓", "type"=>"", "q"=>"1234", "controller"=>"searches", "action"=>"index"}
  * Timestamp  : 2024-05-22 10:22:51 +0100
  * Server : sss0-prod-jammy
    * Rails root : /var/www/sequencescape/releases/20240507130309
  * Process: 3485139

To resolve:
Either:-
a) Sequencescape should handle the exception
b) Helper text should be added to stop users from searching 'All' with four digits

Relates to [RT802971](https://rt.sanger.ac.uk/Ticket/Display.html?id=802971)

UAT
nts

**Comment by sdjmchattie** [comment]
Fix confirmed working in Training.  This can be progressed to UAT and Production when it won't interfere with testing underway for other stories.  @andrewsparkes can mix this in with those changes as they progress.
