### ISSUE TITLE
Y24-114	As SSRs we would like to not have to perform fake cherry picks on stock plates to make submissions so that we are not recording fake data.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4127]
As SSRs we would like to **not** have to perform fake cherry picks on stock plates to make submissions so that we are not recording fake data.

**Description**
We support a number of pipelines whose first step requires a submission on the stock plates received in SciOps from faculty. A restriction within SequenceScape prevents users making submissions on stock plates  - forcing SSRS to create fake transfers and plates, on which they can then create the desired submission.

This undesirable because:

- This creates a false data record of what actually happens in the lab. (I suspect problematic for human material)
- It is an unnecessary operation that the SSR's have to know about and perform. 

**Desired Outcome**
- [ ] Identify possible solutions to the problem (e.g. faculty perform cherry picks and only submit picked plates, enable submissions on stock plates, something else.....)
- [ ] Check for any consequences for canceling and failing wells/plate that link back to submissions on stock plates. 
- [ ] Propose a solution such that fake cherry picks no longer need to be made.
- [ ] Generate user story/ies required to implement change.

**Who the primary contacts are for this work**
SSR team
PSD

**Knowledge or Stake holders**
Liz C

**Comment by andrewsparkes** [comment]
Maybe also fold in why they do purpose changes.
Maybe fake cherrypick is for partials, purpose changes for full plates.

**Comment by TWJW-SANGER** [comment]
See Confluence page "Fake Cherry Picking (CP) Investigation"

Seems like we need to do 3 things (?):

Allow submissions from stock plates.
Allow users to change a plate purpose and/or allow plates to proceed to any purpose on a specified pipeline.
Allow plates to be submitted to SciOps with samples on for multiple studies.

**Comment by KatyTaylor** [comment]
Retention instructions on stock plates needs to be considered - if plates are used as stock plates but not called stock plates, will this cause confusion? (From conversation with Liz C)

**Comment by stevieing** [comment]
Initially we could try adding Stock Plate to the list of acceptable purposes for limber PCR bespoke request type and also to the relationships for bespoke pcr as a starter for 10.

This should work for 10x - CITEseq and EMSeq.

**Comment by stevieing** [comment]
Hi-C - Doesn't actually exist as a pipeline in Sequencescape or Limber so only has a library type. Not sure what we could even do in this case and it is only used for when TopUp sequencing is needed for some samples - rare occurence. This is a long read pipeline.

**Comment by stevieing** [comment]
Outstanding issues:
- **custom RNA** - Not even sure which pipeline this is? If we can work out where we need to make changes we can allow a submission on an RNA stock plate
- **Library quant submissions** - again not sure of the pipeline it is referring to.
- **Bespoke/R&D requests** - again not entirely sure how we would approach this. Do we want to be able to chnage the plate purpose on all pipelines for restricted users.
- **GbS** - I think we need more information on how we could solve this one.
