### ISSUE TITLE
Y24-120	BUG: Taken Link error when creating sequencing batches

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#4133]
From time to time when creating a sequencing batch the Short Read team encounter an error warning
'Ancestor has already been taken, Link already exists between these points'
![taken_link](https://github.com/sanger/sequencescape/assets/299768/9b1d1ae6-e965-4ca6-805a-5a92c32b48ec)

They are unable to proceed with the batch and it is not clear from the warning which of the pool tubes is the centre of the issue.
Team have to raise an issue and wait for a fix before proceeding causing delays in production.

**Cause of issue**
This only occurs in cases where pool tubes have more than one stock tube however it does not occur in every instance of this. 
The expected behaviour is that a pool tube (descendant) should have a 1:1 relationship with it's ancestors i.e. there should only be one AssetLink entry for the descendant per ancestor.
When there is more than one AssetLink entry the error is generated.

To reproduce:

Finding duplicates
`SELECT 
  ancestor_id
, alw.name ancestor_name
, alwpp.name purpose
, descendant_id
, dlw.name descendant_name
, dlwpp.name purpose
, count(*) no_of_records
, group_concat(al.id) 'AssetLink ids'
FROM asset_links al
LEFT JOIN labware alw ON alw.id = al.ancestor_id
LEFT JOIN labware dlw ON dlw.id = al.descendant_id
LEFT JOIN plate_purposes alwpp ON alwpp.id = alw.plate_purpose_id
LEFT JOIN plate_purposes dlwpp ON dlwpp.id = dlw.plate_purpose_id
WHERE al.ancestor_id IS NOT NULL 
AND al.descendant_id IS NOT NULL
GROUP BY al.ancestor_id, al.descendant_id
HAVING count(*) > 1
order by al.created_at ASC;`

[Y24-120_output.csv](https://github.com/user-attachments/files/15741356/Y24-120_output.csv)

SQPP32908 E1:H1 is an example of a pool tube that has to identical asset links.
Requesting additional sequencing (S4, read length 100) and scan to postmanpat
Batch this request with others.
Create batch
'Ancestor has already been taken, Link already exists between these points'

Resolving:
The above SQL shows 76 instances of duplicates from ~10 million records.
Perhaps look to stop creation of duplicates?

**Comment by neilsycamore** [comment]
relates to https://github.com/sanger/sequencescape/issues/3356

**Comment by yoldas** [comment]
Hypothesis: 

The following transfers are creating AssetLinks asynchronously:

app/models/transfer/between_plate_and_tubes.rb
Transfer::BetweenPlateAndTubes

app/models/transfer/between_tubes_by_submission.rb
Transfer::BetweenTubesBySubmission

They both have a build_asset_links method that create a AssetLink::Job, which is a AssetLink::BuilderJob. The create method enqueues a delayed job.

app/jobs/asset_link/job.rb
app/jobs/asset_link/builder_job.rb

When multiple links are to be built quickly, there is a race condition between the jobs at edge creation. 

Testing:

- Find a way to simulate a race condition to reliably reproduce the bug.

Approaches:

- Quick: Run the asset link creation synchronously; no background job. We need to measure the effects on the performance.

- Hard: Find a way to do a create or get the link atomically. How do we know it is the link we are supposed to create?

**Comment by yoldas** [comment]
```sql
SELECT 
    ancestor_id, 
    alw.name AS ancestor_name, 
    alwpp.name AS purpose, 
    descendant_id, 
    dlw.name AS descendant_name, 
    dlwpp.name AS purpose, 
    COUNT(*) AS no_of_records, 
    GROUP_CONCAT(al.id) AS 'AssetLink ids' 
FROM 
    asset_links al 
LEFT JOIN 
    labware alw ON alw.id = al.ancestor_id 
LEFT JOIN 
    labware dlw ON dlw.id = al.descendant_id 
LEFT JOIN 
    plate_purposes alwpp ON alwpp.id = alw.plate_purpose_id 
LEFT JOIN 
    plate_purposes dlwpp ON dlwpp.id = dlw.plate_purpose_id 
WHERE 
    al.ancestor_id IS NOT NULL 
    AND al.descendant_id IS NOT NULL 
GROUP BY 
    al.ancestor_id, 
    al.descendant_id 
HAVING 
    COUNT(*) > 1 
ORDER BY 
    al.created_at ASC;
```

**Comment by yoldas** [comment]
Link already exists between these points

https://github.com/payrollhero/acts-as-dag/blob/0a0a824013013d5b54d5b62716c3e29f0fe8a536/lib/dag/validators.rb#L7

**Comment by yoldas** [comment]
Existing DDL. 

- There are two separate indices on (descendant_id, direct) and (ancestor_id, direct) columns.
- There is no unique together constraint on the parent-child link. I think this would correspond to the trio (ancestor_id, descendant_id, direct). I am trying to understand if the indices in the previous item were intended to establish this uniqueness but got it wrong.

![image](https://github.com/user-attachments/assets/97ce8f66-3e7a-4142-813e-251e2da7954b)

![image](https://github.com/user-attachments/assets/85a9d80a-1588-4edb-b8ad-764d35a1df47)

![image](https://github.com/user-attachments/assets/2819ca21-c20c-4db0-8637-a0c766e0de2a)

**Comment by yoldas** [comment]
Solution: 
- creating a unique-together index on ancestor_id and descendant id
- handling race condition in find_link and has_duplicates unique validation
- handling unique constraint violation

Deployment:
- Deploy first update to run a rake task to remove existing duplicate records
- Deploy second update to handle race conditions

**Comment by yoldas** [comment]
Part-1 of this story is deployed. I have decided to do the release of Part-1 and Part-2 separately and develop a strategy for handling the duplications added in between:

part-1 includes a rake task which is manually executed to remove duplicates from asset_links table to get ready for unique index creation.

Time window here will be handled with a different procedure.

part-2 includes a migration to create a unique index and handling of race conditions.

**Comment by yoldas** [comment]
Deployed Part-1 to both UAT and Training. The following shows the rake command on training and collecting the output file for inspection.

![image](https://github.com/user-attachments/assets/d0e3996d-dc8b-4856-801c-deec1e313e59)

**Comment by yoldas** [comment]
Output of the rake task from UAT and Training:

[uat_deleted_asset_links.csv](https://github.com/user-attachments/files/17189901/uat_deleted_asset_links.csv)
[training_deleted_asset_links.csv](https://github.com/user-attachments/files/17189903/training_deleted_asset_links.csv)

Deleted 251 asset_links records from UAT.
Deleted 324 asset_links records from Training.

**Comment by yoldas** [comment]
Part 1 was deployed to all environments and duplicate records were removed by executing the rake task. Part-2 will be merged to develop and then to environments, for testing and production.

**Comment by yoldas** [comment]
Deployed to UAT and Training. Running integration suite against Training because UAT has breaking changes from another story, training is similar but better, and part-2 is close to production.

**Comment by yoldas** [comment]
During deployment to training (DB is almost the same), the index creation (running the migration) part took about 20 minutes.

**Comment by yoldas** [comment]
I have attached the csv file that contains the record which prevented the production deployment in first attempt. The file is the product of the rake task to remove the duplicates. The unique index creation proceeded without problems after removing the duplicate.

[prod_part_2_deleted_asset_links.csv](https://github.com/user-attachments/files/17278913/prod_part_2_deleted_asset_links.csv)
