### ISSUE TITLE
Y24-187 - As TL I would like to update the support links in SequenceScape to point to FreshService so that we can transition from RT [DUE 14/10/24]

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4194]
**On hold until 14/10/24**

As TL I would like to update the support links in SequenceScape to point to FreshService so that we can transition from RT

**Acceptance Criteria**

- [x] Support hyperlinks to rt.sanger.ac.uk to be updated to point to https://sanger.freshservice.com/a/tickets/new
- [x] Any existing support forms / pages to be removed in favour of a link to FreshService.
- [x] If possible the FreshService landing should be configure such that PSD is specified in the Group field and SeqOps in the Category or Tag fields. (Awaiting ServiceDesk response on if this is possible.)

**Comment by harrietc52** [comment]
# Deployment

- [ ] Merge PR into develop
- [ ] Deploy release v<> to UAT (rollback version v<>) `script-command-here`
- [ ] User testing
- [ ] Create PR develop -> master
- [ ] Merge PR into master
- [ ] Deploy release v<> to Training (rollback version v<>) `script-command-here`
- [ ] Run the Integration Test Suite on the Training environment.
- [ ] Deploy release v<> to Production (rollback version v<>) `script-command-here`
- [ ] Sanity check
