### ISSUE TITLE
Y24-192 - Seq 79: Remove all unused sequencing platforms from SS submission templates

### ISSUE THREAD

**Issue by sg32-gif** [sanger/sequencescape#4198]
**User story**

Need to remove all unused sequencing platforms from SS submission templates that means apart from Mi Seq, Nova SeqX and Nova Seq6000, everything needs to be deleted. These will not be used again in the future work. 

****Who are the primary contacts for this story****
Siobhan Austin; slw@sanger.ac.uk 

**Who is the nominated tester for UAT**
Siobhan Austin; slw@sanger.ac.uk 

****Acceptance criteria****

In SS:
Apart from the above three mentioned sequencing machine, there are no other machines used. Hence to avoid more confusion, we delete all other templates. 

****Dependencies****

There are no much dependencies on this request. 

**Additional Reference:**

There are currently a huge number of submission templates in SS and there is a risk of the wrong one being selected (especially HiSeqX and NovaSeqX due to the similarity in names).

**Comment by SujitDey2022** [comment]
Probably a duplicate one
