### ISSUE TITLE
Y24-201 - As GSU Operational Lead (Anna G) I would like to be able to import up to 70 plates of samples into SequenceScape so that we can avoid manual errors and increase efficiency.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4206]
As GSU Operational Lead (Anna G) I would like to be able to import up to 70 plates of samples into SequenceScape so that we can avoid manual errors and increase efficiency.

**Background**
GSU receive physical plates from Brants Bridge (a former Lighthouse Lab) for processing on the Covid and RVI pipelines.
These plates each come with plate map files of the kind uploaded to ftp by Lighthouse Labs to sftp.
Currently GSU has to takes these platemaps (up to 70 at a time), converts them to manifest files and uploads them to SequenceScape.
This is a time consuming and error prone manual process.

Previously, for Heron the GSU DSE team parsed the plate maps and converted them to RabbitMQ messages that could be consumed by the Crawler application for selection within Lighthouse / BoxBuster / Plate Genie for eventual import into SequenceScape. This is still an option to consider, but the GSU DSE team is now much reduced.

We could also consider if this is an opportunity to start to provide bulk manifest conversion and upload within SequenceScape or automated manifest submission for short read sequencing more generally.

We do not intend to extend SequenceScape to store extra GSU / RVI specific sample metadata such as CT values - my preference would be for GSU to track this for themselves and restrict SS / Limber to supporting data that is needed to run the high throughput pipelines at scale. (Faculty can and do store additional metadata within MLWH for their purposes).

**Acceptance Criteria**

- [ ] Changes do not break the existing Heron / Covid pipeline.
- [ ] Produce at least two design options with a backlog of user stories to import multiple plate maps of sample data from Brants Bridge into SequenceScape with minimal manual intervention. 
- [ ] Aim to produce solution that can be extended to other pipelines, not just RVI/Covid.
- [ ] Consider the minimum amount of data SS / Limber need to know. (Supplier ID and Public Name ?)
- [ ] Consider low-tech (excel, google sheets, python) and high-tech (bulk upload, RabbitMQ) solutions.

**Who are the primary contacts for this story**
Anna G

**Who is the nominated tester for UAT**
Anna G?

**Comment by AnnaGalvin** [comment]
Current workflow which we would like optimising: The sample selection is done using qpcr data from the Brants Bridge lighthouse provided to us in a manually created excel file. This is then converted into the correct Heron style format for ingestion, this csv goes to DAE for upload. Then to make the sample available to us in LIMS we use plate Plate Genie. Once physically stamped into shallow well plates and sample information available in SS, we request a check from PSD to

**Comment by AnnaGalvin** [comment]
Current workflow which we would like optimising: 

1. The sample selection is done using qpcr data from the Brants Bridge lighthouse provided to us in a manually created excel file. 
2. This is then converted into the correct Heron style format for ingestion, this csv goes to DAE for upload. Then to make the sample available to us in LIMS we use plate Plate Genie. 
3. Once physically stamped into shallow well plates and sample information available in SS, we request a Root ID check from PSD to verify the sample selected (using the qpcr data) is correct against MLWH  
4. Samples are then selected for bespoke CP

**Comment by AnnaGalvin** [comment]
And to add anonymous IDs to remove the need to do it manually. Currently done by PSD post CP

**Comment by AnnaGalvin** [comment]
PSD scoping requirement document for RVI bait capture sample ingestion : https://docs.google.com/document/d/15dUTN_IYepnHjuOW6gN7dehSzD6o_I3TkuVGwj9muFU/edit

**Comment by KatyTaylor** [comment]
Write up from reminding myself of the designed / current sample import processes for Heron & RVI:

### Heron

1. GSU parses the plate map files and sends resulting messages to RabbitMQ
2. PSD's crawler consumes the messages and inserts into our MongoDB database, and the (Beckman) DART database.
3. crawler sends a feedback message to say whether it all went OK.
4. If it all went OK, GSU inserts records into the lighthouse_sample table of the MLWH (think actually they are inserted upfront and then deleted again if a negative feedback message is received).
5. GSU use Box Buster (https://lighthouse-ui.psd.sanger.ac.uk/box_buster) to scan box barcodes and examine the samples within, and choose which plates should go down the pipeline (see screenshot further down). Box Buster pulls info from LabWhere and MongoDB.
7. Various priority flags are set against samples, again using RabbitMQ messages and crawler - set on the samples collection in MongoDB.
8. Chosen plate is scanned on the robot platform. Depending on platform (Beckman or Biosero), robot method queries different sources to ask what to pick (ultimately either DART or MongoDB database), and picks desired samples into destination plate.
9. Robot method calls LIMS API to create destination plate and samples in Sequencescape. Plate purpose (LTHR Cherrypick) and Study will be specific to Heron pipeline.
10. Created plates go down the Limber ‘Heron-384 Tailed V2’ pipeline (automatic submission done on first step).

#### Box Buster:
![Screenshot 2024-08-12 at 11 37 14](https://github.com/user-attachments/assets/5f4f3041-8d1a-4df7-8156-0e30f3e2d0dc)

### RVI

#### Crossover with Heron:
1. Sanger receive samples in deep well plates from lighthouses.
2. They may be covid or other samples.
3. If they want to use some samples for Heron, these samples are picked off the plate (using existing Heron cherrypicking process?) first.

#### RVI process:
1. Plate barcode is scanned into Plate Genie (https://plate-genie.psd.sanger.ac.uk/deep_well_plates), which will import them (minus any samples that have already been imported via Heron cherrypicking) into Sequencescape as LDW-96 Stock plates. Plate Genie pulls info from MongoDB.
2. Short Limber pipeline allows stamp from deep well plates to LSW-96 Stock shallow well plates.
3. SS cherrypicking pipeline creates RVI Cherrypick plate.
4. Which then goes down Limber ‘RVI Bait Capture Library’ pipeline.

#### Plate Genie:
![Screenshot 2024-08-12 at 11 45 55](https://github.com/user-attachments/assets/c09cc1d1-ba31-4e6a-ba6e-effaa16b6668)

**Comment by AnnaGalvin** [comment]
Issue will be closed. Ticket was placed preempting a problem. GSLP have been able to successfully ingest sample data into LIMS via plate genie, given the plate maps have been added to sftp. 
Anonymous id addition still required, data for rvi has yet to be shared. will create another ticket
