### ISSUE TITLE
Y24-209 - Update the Short Read Team Cross Charging Report with corresponding to NovaSeqX platforms

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/sequencescape#4226]
**User story**
As a User (Rich R.) responsible for Short Read cross-charging reports, I would like to include the details relevant for NovaSeqX v1.2 sequencing platforms SO THAT accurate billing is possible considering the increased usage of the platform 

**Who are the primary contacts for this story**
Tris B.
Rich R.

**Who is the nominated tester for UAT**
Rich R.

**Acceptance criteria**

1. Link to the exiting cross charging report: https://globalreporting.internal.sanger.ac.uk/#/views/NewBilling/SequencingBilling?:iid=1 

To be considered successful the solution must allow:
- [ ] Information needed to be included to the cross charging report is extracted for only v1.2 version runs of the NovaSeqX platform runs contained in the “RunParameters.xml” file.
  - “RunParameters.xml” file example here: https://esa-sv-20201215-02.dnapipelines.sanger.ac.uk:12443/export/esa-sv-20201215-02/IL_seq_data/analysis/20240321_LH00275_0020_B222V7HLT1/RunParameters.xml
- [ ] Following sequencing run details are included in the report,
  - Kit Type and Kit Cycle, available under 'ConsumableInfo'
  Example: 
  
  ![image](https://github.com/user-attachments/assets/83b8c91f-0d24-4ea9-b24c-df03082f0f7e)

  Where, 1.5B is the Kit Type (Flowcell Type) and 100c is the Kit Cylce information

  - Primer details, available under 'RecipeVersion'
  Example:
  ![image](https://github.com/user-attachments/assets/d3a4376c-808e-47ff-aff0-8754f2cc7f93)

OR

![image](https://github.com/user-attachments/assets/c69aa752-5d29-478e-a107-a742a324a282)

- [ ] Fields with no values are left blank with no default values added.
  
**Dependencies**
This story is blocked by the following dependencies:
- N/a

References
This story has a non-blocking relationship with:
- N/a

**Additional context**

**Comment by SujitDey2022** [comment]
@KatyTaylor adding your comment regarding MLWH,

![image](https://github.com/user-attachments/assets/748b0eb3-dbf3-4f5b-96a8-9151502608b8)

**Comment by SujitDey2022** [comment]
![image](https://github.com/user-attachments/assets/ddec5b87-b962-4598-8f69-9a7976a274b8)

**Comment by KatyTaylor** [comment]
Link to Harry's billing docs - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Automating+Billing+Report

See section
```
ExtractValue(iseq_run_info.run_parameters_xml, '//SbsCycleKit')
```

for an example of how to pull info from the XML.

**Comment by sabrine33** [comment]
I double-checked with Marina and confirmed that the data is being consistently populated. However, some very old run data might not be available. 
Marina also mentioned that the data should appear at the end of the primary analysis stage.

**Comment by sabrine33** [comment]
Hi @SujitDey2022 , @khelwood , @KatyTaylor;
It is not entirely clear on the specific information that needs to be included in the report, particularly regarding the column names and their corresponding values. From our last meeting, I recall that we agreed to add two columns:

Custom Primer(s) Used: This column should indicate a boolean value.
Recipe Name: This column should contain a string value, if applicable.

Could you please confirm if this is correct?

**Comment by sabrine33** [comment]
From Tris: 

```
I’d suggest just the ‘<RecipeVersion>’ values – an example below:
 
<RecipeVersion>10B-01.02.00_CustomPrimer_CP1CP2</RecipeVersion>
 
Rich can then likely just add a filter – which can then translate into a Yes/No depending on the recipe contents.
 
I’m sure Rich will flag if not at the UAT stages.
```

I suppose this is quite ready to progress on now.
