### ISSUE TITLE
Y24-221 - Create Sequencescape pages for tag sets

### ISSUE THREAD

**Issue by yoldas** [sanger/sequencescape#4239]
**User story**
As PSD, we would like to create a page to link tag groups as tag sets and list the tag sets.

**Who are the primary contacts for this story**
Abdullah, Andrew, Katy, Neil

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:

New Tag Sets:
- [ ] Input for the name of the tag set
- [ ] Dropdown for the first tag group
- [ ] Dropdown for the second tag group if dual index tag set
- [ ] Only SSRs and admin to create Tag Sets. [Added after 6th August meeting]

Tag Set Listing
- [ ] List tag sets and its tag groups.

View Tag Set
- [ ] Individual tag set page shows tag set linking
- [ ] The link text to create the tag layout template  is **Create a new tag layout template from this tag set** 
- [ ] The link navigates to the new tag layout template by setting tag_group_id and tag2_group_id URL parameters to initialise the target page with the correct tag groups.

**Dependencies**
This story is blocked by the following dependencies:
- #4160
- #4236

References
This story has a non-blocking relationship with:
See links in the parent research story.

**Additional context**
- Existing UAT New Tag Group page: https://uat.sequencescape.psd.sanger.ac.uk/tag_groups/new
- Existing UAT Tag Group listing page: https://uat.sequencescape.psd.sanger.ac.uk/tag_groups/
- Existing View Tag Group page: https://uat.sequencescape.psd.sanger.ac.uk/tag_groups/1

Update requirements after discussions with users:
- Validation of pairs selected
- Filters based on for example chromium ones or dual ones, adapter type etc.

**Comment by KatyTaylor** [comment]
I would suggest, for dual index, that we set the name automatically. The two boxes could be labelled 'i7' and 'i5', and we can automatically append those suffixes onto the tag set name to create the tag group names.

I think adapter type will be the same for both i7 and i5, so just one box for that.

Not necessarily MVP, but I think ideally the list and detail pages should show tag sets (rather than groups) too.

> Includes a field to the tag group name
Is this meant to say 'tag set name' ?

Think this is blocked by https://github.com/sanger/sequencescape/issues/4236 too.

**Comment by yoldas** [comment]
> Thoughts:
> 
> * For dual index, set the name automatically. The two boxes could be labelled 'i7' and 'i5', and we can automatically append those suffixes onto the tag set name to create the tag group names.

I have updated the criteria: 
- for single index tag sets, the only tag group has the same name as the tag set.
- for dual index tag sets, tag groups names are to be generated by appending (i7) and (i5) to the tag set name.

**Comment by yoldas** [comment]
> * I think adapter type will be the same for both i7 and i5, so just one box for that.

Updated now. There should be one box for the adapter type.

**Comment by yoldas** [comment]
> * Not necessarily MVP, but I think ideally the list and detail pages should show tag sets (rather than groups) too.

I have tried to enhance the existing tag group pages with tag set information and assumed giving the name of the tag set would be enough for a minimal solution. If we create pages for tag sets instead, we can achieve a cleaner solution maybe. In that case, the existing tag group pages need links to the tag set pages instead of just names. I have updated the description now.

**Comment by yoldas** [comment]
I have updated the story with new tag set page designs. Acceptance Criteria are updated for replacing  tag group pages with the new tag set pages.

**Comment by KatyTaylor** [comment]
Noting down something we mentioned -

If we are *replacing* the current tag group pages with tag set pages, we have to make sure tag groups always have an associated tag set - otherwise, you will have some orphaned tag groups that you can't access through the UI.

**Comment by yoldas** [comment]
We are no longer proposing the modification of existing tag group pages. We will add pages to create/list/view tag sets that link the existing tag groups.
