### ISSUE TITLE
Y24-245 - As lab users we would like to be able to make a submission from a Stock Plate for the 10x - CITEseq and Emseq pipelines so that we no longer need to do a fake cherrypick to reduce workload and remove creation of fake data

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#4270]
**User story**
As lab users we would like to be able to make a submission from a Stock Plate for the 10x - CITEseq and Emseq pipelines so that we no longer need to do a fake cherrypick to reduce workload and remove creation of fake data

**Who are the primary contacts for this story**
Steve / Liz

**Who is the nominated tester for UAT**
SSRs / ??

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Add stock plate to the list of acceptable puroposes for Limber PCR bespoke request type
- [x] Update the appropriate relationships
- [x] Release onto UAT from branch to try and test the process end to end to ensure there are no hidden issues
- [x] Add a scenario to the existing integration suite test to create a plate of purpose 'Stock Plate' with a submission for Bespoke PCR on it and check you can create the first child plate 'LBB Ligation'

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #4127
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by wendyyang** [comment]
For existing DB (e.g. UAT and PROD), use the following steps to manually update the Stock Plate purpose:

login to the server, e.g.
ssh sss0-uat.psd.sanger.ac.uk

Go to the current release directory:
cd /var/www/sequencescape/current/

Run the console
bundle exec rails c

#find the stock plate
p = PlatePurpose.find_by(name:"Stock Plate")

#update the type
p.type = 'PlatePurpose::Input'

#save it
p.save

Check the uat database, i.e. psdd. in Mysql Workbench, run query:
select * from sequencescape_staging.plate_purposes where name = 'Stock Plate';
check if the stock plate type is 'PlatePurpose::Input'.
If so, that should mean the update is successful.

**Comment by dasunpubudumal** [comment]
The issue with the cucumber tests is that the pooling behaviour for an input plate is overridden for `PlatePurpose::Input` at [app/models/plate_purpose/input.rb:54](https://github.com/sanger/sequencescape/blob/9c10936c7bbf369e1d5838ee7f688357988ea800/app/models/plate_purpose/input.rb#L54).

Attached following is the numbered trace of the execution flow:

1. app/models/tag_layout.rb:60
2. app/models/tag_layout/walk_wells_by_pools.rb:6
3. app/models/plate.rb:83
4. app/models/plate_purpose.rb:69
5. app/models/plate_purpose/input.rb:54

**Comment by dasunpubudumal** [comment]
There's one more update to be done for this.

As @wendyyang has mentioned [above](https://github.com/sanger/sequencescape/issues/4270#issuecomment-2344577597), we need to set the stock plate as an input plate. 

Also, we will have to populate `request_type_plate_purposes` table with a record associating the request type `limber_chromium_bespoke` (its ID) with plate purpose `Stock Plate` (its ID).

As far as I know, this is done with the record loader. However, record loader only allows purposes in `config/default_records/plate_purposes` and it is not possible to add `Stock Plate` into it as `Stock Plate` purpose is already populated in the purposes table.

I think we will have to add a new record to the table associating `limber_chromium_bespoke` (its ID) with plate purpose `Stock Plate` (its ID).
