### ISSUE TITLE
Y24-271 - Configuration and integration test for the start of LCM Triomics Pipeline

### ISSUE THREAD

**Issue by yoldas** [sanger/sequencescape#4291]
**User story**
As PSD, we would like to create configuration and integration test for the start of the LCM Triomics WGS/EMSeq pipeline to enable parallel development of branches. This part starts with the submission on Lysate plate and goes up to and includes Adp Lig plate in the [Process Diagram](https://lucid.app/lucidchart/b71a82e4-ca5c-4fb4-a2bb-4f16e21f6376/edit?invitationId=inv_80dd70e7-82ea-4415-b592-c507c64af359&page=pY0tJQ3FKvrSt#).

**Who are the primary contacts for this story**
Abdullah (PSD)
Andrew (PSD)
Katy (PSD)
Shiv (PSD)
Scott G (R&D)
Sara W (Lab ops)

**Who is the nominated tester for UAT**
TBC

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Configuration up to and including Adp Lig plate
- [x] Integration suite test up to and including Adp Lig plate
- [x] Initial submission common for the pipeline branches on Lysate plate
- [x] Allows pre-creation of the plates LCMT DNA frag, LCMT DNA end prep, LCMT DNA Adp Lig in pending state. Note that EMSeq branch pre-creates two more plates after Adp Lig.

**Dependencies**
This story is blocked by the following dependencies:
None

**References**
This story is part of the parent story:
- [Y24-194 - LCM WGS/EM-Seq - Pipeline configuration and integration test](https://github.com/sanger/sequencescape/issues/4199)

**Additional context**
The initial submission will cover until the end of the EMSeq branch. There will be an automated submission for WGS branch. This story should implement common configuration until the branch point.

**Comment by andrewsparkes** [comment]
@SHIV5T3R Can you add a link to the integration suite test PR on here as it's one of the requirements. Thx.

**Comment by SHIV5T3R** [comment]
This part of the pipeline is done, all changes are currently in:

- https://github.com/sanger/limber/pull/1879
- https://github.com/sanger/sequencescape/pull/4318
- https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/merge_requests/157

and will be merged in when complete. I'll close this issue, but keep my PRs open for now.
