### ISSUE TITLE
Y24-286 - [BUG] RVI Bait Capture Library Preparation requests not being updated.

### ISSUE THREAD

**Issue by BenTopping** [sanger/sequencescape#4306]
**Describe the bug**
**NOTE:** The `Limber-Htp - RVI - Bait Capture Library` submission is being superseded by the `RVI Limber-Htp - RVI Bait Capture Library - NovaSeq 6000 paired end sequencing` but the issue still applies to both.

The `Limber-Htp - RVI - Bait Capture Library` submission template creates 2 request groups, `Bait Capture Library Preparation`, `Limber Multiplexing`. These requests should update automatically whilst going through the RVI BCL Pipeline in Limber. However the `Bait Capture Library Preparation` requests are not getting updated.

This does not appear to affect the pipeline but we should fix this so it does get updated correctly and update the existing records so the requests are correctly passed.

**Suspected cause**
The requests should be started during the RVI Cherrypick -> RVI RT plate transfer / bed verification. This is controlled by [the transfer request logic here](https://github.com/sanger/sequencescape/blob/develop/app/models/transfer_request.rb#L296) and the transition states in Limber's robot file for this bed verification. However the state update is not getting fired because the RVI RT does not go into the started state.

**Acceptance criteria**
- [x] Update the RVI-BCL pipeline so that it starts it's `Bait Capture Library Preparation` requests when transferring from RVI Cherrypick to RVI RT. This may require updating the state machine in sequencescape transfer_request and the states in the Limber Robots file for the RVI-BCL pipeline.
Completed in: https://github.com/sanger/sequencescape/pull/4482

- [ ] Update historical `Bait Capture Library Preparation` requests so that they have the correct states via a rake task.
  - [ ] Should be 'Passed' if the limber multiplexing requests are passed.
  - [ ] Should be 'Started' if the limber multiplexing requests have not yet been started.
  - [ ] Check whether the state change requires a correct time stamp.
  - [ ] Check whether the request state is sent to the warehouse, if so update the rake task accordingly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the RVI BCL integration test suite to completion.
2. Go to the created `Limber-Htp - RVI - Bait Capture Library` submission 
3. See `Bait Capture Library Preparation` requests are not started or passed.

**Screenshots**
![Screenshot 2024-08-28 at 14 00 35](https://github.com/user-attachments/assets/418b6824-b305-4886-9271-0b500f59122c)

**Additional context**
This story is a mixture of Limber and Sequencescape work.

You may also be able to forcefully pass the requests without starting them by using Limbers work_completion_request_type.

Contacts Ben T, Andrew S, Katy T.

**Comment by KatyTaylor** [comment]
This may also mean that the library_start events haven't been sent to the Event Warehouse for this pipeline.

**Comment by BenTopping** [comment]
@KatyTaylor I'm not sure whether its worth fixing the historical data. I don't think we will be able to determine when the requests were originally started and hence when the library start event should occur, not sure if its better to have no event or an incorrect event.

**Comment by TWJW-SANGER** [comment]
@BenTopping @KatyTaylor 
Anna G says there is not much value in correcting historical data as corrections have already made to billing manually (Only 2 months impacted).

**Comment by BenTopping** [comment]
Closing as confirmed with Anna G there is no need to back fill historical data for billing and there is no advantage for us except occasionally we will need to manually pass an old plate for ReISC.
