### ISSUE TITLE
[BUG] Exception 29/08/2024 at 10:42

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#4309]
#### Email subject line

[Psd-exceptions] [Sequencescape Production] requests#show (ActionView::Template::Error) "undefined method `labware_id' for nil:NilClass"

#### Error body

```
An ActionView::Template::Error occurred in requests#show:

  undefined method `labware_id' for nil:NilClass
  app/models/comment.rb:42:in `block in counts_for_requests'
```

#### Acceptance Criteria

- [ ] Look into this exception and fix the code to handle the exception sensibly.
- [ ] Document the root cause and solution in a comment on this issue.

#### Additional information
The id of the user who triggered this error is often shown in the exception email, in case you need to communicate with them.

**Comment by dasunpubudumal** [comment]
@wendyyang Kibana logs might give more information: 

http://kibana.psd.sanger.ac.uk/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2FM,mode:quick,to:now%2FM))&_a=(columns:!(_source),index:'10b2b450-5719-11ee-8c04-7930a8f11eaa',interval:auto,query:(language:kuery,query:'program.keyword:%20*sequencescape*%20and%20message:%20*counts_for_requests*'),sort:!('@timestamp',desc))
