### ISSUE TITLE
Y24-289 - [BUG] Exception 29/08/2024 at 15:28

### ISSUE THREAD

**Issue by harrietc52** [sanger/sequencescape#4310]
#### Email subject line

[Psd-exceptions] [Sequencescape Production] searches#index (ActionView::Template::Error) "uninitialized constant Barcode::FormatHandlers:...

#### Error body

```
An ActionView::Template::Error occurred in searches#index:

  uninitialized constant Barcode::FormatHandlers::AkerBarcode
  app/models/barcode.rb:222:in `const_get'
```

#### Acceptance Criteria

- [ ] Look into this exception and fix the code to handle the exception sensibly.
- [ ] Document the root cause and solution in a comment on this issue.

#### Additional information
The id of the user who triggered this error is often shown in the exception email, in case you need to communicate with them.

**Comment by stevieing** [comment]
@wendyyang More context. This is happening because someone is running a Sequencescape search  /searches?type=&q=7747.

It looks like they are doing a search for study 7747 but because they are not specifiying a type it is actually looking for everything with an id of 7747.

We probably don't want it to fail but it is worth a check on how it is handled.

It will be difficult to reproduce in UAT as we might not have any Aker barcodes in the table.

**Comment by neilsycamore** [comment]
This exception is raised in the Sequencescape console when calling labwhere_location on a Labware object that has an aker_format (id = 4) barcode
e.g.
l = Labware.find 23061777
l.labwhere_location
/var/www/sequencescape/releases/20240920142713/app/models/barcode.rb:222:in `const_get': uninitialized constant Barcode::FormatHandlers::AkerBarcode (NameError)

I've come across this when writing reports in Ruby and have handled this with:
```
class Labware
  def find_location()
    if self.barcodes.map(&:format).include?("aker_barcode")
      location = nil
    else
      location = self.labwhere_location
    end
    return location
  end
end
```

**Comment by neilsycamore** [comment]
```
barcodes = Barcode.where(format:4)
labware  = barcodes.map(&:asset)
```
using the above method
```
labware.map(&:find_barcode)
=> ["NT1457915H", "DN537747W", "DN537868H", "DN537869I", "DN537870B", "DN538319K", "NT1462400Q", "DN538443N", "DN552057Q"]
```
DN537747W is the barcode being matched in the search
