### ISSUE TITLE
Y24-290 - [BUG] Exception 28/08/2024 at 17:35:40

### ISSUE THREAD

**Issue by sdjmchattie** [sanger/sequencescape#4311]
#### Email Subject Line

[Psd-exceptions] [Sequencescape Production] searches#index (ActionView::Template::Error) "uninitialized constant Barcode::FormatHandlers:...

#### Error Body

```
An ActionView::Template::Error occurred in searches#index:

  uninitialized constant Barcode::FormatHandlers::AkerBarcode
  app/models/barcode.rb:222:in `const_get'
```

#### Acceptance Criteria

- [ ] Look into this exception and fix the code to handle the exception sensibly.
- [ ] Document the root cause and solution in a comment on this issue.

#### Additional Information
The id of the user who triggered this error is often shown in the exception email, in case you need to communicate with them.

**Comment by stevieing** [comment]
Duplicate.
