### ISSUE TITLE
Y24-304 - Allow fixed placement of controls when cherrypicking

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#4333]
**User story**
As a user of the cherrypicking pipeline in Sequencescape, I would like there to be an option to add controls into a fixed location on the destination plate(s), so that I can choose where I want my controls.

Existing behaviour:
The cherrypicking pipeline currently has a dropdown called 'Control Plate', which is populated with the existing control plates in the system. A Control Plate is a special kind of labware, which generally has just a few of its wells populated with control samples. When a control plate is selected in the cherrypicking pipeline, these control samples are put into wells on the destination plate(s). The current behaviour is to randomise the location of these samples on the destination plate(s).

**Who are the primary contacts for this story**
Anna G, Adrianne L, Katy

**Who is the nominated tester for UAT**
Anna G, Rich C

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] I am able to choose to place the controls in pre-specified fixed locations on the destination plates (e.g. H10, H11 and H12).
- [x] Existing randomisation behaviour continues to work.
- [x] Control plates are used as the source of the control samples.
- [x] Control samples are added to the same locations on the destination plate as they are in on the control plate.
- [ ] In UAT, get customer to make their own control plate using [this documentation](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Creating+Control+Plates) (developer needed for final step), and test using that.
- [x] If needed, update [instructions for making Control Plates](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Creating+Control+Plates) 
- [x] If the control plate and plate template clash, display an error message

**Dependencies**
Original research story - https://github.com/sanger/limber/issues/1864 

**Additional context**
UX & design options are discussed in [a comment](https://github.com/sanger/sequencescape/issues/4333) on this issue.

See code in:
- `cherrypick_task.rb`
- `cherrypick_handler.rb`
- `control_locator.rb`

Quickest way to get to the cherrypicking screen:
- Create stock plate: UAT tab, Create Plate, accept default options, copy resulting plate barcode
- Create cherrypick submission: UAT tab, Test Submission, submission template = 'Cherrypick', Plate barcode = paste in your barcode 
- Create cherrypick batch: Pipelines tab, Cherrypick, refresh page until your plate appears in the table, select that row and hit Submit
- Click on 'Select Plate Template'

**Comment by SHIV5T3R** [comment]
Currently, when adding the control samples to the destination plate, the order of wells (relative to well position and map IDs) are inverse. This seems to be because when making a control plate, the wells are ordered in this way, which is the opposite of how the destination plate wells are ordered. 

To solve this, I've written a function to find the well position on an emulated "invalid plate" and track the map ID that corresponds to the well position on the valid plate, which represents the order of wells on the destination plate. 

Another solution would be to change how the manifests are created so that when making a control plate, the order is changed so that work doesn't need to be done in the control locator.

**Comment by yh4-GSU** [comment]
Just to transfer some conversations with Shiv after testing here:
- in UAT, when generating CP submission with a control plate (with controls sitting in H10,H11,H12) and several sample plates (total the sample number= 96); it automatically populated samples and controls into 2 plates (first plate is full and second plate is partial) see attached image
- the first (full) plate has controls going into the wells the same as wells in the control plate (H10,H11,H12) with samples being randomly allocated. This fulfills our requirement👍!
- the second (partial) plate however populates the samples and controls in well order (A1-H12) with controls going to wells right after the samples in stead of going into H10,H11,H12. This is NOT fullfill the requirement.
- I'd suggest: for all FULL plates => controls automatically added into fixed well positions (the same as control plate); while for all PARTIAL plates => controls NOT automaticlly added during CP submission.
Many thanks
![Screenshot 2024-10-16 at 14 27 05](https://github.com/user-attachments/assets/e45e34ed-f351-40ae-9630-d0f40db088e5)
