### ISSUE TITLE
Y24-310 - Accept customer input in cDNA prep submission - bulk

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#4337]
**User story**
As a user of the scRNA Core pipeline, I want to be able to collect extra information from the customer at the point of submission of LRC Bank Seq and Spare tubes for cDNA Prep.
* Number of samples/pool - will be used to automatically allocate samples to pools. 
* Number of cells per chip well - affects the recommended chip loading concentration, as well as the absolute volume to transfer to the chip.

**Who are the primary contacts for this story**
Abby, Katy

**Who is the nominated tester for UAT**
Abby, Liz H

**Acceptance criteria**
- [x] SSR can create a cDNA prep submission through the bulk method, which includes two new columns ‘Samples per pool’ and ‘Cells per chip well'
- [x] Validate on upload that the values for these columns do not vary within a Study (could use Order as proxy if easier).
- [x] Number of samples per pool must be between 5 and 25 (inclusive) (if there's a value in the column)
- [x] Number of cells per chip well must be between 12,000 and 90,000 (inclusive) (if there's a value in the column)
- [x] When submission is created, options provided above are saved (suggest request_options on Order, which ends up in request_metadata_attributes on each Request).

**References**
Research story: https://github.com/sanger/limber/issues/1865

**Additional context**
This is about the bulk submission only, not the submission through the UI. That can be tackled in a different story.

Ideally, these columns should only show for the relevant submission template (but might be tricky as i think currently it's not configurable) - this can be looked into in a separate story.

**Comment by andrewsparkes** [comment]
This one partially already done by Abdullah and myself. Have a branch I can share.

**Comment by seenanair** [comment]
@andrewsparkes Oh, sorry. I didn’t know that. I’ll pick another one.

**Comment by andrewsparkes** [comment]
Assigned to myself and @yoldas as we'd already partially done some of it as research when doing the pooling calculation story.

**Comment by KatyTaylor** [comment]
This has been signed off in UAT already. There are a few potential areas for improvement, raised in UAT and discussed within the team this week:

**Validation of the two new fields:** 
- The two new fields are validated within the spreadsheet (constrained to a range).
- You can bypass this validation by either:
    - Filling the equivalent input fields out on the page in Sequencescape where you download the submission form - fill them out to be outside the range, and they are populated in the spreadsheet and not validated.
    - Converting the spreadsheet to a csv to bypass the excel validation.

Don't think we need to worry about the second one - this is common to all submission fields and would only be done intentionally.

We could think about solving the first one by either:
- Adding validation to the input boxes
- Adding validation upon upload of the submission (would also solve the second one)

We want to be careful about duplicating the constants that are used to define the ranges.

**Issue with pool of 24:**
Abby encountered an issue when trying to create a pool of 24.
We think this was user error, in that she uploaded the submission with a value of '10' for 'number of samples per pool' - so don't think anything needs to be done here.

However, there is a possibility that she tried to re-upload the submission with a corrected value - we could look into whether this is possible and whether/how to prevent it.
