### ISSUE TITLE
Y24-366 - As a staff scientist I would like to have a separate submission for the new BGE pipeline.

### ISSUE THREAD

**Issue by BenTopping** [sanger/sequencescape#4402]
**User story**
As a staff scientist (Matt M) I would like to have a separate submission for the new BGE pipeline. This submission is required for the new BGE Limber pipeline to function.

**Who are the primary contacts for this story**
Matt M, Sara W, Liz C, Katy T, Ben T

**Who is the nominated tester for UAT**
Matt M, Sara W, Liz C

**Acceptance criteria**
To be considered successful the solution must allow:
**This will be the initial submission**
- [x] Add a new request type limber_bge_pcr_free (copy of PCR Free request)
- [x] Add a new submission template for BGE pipeline (name based on its contents or ask stakeholders)
  - [x]  Submission includes new BGE request (copy of PCR Free request) and a multiplexing request

**This will be the second, automated submission**
This submission is purely for pipeline 3 in the lucid chart. A small limber pipeline to move plates across from PCR Free to ISC.
- [x] Add a new request type limber_bge_transition (not sure on the name or the request type as its not strictly library prep)
- [x] Add a new submission template for BGE transition
  - [x] includes new BGE transition request

**This will be a third submission on BGE ISC**
- [x] Add a new request type limber_bge_isc (copy of ISC request)
- [x] Add a new submission template for BGE ISC pipeline (name based on its contents or ask stakeholders)
  - [x]  Submission includes new BGE ISC request (copy of ISC request) and a multiplexing request
 
**References**
This story has a non-blocking relationship with:
- Limber [BGE pipeline setup story](https://github.com/sanger/limber/issues/1980)

**Additional context**
- BGE Library type already exists
- The pooling (prior to blending) strategy will be specified in this new submission, in the normal way (using the submission name to group pools together).
- [BGE Research doc](https://docs.google.com/document/d/1pp4p2n3wMuDTlwDV6rr6u9hZD0F2-F4FN3PPRauTJ-g/edit#heading=h.in9mq3mdhq1z) (contains link to lucid chart pipeline design)

**Comment by KatyTaylor** [comment]
The third submission will be an 'automated' one - created by Limber through the API. Consider using `submission_class_name` `AutomatedOrder` on the submission template. We don't seem to be using it for all our automated submissions, but perhaps should for this one.

**Comment by KatyTaylor** [comment]
Think ideally the submission would include the blending and sequencing (Novaseq) request types too. Could add that in here, or will it come in later in the blending stories?

**Comment by dasunpubudumal** [comment]
Hi @BenTopping @KatyTaylor, I have partially implemented the changes in https://github.com/sanger/sequencescape/pull/4511. A couple of questions:

1. For the submission made with `limber_bge_pcr_free` and `limber_bge_isc` request types, do we need the`illumina_htp_novaseqx_paired_end_sequencing` in `request_type_keys`?
2.  Are there any other additional request type keys for the submission related to the `limber_bge_transition` request?
3. I have named the submissions the following. Do we need to change them?
    - Limber-Htp - BGE PCR Free
    - Limber-Htp - BGE Transition
    - Limber-Htp - BGE ISC
4. The transition request type uses a `IlluminaHtp::Requests::StdLibraryRequest`. Is this correct or does this require a different type?

**Comment by BenTopping** [comment]
@dasunpubudumal 
1. For the time being I think we can leave the sequencing requests off them until we get to the later stages of the pipeline and understand which requests are needed.
2. Just one request.
3. Look fine for the time being, im not sure if they classify as Htp (High throughput) - but these are just preliminary submissions to help with testing the pipeline so as long as they are wip'd we can change them down the line. Since BGE Transition is automated we could rename to `Limber - BGE Transition - Automated`
4. Good question, im not sure. Does the standard library request associate any unique data with the submission? We don't need any extra data, purely a request to help with the limber pipeline.

**Comment by KatyTaylor** [comment]
1. I'm hoping that we can include two extra request types in the upfront (pcr free) submission, one for the 'blending' step and one for the sequencing step. But, like Ben said, we probably need to leave them off until later on as we haven't quite figured out the blending step yet.
2. Agree with Ben
3. Agree with Ben
4. Library requests normally have a library type associated with them - not sure if it's mandatory. Could try a 'customer request' instead. Or, can set the library type as BGE.

**Comment by dasunpubudumal** [comment]
UAT: ![Image](https://github.com/user-attachments/assets/b077287f-bece-4489-81db-053a310a5de1)
