### ISSUE TITLE
Y24-374 -  [RESEARCH] As Legal we would like to ensure the Data Access Agreements actually used for Studies are synchronised with the Electronic Data Access Management (EDAM) system to avoid delays in granting access.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4407]
**Description**
As Legal we would like to ensure the Data Access Agreements actually used for Studies are synchronised with the Electronic Data Access Management (EDAM) system to avoid delays in granting access.

**Additional context or information**
When data has been released to the EBI, external researchers will ask to access it and then the EBI will ask the Sanger Legal team permission to grant it. 
Too often the data access agreement is unknown to the Legal and Governance Team resulting in delays in releasing data to external researchers.

To help mitigate this we want to create a set of user stories to achieve the following:

- Add additional data access related questions/answers to the Study setup form in SequenceScape - forcing Research Managers to correctly consult with the Legal team when creating a study earlier.
- Export this additional data and possibly the data access agreement document itself to the MLWH database
- Work with Legal's developers to help them obtain and keep synchronised with the EDAM system.

A couple of things to note:

1. Studies can be created & edited at any time and samples moved between them.
2. The important study for EDAM is the study linked to the sequencing that produced the data specified in the sequencing submission.

**Acceptance Criteria**
The following outputs from the research are produced:
- [x] Work with the Lego & SSR team to define the required data fields and create Users Stories to implement them.
- [x] Keep the Lego developers appraised of the fields and design of extension to databases.
- [x] SSR team would like an additional user story to be able to bulk upload study data from a csv file generated from their Study Setup Form.
- [x] User stories should include testing with LeGo developers to ensure the correct studies are being associated with sequencing data that is released. _Q: Not sure how’s best to go about this, as this I believe this is down to the MLWH sample/study association being correct, before the Data Release Team pull in the data from MLWH, as the Sample Submission/ Sequencing steps aren’t being touched in this work._

**Who the primary contacts are for this work**
Laura B (Data Access Officer)
Mugdha K (Graduate Associate)
Liz C (SSR)
Odion A (Senior Web Developer) - EDAM  

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Comment by harrietc52** [comment]
Ludic Chart to gather thoughts [here](https://lucid.app/lucidchart/78803ef5-e0b4-4ec4-aba7-c5f074863201/edit?viewport_loc=-342%2C-12%2C1898%2C743%2C0_0&invitationId=inv_dff3ec0e-f058-41b7-96da-21b55a1b294e)

**Comment by harrietc52** [comment]
Non-Story specific questions
- does teh diagram show how iRODS/ EGA fit together correctly?
- what exactly is data release reffering too? Its used in a few contexts
- where do the data release team come in?
- “Update EBI” study data in SS”? Does this happen indirectly?
- Is the data release after all study samples are compelte?
- when a sample is sequenced, is the data auto added to iRODS?

**Comment by harrietc52** [comment]
BPM - flow charts - make linear, and decion points and loops

**Comment by harrietc52** [comment]
- Update Liz C with the final list of fields in Sequnecscape, as she is creating a Google form with these inputs and they want to align with Sequencescape

**Comment by harrietc52** [comment]
Outdated questions from stories. Move here to not clutter stories

**Y24-419 Questions**

Liz:

- [x] eDAM Study Title; In the Sequencescape Study creation page, the field which is currently being used to pull into eDAM is “**Title**", which is labelled an “ENA requirement”. Should it say ENA if it required for both ENA & EGA? Maybe we should remove the “ENA requirement” label?)
- [x]  eDAM Study Description; same as above, but for "Study description"

![Screenshot 2024-11-11 at 11 21 29](https://github.com/user-attachments/assets/28afe5b0-8014-4a0b-b369-7e8fb02e427b)

- [x] Where would you like these new fields to be added, in terms of the Study page, in a new subsection? At the top, near the bottom etc? Name of section on page? Would you want to show/hide this section by default?
_A: If they could appears in SS in the same order as they appear in eDAM2 that would be good I think. So this would be below the study title and description sections._
- [x] What would you like the toggle to be called? Maybe the `in_edam` eDAM question is the question we use for the toggle as to whether this eDAM section should be shown? If so, what would you like to do with the questions to show when `in_edam` is “No” (`non_sanger_dac_notes` and `non_sanger_dac_details`)?
- [x] When viewing the Study, where would you like the eDAM fields to appear

PSD

- [ ]  Check when this study data is sent to the MLWH? on “activation” or when study is submitted?

Please see [PSD Google Sheet with DAA fields](https://docs.google.com/spreadsheets/d/1Ya6YyBuoGNBV-6xFLfGHc1WuLjeVLjSlCOMQC6VCUhQ/edit?usp=sharing) cells in Red, for those under discussion

**Comment by harrietc52** [comment]
**Y24-419 Questions** 

Currently in Sequencescape Study set up, there is a `Study Name` field. Is this linked to the eDAM field `Study Title`? Would you like the “Hint” for this field in eDAM adding to Sequencescape?
> Regarding the Study Name field, I think so, but I can't say for sure. This is the query we run to get the studies from the MLWH: "select id_study_lims, description, accession_number, study_title, faculty_sponsor from study where data_release_strategy='managed' ", so it depends on whether the Study Name field in Sequencescape is inserted into the study table in the MLWH as study_title. Regarding the Hint, you can leave that out.

Currently in Sequencescape Study set up, under ENA specific questions there is a `Title` (`study_study_title`) and `Study Description` (`study_description`). Is the `Study Description` in eDAM different (not ENA specific), and if so, shall a new field for “Study Description" to the Sequencescape Study set up page? What would you like the text to show, and what would you like the field in MLWH to be?: 
> The Study Description in eDAM comes from the 'description' field in the study table in the MLWH. I think it's the ENA specific question, but I can't say for sure.

The same field name `collabs` refers to both name an institution. Should these fields be seperated to `collabs_name` and `collabs_institution`?: 
> No, leave as it is (see response to next question below)

There is a note in "eDAM DAA setup questions” - “Users must be able to add multiple collabs”. How would you like this to be persisted in the `study` table in MLWH? If there is more than one collaborator?
> Might be best to save it as a json array, so something like this: [ { collabName: "", collabInstitute: "" }, { collabName: "", collabInstitute: "" } ]. We can have a call to discuss this.

Is `want_pub_delay` needed? For example, could this field be removed and only the `publish_delay` field used, and set to 12 as default?: 
> Yeah, it can be removed. 

`ega_dataset_accession_numbers` What input is required for "Known EGA Dataset Accession numbers for this study”. What type is it? Is it required? It is missing from "eDAM DAA setup questions” Google Sheet below
> No input is required for this because the RMs don't enter this information. These are the datasets linked to the study, eDAM pulls these datasets from the EGA archive and displays them on this question.

What is the “Hint” text for each field? Please can it be added to the Google Sheet (see eDAM fields below) Do not all fields have a “Hint”?:
> Not all fields have hints.

Can we separate `non_sanger_dac_notes` into two serpate fields `non_sanger_dac_name` and `non_sanger_dac_email`?: 
> Yes this would be fine, it might make it a bit clearer and would be useful to ensure we have both the name and email address.

Could `dao_send_to_giselle` and `dao_send_to` be combined, to just be one field `dao_send_to`? By default the email is `datasharing@sanger`, or if not, input another email? Assume email requires `.ac.uk`? Then don't have a users name in a field. 
> Yeah, I'm happy with that, if Laura is happy with it as well
> As far as I know this should always be the datasharing mailbox, so yes it should default to this but have an option for something else just in case of odd situations.

Can `ez1_to_approve` be removed? And `sanger_approve_by` become one field? Which defaults to Sarion B email, or the manually entered email? Could `ez1`’s address be replaces with a non-personal / role level? (incase Sarion B ever left the institute). Also, in "eDAM DAA setup questions” doc it says Display when option 1 is selected for `ez1_to_approve`, is this correct, or should it display when “No” is selected for `ez1_to_approve`?: 
> Yeah, you can merge the fields, if Laura is happy with that. Regarding replacing Sarion's email with a role, we can discuss how that would work. You're right, it should be Option 2, I've updated the google sheet.
> As long as the approvals still go to Sarion then this is fine. If she left then I guess we would just update this to the email address of whoever took over doing approvals from her.

 In "eDAM DAA setup questions” doc it says Display when option 1 is selected for `in_edam `, is this correct, or should it display when “No” is selected for `in_edam `?
> It should display when "No" is selected, I've updated the google sheet.

Is `approved_by_lego` okay? A “yes”/ “No” input? Is the text description okay, or would you like anything adding? e.g.  “Confirm this study has been approved by LeGo and added to eDAM2 internal”. Would you like this to be nearer the start of the form? If “No”, can the user still submit the Study in Sequencescape?. 
> Could you clarify what role this question plays when answered?

Would you like all these questions to be in their own group, within the Study setup page? Where exactly would you like them to go on the form (at the bottom/ top etc?): 
>  If they could appears in SS in the same order as they appear in eDAM2 that would be good I think. So this would be below the study title and description sections.

Are all these questions only required if the Studies release strategy is EGA, or ENA, or Both (ie would these questions only want to appear if EGA/ENA checkbox is selected in Sequencescape set up form?): 
> These questions are only needed for managed access data held in EGA (not ENA), and only those using the standard WSI DAA (so if they’re using a different DAA like the DDD or CGP ones for example, then the questions aren’t needed).

**Comment by harrietc52** [comment]
**Y24-420 Questions**

Odion:

- [x] How is best to put a story in to the eDAMs dev cycle, requesting the ability for eDAM to pull in data from MLWH UAT DB? _A: You don't need to put a story in, once we are ready to pull from the MLWH UAT DB, i'll implement this on the eDAM2 dev_

- [x] In Sequencescape's Study edit page, we are going to add a note saying something like: “If you would like to update any of the eDAM required fields, please update these in eDAM directly.” Have you a URL for a Test and Production environment we can link to from this page, to make it easier for the users to update the fields in eDAM?
_A:
Internal eDAM2 dev: (https://edam-internal.dev.sanger.ac.uk/#/). 
Internal eDAM2 live: (https://edam-admin.sanger.ac.uk/#/)_

**Comment by harrietc52** [comment]
**Y24-422 Questions**

Liz:

- Where would you like this to appear? e.g. as a Link on the right pane “Bulk Study upload from CSV”, which opens to a new page?
- How's best to keep Sequencescape Study headers in sync with SSR Google Study Set Up Form? 


**Answers**

HI Harriet - in answer to your Qs for me above:
Q1 - yes, a button on the right hand side to allow "Bulk study upload from csv" would be perfect. Note that we still want to be able to do a study creation as we do at the moment by filling in each individual box - this would be an additional feature. We also still want to be able to edit individual fields for a study like we can at the moment
Q2 - good Q!! If there are changes that we need to make to the info we collect for studies, we will ensure we let psd know (I assume raise a new story for new fields that we need). Do we need to do any more than that?
