### ISSUE TITLE
Y24-378 - As a Data Release Manager (Quan L) I would like the "Cancer Genomics" option from the Study Type field on the Study setup page to be removed as this is no longer a valid option.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sequencescape#4408]
**User story**
As a Data Release Manager (Quan L) I would like the "Cancer Genomics" option from the Study Type field on the Study setup page to be removed as this is no longer a valid option.

**Who are the primary contacts for this story**
Quan L

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Users can no longer select "Cancer Genomics" from the Study Type combo box on the setup page.

**Additional context**
The Data Release team have to map the study information in SequenceScape to valid fields in EBI ENA database. The "Cancer Genomics" option cannot be mapped and already existing alternative options should be specified by SSRs & Research Managers. At present the data release team have to manually contact teams to work out option should have been specified at the point of data release - causing a delay.

**Comment by neilsycamore** [comment]
Now this is in UAT I can see a possible data issue.
Previously created studies are not going to have these 3x ebi_library_* fields populated and when editing a study in the SS UI these fields are going to be populated with the defaults set in the form without informing the user.
e.g. when SSR is asked to add a new user to the study's data access group

Should the validation be applied on the CREATE action rather on UPDATE?

**Comment by TWJW-SANGER** [comment]
@neilsycamore Good point. But to be nit picky the 3 x ebi_library fields are part of story #4409   

Although, your point is valid if users edit old studies that were using "Cancer Genomics" in the Study Type on the Edit Studies page.

I think it's worth checking what the behavior is on the Edit Study page in these cases, then think through the options. 
Assuming this is not a frequent use case, and the edit page behaves sensibly, one solution would be for users to raise a ticket when and if they need to do this.

**Comment by neilsycamore** [comment]
sigh.. the above comments should have been added to [4409](https://github.com/sanger/sequencescape/issues/4409) not this story
